Repository goblint/analyzer, pull requests merged in 2021-07, with the labels that each got.

#266 Fix ikind in Interval.invariant_ikind
  src/cdomains/intDomain.ml
Labels: bug

#269 Fix unsoundness due to `pthread_cond_wait`
  src/analyses/mutexAnalysis.ml
  tests/regression/13-privatized/67-pthread_cond_wait.c
Labels: unsound

#270 Change `enter`, `combine`, `FunctionEntry`, `Function` argument `varinfo` -> `fundec`
  src/analyses/apron/octApron.apron.ml
  src/analyses/apron/poly.apron.ml
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/condVars.ml
  src/analyses/constants.ml
  src/analyses/contain.ml
  src/analyses/deadlock.ml
  src/analyses/deadlocksByRaces.ml
  src/analyses/expRelation.ml
  src/analyses/extract_arinc.ml
  src/analyses/extract_osek.ml
  src/analyses/fileUse.ml
  src/analyses/flag.ml
  src/analyses/flagModes.ml
  src/analyses/mallocWrapperAnalysis.ml
  src/analyses/malloc_null.ml
  src/analyses/mayLocks.ml
  src/analyses/octagon.ml
  src/analyses/osek.ml
  src/analyses/osektransactionality.ml
  src/analyses/region.ml
  src/analyses/shapes.ml
  src/analyses/spec.ml
  src/analyses/stackTrace.ml
  src/analyses/termination.ml
  src/analyses/threadAnalysis.ml
  src/analyses/threadEscape.ml
  src/analyses/threadReturn.ml
  src/analyses/uninit.ml
  src/analyses/unit.ml
  src/analyses/varEq.ml
  src/cdomains/arincDomain.ml
  src/cdomains/basetype.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/framework/myCFG.ml
  src/framework/node.ml
  src/incremental/updateCil.ml
  src/util/tracing.ml
  src/witness/observerAnalysis.ml
  src/witness/witness.ml
  src/witness/witnessConstraints.ml
  src/witness/witnessUtil.ml
  tests/regression/02-base/51-spawn-special.c
  tests/regression/02-base/52-otherfun-special.c
  tests/regression/02-base/53-spawn-special-arg.c
  tests/regression/02-base/54-spawn-special-unknown.c
Labels: cleanup

#264 Serialize additional data for Gobview
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/framework/control.ml
  src/util/defaults.ml
  src/util/messages.ml
Labels: feature

#271 Allow running without base analysis
  src/domains/hoareDomain.ml
  src/framework/constraints.ml
  src/witness/witnessConstraints.ml
  tests/regression/02-base/51-empty-not-dead.c
  tests/regression/33-constants/01-const.c
  tests/regression/33-constants/02-simple.c
  tests/regression/33-constants/03-empty-not-dead-branch.c
  tests/regression/33-constants/04-empty-not-dead.c
Labels: bug, unsound

#276 Update scripts to use more portable shebang
  make.sh
  regtest.sh
  scripts/bisect.sh
  scripts/incremental.sh
  scripts/privPrecCompare-creduce.sh
  scripts/privPrecCompare.sh
  scripts/set_version.sh
  scripts/trace_off.sh
  scripts/trace_on.sh
  scripts/track_off.sh
  scripts/track_on.sh
  sv-comp/archive.sh
  sv-comp/benchexec/my-bench-sv-comp/goblint-all-fast.sh
  sv-comp/benchexec/my-bench-sv-comp/goblint-data-race.sh
  sv-comp/benchexec/my-bench-sv-comp/goblint.sh
  sv-comp/benchexec/my-bench/goblint.sh
Labels: practical-course, usability

#272 Merge relevant commits from SAS '21 artifact description
  docs/artifact-descriptions/sas21.md
  mkdocs.yml
  scripts/update_suite.rb
  src/analyses/apron/octApron.no-apron.ml
  src/analyses/apron/poly.no-apron.ml
  src/cdomains/apron/apronDomain.no-apron.ml
  src/cdomains/apron/octApronDomain.no-apron.ml
Labels: documentation

#283 Remove ppx_import
  _tags
  dune-project
  goblint.opam
  goblint.opam.locked
  src/analyses/base.ml
  src/analyses/basePriv.mli
  src/cdomains/basetype.ml
  src/cdomains/deadlockDomain.ml
  src/cdomains/exp.ml
  src/cdomains/lval.ml
  src/domains/mapDomain.ml
  src/domains/octagonMapDomain.ml
  src/domains/queries.ml
  src/dune
  src/framework/myCFG.ml
  src/framework/node.ml
  src/util/arincUtil.ml
  src/util/cilType.ml
  src/util/deriving.ml
  src/witness/myARG.ml
Labels: cleanup

#277 Replace `Cil.typeOf` with `Cilfacade.typeOf` which uses sensible exceptions
  src/analyses/apron/octApron.apron.ml
  src/analyses/apron/poly.apron.ml
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/contain.ml
  src/analyses/expRelation.ml
  src/analyses/extract_arinc.ml
  src/analyses/octagon.ml
  src/analyses/osek.ml
  src/analyses/termination.ml
  src/analyses/varEq.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/containDomain.ml
  src/cdomains/intDomain.ml
  src/cdomains/regionDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/access.ml
  src/util/cilfacade.ml
  src/witness/myARG.ml
Labels: cleanup

#280 OCaml 4.11.1 -> 4.12.0
  .github/workflows/tests.yml
  goblint.opam.locked
  make.sh
Labels: setup

#274 Remove unnecessary Skip and Neg(1) edges from CFG
  .gitignore
  src/framework/myCFG.ml
  src/maingoblint.ml
  src/util/defaults.ml
  tests/regression/00-sanity/19-if-0.c
  tests/regression/00-sanity/20-if-0-realnode.c
  tests/regression/00-sanity/21-empty-loops.c
  tests/regression/03-practical/22-nested-infinite-loops.c
Labels: bug, cleanup, usability

#260 Add congruence integer domain and enable mutual refinement of the integer domains
  .gitignore
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/maindomaintest.ml
  src/util/defaults.ml
  tests/regression/37-congruence/01-simple.c
  tests/regression/37-congruence/02-constants.c
  tests/regression/37-congruence/03-interval-overflow.c
  tests/regression/37-congruence/04-branching.c
  tests/regression/37-congruence/05-implicitunsignedconversion-1.c
  tests/regression/38-int-refinements/01-interval-congruence.c
Labels: feature, practical-course, precision

#286 Undo update_suite ignoring precision difference for UNKNOWN
  scripts/update_suite.rb
  tests/regression/00-sanity/19-update_suite.c
  tests/regression/31-ikind-aware-ints/13-intervals-large.c
Labels: bug, precision, testing

#295 Add column to location
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/framework/myCFG.ml
Labels: feature, usability

#299 Add output of location columns
  scripts/update_suite.rb
  src/analyses/basePriv.ml
  src/analyses/deadlock.ml
  src/analyses/extract_arinc.ml
  src/analyses/extract_osek.ml
  src/analyses/mallocWrapperAnalysis.ml
  src/analyses/osek.ml
  src/analyses/termination.ml
  src/analyses/threadAnalysis.ml
  src/cdomains/arincDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/concDomain.ml
  src/cdomains/deadlockDomain.ml
  src/cdomains/lvalMapDomain.ml
  src/cdomains/stackDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/access.ml
  src/domains/octagonMapDomain.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/framework/myCFG.ml
  src/framework/node.ml
  src/privPrecCompare.ml
  src/solvers/generic.ml
  src/solvers/sLRphased.ml
  src/solvers/sLRterm.ml
  src/solvers/topDown.ml
  src/solvers/topDown_deprecated.ml
  src/solvers/topDown_space_cache_term.ml
  src/solvers/topDown_term.ml
  src/transform/expressionEvaluation.ml
  src/transform/transform.ml
  src/util/cilType.ml
  src/util/deadcode.ml
  src/util/messages.ml
  src/util/privPrecCompareUtil.ml
  src/util/tracing.ml
Labels: usability

#294 Clean up `MyCFG` and refactor CIL helper mappings
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/contain.ml
  src/analyses/extract_arinc.ml
  src/analyses/extract_osek.ml
  src/analyses/mallocWrapperAnalysis.ml
  src/analyses/osek.ml
  src/cdomains/arincDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/containDomain.ml
  src/domains/invariantCil.ml
  src/framework/analyses.ml
  src/framework/cfgTools.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/framework/edge.ml
  src/framework/myCFG.ml
  src/framework/node.ml
  src/incremental/updateCil.ml
  src/solvers/generic.ml
  src/solvers/td3.ml
  src/util/cilfacade.ml
  src/util/tracing.ml
  src/witness/myARG.ml
  src/witness/observerAnalysis.ml
  src/witness/witness.ml
  src/witness/witnessConstraints.ml
Labels: cleanup

#300 Move `pretty_diff` from `Printable.S` to `Lattice.S`
  src/analyses/mCP.ml
  src/cdomains/arincDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/containDomain.ml
  src/cdomains/deadlockDomain.ml
  src/cdomains/exp.ml
  src/cdomains/lval.ml
  src/cdomains/unionDomain.ml
  src/domains/access.ml
  src/domains/boolDomain.ml
  src/domains/lattice.ml
  src/domains/mapDomain.ml
  src/domains/octagonDomain.ml
  src/domains/printable.ml
  src/domains/queries.ml
  src/domains/setDomain.ml
  src/framework/analyses.ml
  src/maingoblint.ml
  src/util/cilType.ml
  src/util/hash.ml
  src/witness/witnessConstraints.ml
Labels: cleanup

#302 Fix unsoundness of Modulo Operations involving negative numbers #301
  src/cdomains/intDomain.ml
  src/util/intOps.ml
  tests/regression/00-sanity/22-modulo.c
  tests/regression/00-sanity/23-modulo-interval.c
Labels: bug, unsound

#307 Clean up variable grouping using magic lines -3 and -4
  src/analyses/octagon.ml
  src/cdomains/basetype.ml
  src/cdomains/lval.ml
  src/framework/cfgTools.ml
  src/util/cilfacade.ml
Labels: cleanup

#303 Make use of congruences in invariant
  src/analyses/base.ml
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/util/intOps.ml
  tests/regression/37-congruence/06-refinements.c
  tests/regression/37-congruence/07-refinements-o.c
Labels: precision

#308 check indentation of changes on GitHub
  .github/workflows/indentation.yml
Labels: setup

#305 Fix more CFG display issues
  src/framework/cfgTools.ml
  src/framework/control.ml
  src/framework/node.ml
  src/incremental/updateCil.ml
  src/transform/expressionEvaluation.ml
  src/transform/transform.ml
  src/util/cilfacade.ml
  src/witness/witnessUtil.ml
Labels: bug, usability

#291 Relational traces implementation, octApron fixes & refactoring
  src/analyses/apron/octApron.apron.ml
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/commonPriv.ml
  src/analyses/octApronPriv.ml
  src/analyses/octagon.ml
  src/cdomains/apron/octApronDomain.apron.ml
  src/dune
  src/util/cilfacade.ml
  src/util/defaults.ml
  tests/regression/36-octapron/03-problem-signextension.c
  tests/regression/36-octapron/08-problem-implicitunsignedconversion.c
  tests/regression/36-octapron/08-problem-signed-unsigned-overflow.c
  tests/regression/36-octapron/11-traces-max-simple.c
  tests/regression/36-octapron/12-traces-min-rpb1.c
  tests/regression/36-octapron/13-traces-min-rpb2.c
  tests/regression/36-octapron/14-traces-unprot.c
  tests/regression/36-octapron/15-globals-st.c
  tests/regression/36-octapron/16-traces-unprot2.c
  tests/regression/36-octapron/17-traces-rpb-litmus.c
  tests/regression/36-octapron/18-branch2.c
  tests/regression/36-octapron/19-traces-other-rpb.c
  tests/regression/36-octapron/20-traces-even-more-rpb.c
  tests/regression/36-octapron/21-traces-cluster-based.c
  tests/regression/36-octapron/22-traces-write-centered-vs-meet-mutex.c
  tests/regression/36-octapron/23-traces-write-centered-problem.c
  tests/regression/36-octapron/24-combine-no-lval.c
  tests/regression/36-octapron/25-combine-global.c
  tests/regression/36-octapron/26-combine-forget-local-lval.c
  tests/regression/36-octapron/27-combine-forget-fun-lval.c
  tests/regression/36-octapron/28-combine-forget-fun-lval-imprecise.c
  tests/regression/36-octapron/29-combine-arg-var-conflict.c
  tests/regression/36-octapron/30-return-global.c
  tests/regression/36-octapron/31-combine-global-lval.c
  tests/regression/36-octapron/32-typedef.c
  tests/regression/36-octapron/33-large-int64.c
  tests/regression/36-octapron/34-large-bigint.c
  tests/regression/36-octapron/35-rational-value.c
  tests/regression/36-octapron/36-special-unknown-globals.c
  tests/regression/36-octapron/37-special-unknown-lval.c
  tests/regression/36-octapron/60-evalint-interval.c
Labels: cleanup, feature, precision, unsound

#293 Document how to develop goblint-cil in conjunction with Goblint
  docs/developer-guide/developing.md
Labels: documentation
