Repository goblint/analyzer, pull requests merged in 2021-08, with the labels that each got.

#296 Fix CI to correctly use OCaml version matrix
  .github/workflows/locked.yml
  .github/workflows/tests.yml
  .github/workflows/unlocked.yml
  README.md
Labels: cleanup, testing, setup

#326 Pin ppx_deriving fork with forwarding optimizations
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
Labels: performance

#313 Make Spec & Inc arguments of the functor AnalyzeCFG
  src/framework/control.ml
Labels: cleanup

#315 Use fork of Zarith
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
Labels: setup

#321 OctApron: Support branched thread creation
  src/analyses/apron/octApronPriv.apron.ml
  tests/regression/36-octapron/61-branched.c
  tests/regression/36-octapron/62-branched_intricate.c
  tests/regression/36-octapron/63-branched-not-too-brutal.c
Labels: bug, unsound

#324 Fix octApron branch, enter & combine not handling globals
  conf/svcomp21.json
  src/analyses/apron/octApron.apron.ml
  src/analyses/apron/octApronPriv.apron.ml
  src/cdomains/apron/octApronDomain.apron.ml
  tests/regression/36-octapron/38-branch-global.c
  tests/regression/36-octapron/39-enter-global-arg.c
  tests/regression/36-octapron/40-rational-bounds.c
  tests/regression/36-octapron/41-threadenter-no-locals.c
  tests/regression/36-octapron/42-threadenter-arg.c
Labels: bug

#328 Add subexpression overflow checking to octApron
  src/analyses/apron/octApron.apron.ml
  src/cdomains/apron/octApronDomain.apron.ml
  src/util/defaults.ml
  tests/regression/31-ikind-aware-ints/07-defexc-large.c
  tests/regression/31-ikind-aware-ints/13-intervals-large.c
  tests/regression/31-ikind-aware-ints/14-enums-large.c
  tests/regression/36-octapron/19-traces-other-rpb.c
  tests/regression/36-octapron/21-traces-cluster-based.c
  tests/regression/36-octapron/22-traces-write-centered-vs-meet-mutex.c
  tests/regression/36-octapron/23-traces-write-centered-problem.c
  tests/regression/36-octapron/28-combine-forget-fun-lval-imprecise.c
  tests/regression/36-octapron/29-combine-arg-var-conflict.c
  tests/regression/36-octapron/31-combine-global-lval.c
  tests/regression/36-octapron/35-rational-value.c
  tests/regression/36-octapron/36-special-unknown-globals.c
  tests/regression/36-octapron/61-evalint-overflow.c
Labels: bug, unsound

#304 Add global option to assume no overflows for signed types
  conf/svcomp.json
  src/analyses/apron/octApron.apron.ml
  src/cdomains/apron/octApronDomain.apron.ml
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/util/defaults.ml
  tests/regression/01-cpa/10-posneg.c
  tests/regression/27-inv_invariants/01-ints.c
  tests/regression/31-ikind-aware-ints/09-signed-negate.c
  tests/regression/31-ikind-aware-ints/13-intervals-large.c
  tests/regression/31-ikind-aware-ints/14-enums-large.c
  tests/regression/36-octapron/70-signed-overflows.c
  tests/regression/37-congruence/01-simple.c
  tests/regression/37-congruence/02-constants.c
  tests/regression/37-congruence/04-branching.c
  tests/regression/37-congruence/05-implicitunsignedconversion-1.c
  tests/regression/37-congruence/06-refinements.c
  tests/regression/39-signed-overflows/01-def_exc.c
  tests/regression/39-signed-overflows/02-intervals.c
Labels: cleanup, feature

#322 Remove `exp.full_context` and `val_of`
  src/analyses/apron/octApron.apron.ml
  src/analyses/apron/poly.apron.ml
  src/analyses/arinc.ml
  src/analyses/constants.ml
  src/analyses/mCP.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/maingoblint.ml
  src/util/defaults.ml
  src/witness/witnessConstraints.ml
Labels: cleanup

#334 Congruence: Account for overflow for definite values in normalize
  src/cdomains/intDomain.ml
  tests/regression/38-int-refinements/03-more-problem.c
Labels: bug, unsound
