Repository goblint/analyzer, pull requests merged in 2021-09, with the labels that each got.

#337 Add semgrep for custom scanning of Goblint code
  .github/workflows/semgrep.yml
  .semgrep/cil.yml
  .semgrep/tracing.yml
  src/cdomains/intDomain.ml
  src/framework/cfgTools.ml
  src/solvers/generic.ml
Labels: cleanup, setup

#341 Add optional Z3 dependency for conditional ViolationZ3 build
  dune-project
  goblint.opam
  src/domains/hoareDomain.ml
  src/dune
  src/util/gobConfig.ml
  src/witness/witness.ml
  src/witness/z3/dune
  src/witness/z3/violationZ3.no-z3.ml
  src/witness/z3/violationZ3.z3.ml
Labels: cleanup, bug, usability

#342 Replace our own JSON library with Yojson
  src/analyses/arinc.ml
  src/analyses/baseUtil.ml
  src/analyses/commonPriv.ml
  src/analyses/contain.ml
  src/analyses/extract_arinc.ml
  src/analyses/extract_osek.ml
  src/analyses/flagModes.ml
  src/analyses/mCP.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/osek.ml
  src/cdomains/intDomain.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/maingoblint.ml
  src/util/arincUtil.ml
  src/util/cilfacade.ml
  src/util/defaults.ml
  src/util/dune
  src/util/gobConfig.ml
  src/util/gobYojson.ml
  src/util/goblintutil.ml
  src/util/json.ml
  src/util/jsonLexer.mll
  src/util/jsonParser.mly
  src/util/jsonSchema.ml
  src/witness/witness.ml
Labels: cleanup

#343 Rewrite instructions in README
  README.md
Labels: usability, documentation, setup

#338 Refactor and generalize warning system to message system
  docs/developer-guide/messaging.md
  docs/developer-guide/warning.md
  mkdocs.yml
  scripts/set_version.sh
  scripts/track_off.sh
  scripts/track_on.sh
  scripts/update_suite.rb
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/commonPriv.ml
  src/analyses/condVars.ml
  src/analyses/contain.ml
  src/analyses/deadlock.ml
  src/analyses/extract_arinc.ml
  src/analyses/extract_osek.ml
  src/analyses/fileUse.ml
  src/analyses/libraryFunctions.ml
  src/analyses/mCP.ml
  src/analyses/malloc_null.ml
  src/analyses/mayLocks.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/osek.ml
  src/analyses/region.ml
  src/analyses/spec.ml
  src/analyses/symbLocks.ml
  src/analyses/termination.ml
  src/analyses/uninit.ml
  src/analyses/varEq.ml
  src/cdomains/arincDomain.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/containDomain.ml
  src/cdomains/intDomain.ml
  src/cdomains/lval.ml
  src/cdomains/lvalMapDomain.ml
  src/cdomains/regionDomain.ml
  src/cdomains/shapeDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/access.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/maingoblint.ml
  src/solvers/generic.ml
  src/util/arincUtil.ml
  src/util/cilType.ml
  src/util/cilfacade.ml
  src/util/defaults.ml
  src/util/gobFormat.ml
  src/util/messageCategory.ml
  src/util/messageUtil.ml
  src/util/messages.ml
  tests/regression/04-mutex/58-strange-spawn.c
Labels: cleanup, feature, usability

#310 Fix "escaping" via recursion
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/base.ml
  src/analyses/varEq.ml
  src/cdomains/baseDomain.ml
  src/domains/partitionDomain.ml
  src/domains/queries.ml
  src/util/cilfacade.ml
  tests/regression/01-cpa/52-escaping-recursion.c
  tests/regression/01-cpa/53-escaping-recursion-varEq.c
Labels: bug, unsound

#325 Make loops strict w.r.t. entry edges
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/edge.ml
  src/solvers/effectWCon.ml
  src/solvers/effectWConEq.ml
  src/solvers/generic.ml
  src/solvers/sLR.ml
  src/solvers/sLRphased.ml
  src/solvers/sLRterm.ml
  src/solvers/td3.ml
  src/solvers/topDown.ml
  src/solvers/topDown_deprecated.ml
  src/solvers/topDown_space_cache_term.ml
  src/solvers/topDown_term.ml
  src/solvers/worklist.ml
  tests/regression/00-sanity/26-strict-loop-enter.c
Labels: cleanup, precision

#331 Add thread IDs with history
  .git-blame-ignore-revs
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/osek.ml
  src/analyses/threadAnalysis.ml
  src/analyses/threadFlag.ml
  src/analyses/threadId.ml
  src/cdomains/concDomain.ml
  src/cdomains/threadFlagDomain.ml
  src/cdomains/threadIdDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/events.ml
  src/domains/lattice.ml
  src/domains/printable.ml
  src/domains/queries.ml
  tests/regression/40-threadid/01-threadid_history_unique.c
  tests/regression/40-threadid/02-threadid_history_nonunique.c
  tests/regression/40-threadid/03-threadid_history_two_unique.c
Labels: feature, precision

#262 Simple tutorial for getting started
  docs/developer-guide/firstanalysis.md
  docs/user-guide/inspecting.md
  make.sh
  mkdocs.yml
  src/analyses/tutorials/constants.ml
  src/analyses/tutorials/signs.ml
  src/analyses/tutorials/unit.ml
  src/cdomains/basetype.ml
  src/cdomains/intDomain.ml
  src/cdomains/osektupel.ml
  src/domains/printable.ml
  src/framework/analyses.ml
  src/maindomaintest.ml
  tests/regression/13-privatized/53-pfscan_widen_dependent_minimal.c
  tests/regression/13-privatized/54-widen-dependent.c
  tests/regression/13-privatized/55-widen-dependent-local.c
  tests/regression/99-tutorials/01-first.c
Labels: cleanup, documentation

#345 Make malloc-ed variables non-unique
  src/analyses/base.ml
  src/analyses/mCP.ml
  src/analyses/mallocWrapperAnalysis.ml
  tests/regression/02-base/60-malloc-nonrefl.c
Labels: bug, unsound

#354 Fix analysis auxiliary data marshaling
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/contain.ml
  src/analyses/deadlock.ml
  src/analyses/deadlocksByRaces.ml
  src/analyses/extract_arinc.ml
  src/analyses/extract_osek.ml
  src/analyses/flag.ml
  src/analyses/flagModes.ml
  src/analyses/mCP.ml
  src/analyses/mallocWrapperAnalysis.ml
  src/analyses/malloc_null.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/osek.ml
  src/analyses/osektransactionality.ml
  src/analyses/region.ml
  src/analyses/shapes.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/witness/witnessConstraints.ml
Labels: bug

#358 Remove dependence of the incremental analysis on Git
  conf/incremental.json
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/incremental/compareAST.ml
  src/incremental/git.ml
  src/incremental/serialize.ml
  src/incremental/updateCil.ml
  src/incremental/versionLookup.ml
  src/maingoblint.ml
  src/solvers/effectWConEq.ml
  src/solvers/generic.ml
  src/solvers/sLR.ml
  src/solvers/sLRphased.ml
  src/solvers/sLRterm.ml
  src/solvers/td3.ml
  src/solvers/topDown.ml
  src/solvers/topDown_deprecated.ml
  src/solvers/topDown_space_cache_term.ml
  src/solvers/topDown_term.ml
  src/solvers/worklist.ml
  src/util/defaults.ml
  src/util/goblintutil.ml
Labels: feature, usability

#362 Change "make debug" command so that it uses dune.
  docs/developer-guide/debugging.md
  dune
  make.sh
  src/dune
Labels: cleanup, setup

#336 Fix enums leq
  src/cdomains/intDomain.ml
  src/util/goblintutil.ml
  tests/regression/31-ikind-aware-ints/17-def-enum-refine.c
Labels: bug

#360 Optimize recursive struct type comparison in `CompareAST`
  src/incremental/compareAST.ml
  src/incremental/versionLookup.ml
Labels: bug, performance

#356 Incremental/compatibility-updates
  conf/incremental.json
  scripts/incremental.sh
  scripts/incremental_avg.sh
  src/analyses/mallocWrapperAnalysis.ml
  src/analyses/preMallocWrapperAnalysis.ml
  src/cdomains/basetype.ml
  src/cdomains/lval.ml
  src/framework/cfgTools.ml
  src/framework/node.ml
  src/incremental/serialize.ml
  src/solvers/td3.ml
  src/util/defaults.ml
Labels: bug
