Repository goblint/analyzer, pull requests merged in 2021-04, with the labels that each got.

#164 Optimize large CPAs
  src/analyses/basePriv.ml
  src/cdomains/baseDomain.ml
  src/cdomains/lvalMapDomain.ml
  src/domains/lattice.ml
  src/domains/mapDomain.ml
  src/domains/printable.ml
  src/framework/constraints.ml
  src/witness/witnessConstraints.ml
Labels: performance

#182 Make known functions in unknown AD still reachable
  src/analyses/base.ml
  tests/regression/02-base/46-spawn-global-funptrs.c
Labels: unsound

#174 Re-enable some int domain tests with fixed ikinds
  src/cdomains/circular_intervals/intOps.ml
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/domains/domainProperties.ml
  src/domains/intDomainProperties.ml
  src/maindomaintest.ml
Labels: testing

#190 Didactical Toy Analysis
  src/analyses/constants.ml
  tests/regression/27-inv_invariants/08-bor-inv.c
  tests/regression/33-constants/01-const.c
  tests/regression/33-constants/02-simple.c
Labels: usability

#191 Fix unsoundness when thread escape analysis is disabled
  src/analyses/base.ml
  src/analyses/threadEscape.ml
  tests/regression/02-base/09-ambigpointer.c
  tests/regression/02-base/47-no-threadescape.c
  tests/regression/22-partitioned_arrays/01-simple_array.c
  tests/regression/22-partitioned_arrays/02-pointers_array.c
  tests/regression/22-partitioned_arrays/03-multidimensional_arrays.c
  tests/regression/22-partitioned_arrays/04-nesting_arrays.c
  tests/regression/22-partitioned_arrays/05-adapted_from_01_09_array.c
  tests/regression/22-partitioned_arrays/06-interprocedural.c
  tests/regression/22-partitioned_arrays/10-array_octagon.c
  tests/regression/23-partitioned_arrays_last/01-simple_array.c
  tests/regression/23-partitioned_arrays_last/02-pointers_array.c
  tests/regression/23-partitioned_arrays_last/03-multidimensional_arrays.c
  tests/regression/23-partitioned_arrays_last/04-nesting_arrays.c
  tests/regression/23-partitioned_arrays_last/05-adapted_from_01_09_array.c
  tests/regression/23-partitioned_arrays_last/06-interprocedural.c
  tests/regression/23-partitioned_arrays_last/10-array_octagon.c
  tests/regression/23-partitioned_arrays_last/13-advantage_for_last.c
  tests/regression/23-partitioned_arrays_last/14-replace_with_const.c
  tests/regression/25-vla/02-loop.c
  tests/regression/25-vla/04-passing_ptr_to_array.c
  tests/regression/25-vla/05-more_passing.c
  tests/regression/25-vla/06-even_more_passing.c
  tests/regression/31-ikind-aware-ints/04-ptrdiff.c
Labels: bug, unsound

#166 Fix Hashconsing & Marshaling of Results
  .github/workflows/tests.yml
  .gitignore
  scripts/update_suite.rb
  src/analyses/mutexAnalysis.ml
  src/analyses/uninit.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/exp.ml
  src/cdomains/fileDomain.ml
  src/cdomains/intDomain.ml
  src/cdomains/lval.ml
  src/cdomains/lvalMapDomain.ml
  src/cdomains/osektupel.ml
  src/cdomains/specDomain.ml
  src/domains/access.ml
  src/domains/mapDomain.ml
  src/domains/octagonMapDomain.ml
  src/domains/printable.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/maindomaintest.ml
  src/util/gobConfig.ml
  src/witness/witness.ml
  src/witness/witnessConstraints.ml
  tests/regression/14-osek/01-privatize.c
  tests/regression/14-osek/02-example.c
  tests/regression/14-osek/03-example_fun.c
  tests/regression/14-osek/07-bad_flags.c
  tests/regression/14-osek/08-flipped_flags.c
  tests/regression/14-osek/09-resource_flags.c
  tests/regression/14-osek/10-weak_flags.c
  tests/regression/14-osek/11-bad_flags2.c
  tests/regression/14-osek/12-good-flags.c
  tests/regression/14-osek/13-pretty-flags.c
  tests/regression/14-osek/14-high_low_read_write.c
  tests/regression/14-osek/15-startuphook.c
  tests/regression/14-osek/16-activateTask.c
  tests/regression/16-relinv/01-flag.c
  tests/regression/17-arinc/02-unique_proc.c
Labels: bug

#203 Use variant type group in `MapDomain.Groupable` with `deriving show`
  src/cdomains/basetype.ml
  src/cdomains/lval.ml
  src/cdomains/shapeDomain.ml
  src/domains/mapDomain.ml
  src/domains/printable.ml
Labels: cleanup, type-safety

#194 Remove references to unmaintained CIL extensions
  src/util/cilfacade.ml
Labels: cleanup

#204 Fix witness generation and HoareMap
  src/domains/domainProperties.ml
  src/domains/setDomain.ml
  src/framework/constraints.ml
  src/maindomaintest.ml
  src/util/cilfacade.ml
  src/witness/witnessConstraints.ml
Labels: bug, sv-comp
