Repository goblint/analyzer, pull requests merged in 2021-11, with the labels that each got.

#417 Relational mutex-meet clustering
  src/analyses/apron/apronPriv.apron.ml
  src/util/defaults.ml
  tests/regression/36-apron/91-traces-mutex-meet-cluster12.c
  tests/regression/36-apron/92-traces-mutex-meet-cluster2.c
Labels: feature, precision

#414 Fix invalid interval widening calls
  src/cdomains/addressDomain.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/intDomain.ml
  src/domains/hoareDomain.ml
  src/domains/lattice.ml
  src/domains/octagonMapDomain.ml
Labels: bug

#418 Make Apron domain configurable
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/apron/apronPriv.apron.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/dune
  src/util/defaults.ml
  tests/regression/36-apron/71-simple-apron-interval.c
  tests/regression/36-apron/72-simple-polyhedra.c
Labels: feature

#422 Minimize Docker image, publish to GitHub Container Registry
  .github/dependabot.yml
  .github/workflows/docker.yml
  .gitignore
  Dockerfile
  README.md
  docker-compose.test.yml
  make.sh
Labels: usability, setup

#409 Incremental TD3: incrementalize analysis within functions
  scripts/incremental.sh
  src/framework/analyses.ml
  src/framework/cfgTools.ml
  src/framework/node.ml
  src/incremental/compareAST.ml
  src/incremental/compareCFG.ml
  src/incremental/compareCIL.ml
  src/incremental/updateCil.ml
  src/incremental/versionLookup.ml
  src/maingoblint.ml
  src/solvers/td3.ml
  src/util/cilfacade.ml
  src/util/defaults.ml
Labels: feature, performance

#424 Fix apron mutex-meet-tid-cluster decreasing protecting locksets
  src/analyses/apron/apronPriv.apron.ml
Labels: bug

#410 Add semgrep rules for List.length and List.combine
  .semgrep/list.yml
  .semgrep/option.yml
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/contain.ml
  src/analyses/deadlock.ml
  src/analyses/extract_arinc.ml
  src/analyses/extract_osek.ml
  src/analyses/fileUse.ml
  src/analyses/osek.ml
  src/analyses/shapes.ml
  src/analyses/spec.ml
  src/cdomains/fileDomain.ml
  src/cdomains/stackDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/octagonMapDomain.ml
  src/domains/printable.ml
  src/extract/pml.ml
  src/framework/cfgTools.ml
  src/framework/control.ml
  src/incremental/compareAST.ml
  src/incremental/compareCIL.ml
  src/incremental/updateCil.ml
  src/maingoblint.ml
  src/solvers/td3.ml
  src/util/arincUtil.ml
  src/util/myLiveness.ml
  src/witness/witness.ml
Labels: cleanup, performance

#376 SARIF output format
  .gitignore
  src/framework/analyses.ml
  src/maingoblint.ml
  src/util/defaults.ml
  src/util/messageCategory.ml
  src/util/sarif.ml
  src/util/sarifRules.ml
  src/util/sarifType.ml
Labels: feature, usability, student-job

#431 Fix symb_locks combine to use returned lockset
  src/analyses/symbLocks.ml
  src/cdomains/lockDomain.ml
  tests/regression/06-symbeq/26-symb_lockfuns.c
  tests/regression/06-symbeq/27-symb_no_lockfuns.c
  tests/regression/06-symbeq/28-symb_lockset_unsound.c
  tests/regression/06-symbeq/29-symb_lockfun_unsound.c
  tests/regression/06-symbeq/30-symb_lockset_mayunlock.c
Labels: bug

#433 Add option to store local results of Apron-Analysis for comparison
  .gitignore
  make.sh
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/apron/apronPriv.apron.ml
  src/analyses/basePriv.ml
  src/apronPrecCompare.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/dune
  src/privPrecCompare.ml
  src/util/apron/apronPrecCompareUtil.apron.ml
  src/util/apron/apronPrecCompareUtil.no-apron.ml
  src/util/apron/dune
  src/util/defaults.ml
  src/util/precCompare.ml
  src/util/precCompareUtil.ml
  src/util/privPrecCompareUtil.ml
Labels: feature, benchmarking

#364 TD3: optimize destabilization by aborting transfer function when unchanged
  scripts/creduce-abort-verify.sh
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/maingoblint.ml
  src/solvers/generic.ml
  src/solvers/td3.ml
  src/util/defaults.ml
  src/util/goblintutil.ml
  tests/regression/04-mutex/59-td3-self-abort.c
  tests/regression/29-svcomp/27-td3-front-via-destab-infl.c
  tests/regression/36-apron/71-td3-self-abort-complex.c
Labels: feature, performance

#437 Remove unnecessary export of AD by Apron privatizations.
  src/analyses/apron/apronPriv.apron.ml
Labels: cleanup

#438 Improve interval overflow detection
  src/cdomains/intDomain.ml
  src/util/goblintutil.ml
  src/witness/witness.ml
  tests/regression/50-juliet/01-CWE190_Integer_Overflow__01.c
  tests/regression/50-juliet/02-CWE190_Integer_Overflow__02.c
  tests/regression/50-juliet/03-CWE190_Integer_Overflow__03.c
  tests/regression/50-juliet/04-CWE191_Integer_Underflow__01.c
  tests/regression/50-juliet/05-CWE191_Integer_Underflow__02.c
  tests/regression/50-juliet/06-CWE191_Integer_Underflow__03.c
Labels: feature, bug, usability

#439 Optimize `eval_rv` for addresses in base `query`
  src/analyses/base.ml
Labels: performance

#440 Switch Apron oct and box to double
  src/cdomains/apron/apronDomain.apron.ml
  src/dune
  tests/regression/36-apron/33-large-int64.c
  tests/regression/36-apron/34-large-bigint.c
Labels: performance

#436 Add devcontainer
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.env
  .devcontainer/devcontainer.json
  Dockerfile
  README.md
  make.sh
Labels: usability, setup

#444 Fix dune file for PrecCompare tools
  src/dune
Labels: bug, setup

#446 Fix signed conversion overflow unsoundness with assume_none
  src/analyses/base.ml
  src/cdomains/intDomain.ml
  tests/regression/39-signed-overflows/03-cast-return-void-ptr.c
  tests/regression/39-signed-overflows/04-cast-unsigned-to-signed.c
Labels: bug, unsound, sv-comp

#450 Remove outdated and broken ocamlbuild
  _tags
  dune-project
  goblint.opam
  make.sh
  src/dune
Labels: cleanup, setup

#443 TD3: optimize switch to narrow by reusing computed right-hand side
  src/solvers/td3.ml
Labels: performance

#448 Add Compilation Database support
  src/analyses/contain.ml
  src/incremental/makefileUtil.ml
  src/maingoblint.ml
  src/util/compilationDatabase.ml
  src/util/defaults.ml
  src/util/gobFilename.ml
  src/util/gobSys.ml
  src/util/gobUnix.ml
  src/util/goblintutil.ml
Labels: feature, usability, benchmarking

#449 Add location ranges to output
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  scripts/update_suite.rb
  src/analyses/arinc.ml
  src/analyses/mallocWrapperAnalysis.ml
  src/analyses/termination.ml
  src/analyses/threadId.ml
  src/framework/cfgTools.ml
  src/incremental/compareAST.ml
  src/util/cilType.ml
  src/util/cilfacade.ml
  src/util/sarif.ml
  src/witness/myARG.ml
  tests/regression/12-containment/01-analyse.c
Labels: feature, usability

#453 Make unit tests run via dune
  make.sh
  src/domains/intDomainProperties.ml
  src/dune
  unittest/cdomains/generalArrayTest.ml
  unittest/cdomains/intDomainTest.ml
  unittest/domains/mapDomainTest.ml
  unittest/dune
  unittest/mainTest.ml
  unittest/solver/solverTest.ml
Labels: cleanup, testing, setup

#455 Remove generation of goblint.ml with all opens
  .gitignore
  make.sh
  scripts/set_version.sh
  scripts/trace_off.sh
  scripts/trace_on.sh
  src/dune
  src/goblint.ml
  src/maingoblint.ml
  src/util/gobConfig.ml
  src/util/messages.ml
  src/util/tracing.ml
  src/version.ml
Labels: cleanup, setup

#347 Add CITATION file
  CITATION.cff
  dune-project
Labels: documentation

#456 Fix: max vid computation in incremental analysis
  scripts/incremental.sh
  src/incremental/updateCil.ml
  src/incremental/versionLookup.ml
Labels: bug

#457 Add shorthand for `--set`
  src/maingoblint.ml
Labels: feature, usability

#353 Extract and fix dead branch detection
  scripts/update_suite.rb
  src/analyses/base.ml
  src/framework/constraints.ml
  src/framework/control.ml
  tests/regression/50-juliet/07-CWE570_Expression_Always_False__01.c
  tests/regression/50-juliet/08-CWE570_Expression_Always_False__02.c
  tests/regression/50-juliet/09-CWE570_Expression_Always_False__03.c
  tests/regression/50-juliet/10-CWE571_Expression_Always_True__01.c
  tests/regression/50-juliet/11-CWE571_Expression_Always_True__02.c
  tests/regression/50-juliet/12-CWE571_Expression_Always_True__03.c
Labels: cleanup, bug

#462 Set length of arrays during fast_global_inits
  src/cdomains/arrayDomain.ml
  src/cdomains/valueDomain.ml
  tests/regression/26-undefined_behavior/15-oob_init.c
Labels: bug, precision

#395 Annotated Precision
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/base.ml
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/cdomains/valueDomain.ml
  src/framework/constraints.ml
  src/util/contextUtil.ml
  src/util/defaults.ml
  src/util/precisionUtil.ml
  tests/regression/42-annotated-precision/01-def_exc.c
  tests/regression/42-annotated-precision/02-interval.c
  tests/regression/42-annotated-precision/03-congruence.c
  tests/regression/42-annotated-precision/04-struct.c
  tests/regression/42-annotated-precision/05-array.c
  tests/regression/42-annotated-precision/06-global.c
  tests/regression/42-annotated-precision/07-missing_annotation.c
  tests/regression/42-annotated-precision/08-22_01-simple_array.c
  tests/regression/42-annotated-precision/09-22_02-pointers_array.c
  tests/regression/42-annotated-precision/10-22_03-multidimensional_arrays.c
  tests/regression/42-annotated-precision/11-22_04-nesting_arrays.c
  tests/regression/42-annotated-precision/12-22_06-interprocedural.c
  tests/regression/42-annotated-precision/13-22_07-global_array.c
  tests/regression/42-annotated-precision/14-22_10-array_octagon.c
  tests/regression/42-annotated-precision/15-23_01-simple_array.c
  tests/regression/42-annotated-precision/16-23_02-pointers_array.c
  tests/regression/42-annotated-precision/17-23_03-multidimensional_arrays.c
  tests/regression/42-annotated-precision/18-23_04-nesting_arrays.c
  tests/regression/42-annotated-precision/19-23_06-interprocedural.c
  tests/regression/42-annotated-precision/20-23_10-array_octagon.c
  tests/regression/42-annotated-precision/21-23_14-replace_with_const.c
  tests/regression/42-annotated-precision/22-26_05-dynamically-sized-array-oob-access.c
  tests/regression/42-annotated-precision/23-26_07-arrays-within-structures.c
  tests/regression/42-annotated-precision/24-30_02-off.c
  tests/regression/42-annotated-precision/25-34_01-nested.c
  tests/regression/42-annotated-precision/26-34_02-hybrid.c
  tests/regression/42-annotated-precision/27-01_03-loops.c
  tests/regression/42-annotated-precision/28-02_36-calloc_struct.c
  tests/regression/42-annotated-precision/29-07_14-struct_in_struct.c
  tests/regression/42-annotated-precision/30-31_12-log-bitwise-enums.c
  tests/regression/42-annotated-precision/31-37_04-branching.c
  tests/regression/42-annotated-precision/32-01_03-loops_i.c
  tests/regression/42-annotated-precision/33-02_36-calloc_struct_i.c
  tests/regression/42-annotated-precision/34-07_14-struct_in_struct_i.c
  tests/regression/42-annotated-precision/35-31_12-log-bitwise-enums_i.c
  tests/regression/42-annotated-precision/36-37_04-branching_i.c
Labels: feature, student-job, precision

#419 Add set struct domains
  src/analyses/base.ml
  src/cdomains/structDomain.ml
  src/cdomains/structDomain.mli
  src/cdomains/valueDomain.ml
  src/util/defaults.ml
  tests/regression/43-struct-domain/01-single-thread.c
  tests/regression/43-struct-domain/02-multi-thread.c
  tests/regression/43-struct-domain/03-multi-thread-mutex.c
  tests/regression/43-struct-domain/04-small.c
  tests/regression/43-struct-domain/05-single-thread-widening.c
  tests/regression/43-struct-domain/06-many-choices.c
  tests/regression/43-struct-domain/07-check-sets.c
  tests/regression/43-struct-domain/08-nested-structs.c
  tests/regression/43-struct-domain/09-join-test.c
  tests/regression/43-struct-domain/10-many-choices-intervals.c
  tests/regression/43-struct-domain/11-normalize-top.c
  tests/regression/43-struct-domain/12-aget.c
  tests/regression/43-struct-domain/13-intervals-branching-meet.c
  tests/regression/43-struct-domain/14-single-thread-keyed.c
  tests/regression/43-struct-domain/15-multi-thread-keyed.c
  tests/regression/43-struct-domain/16-multi-thread-mutex-keyed.c
  tests/regression/43-struct-domain/17-small-keyed.c
  tests/regression/43-struct-domain/18-single-thread-widening-keyed.c
  tests/regression/43-struct-domain/19-many-choices-keyed.c
  tests/regression/43-struct-domain/20-check-sets-keyed.c
  tests/regression/43-struct-domain/21-nested-structs-keyed.c
  tests/regression/43-struct-domain/22-join-test-keyed.c
  tests/regression/43-struct-domain/23-many-choices-intervals-keyed.c
  tests/regression/43-struct-domain/24-normalize-top-keyed.c
  tests/regression/43-struct-domain/25-aget-keyed.c
  tests/regression/43-struct-domain/26-intervals-branching-meet-keyed.c
Labels: feature, student-job, precision

#465 Make Mutex-Meet Privatizations sound for Reentrant Locks
  src/analyses/libraryFunctions.ml
  src/analyses/mutexAnalysis.ml
  src/domains/events.ml
  tests/regression/13-privatized/70-mm-reentrant.c
Labels: bug, unsound

#466 Invalidate variables that are assigned return values of `pthread_create(...)` and `pthread_join(...)`
  src/analyses/base.ml
  tests/regression/01-cpa/54-tid-invalidate.c
Labels: bug, unsound

#467 Flag configured TIDs
  src/cdomains/arrayDomain.ml
  src/cdomains/threadIdDomain.ml
  src/util/defaults.ml
Labels: cleanup, usability, performance
