Repository goblint/analyzer, pull requests merged in 2021-05, with the labels that each got.

#207 Statistics in case of timeout, automatic colors, backtrace on SIGUSR2, `dbg.solver-stats-interval`
  regtest.sh
  scripts/dgoblint
  scripts/spec/check.sh
  src/framework/control.ml
  src/maingoblint.ml
  src/solvers/generic.ml
  src/solvers/sLRterm.ml
  src/solvers/td3.ml
  src/util/defaults.ml
  src/util/goblintutil.ml
  src/util/messages.ml
  src/util/timeout.ml
Labels: feature, usability

#214 Forbid `sideg` in `query`
  src/analyses/mCP.ml
  src/analyses/mutexAnalysis.ml
Labels: bug, performance

#212 Clean up `Printable.S`
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/contain.ml
  src/analyses/deadlock.ml
  src/analyses/extract_arinc.ml
  src/analyses/extract_osek.ml
  src/analyses/mCP.ml
  src/analyses/malloc_null.ml
  src/analyses/mayLocks.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/osek.ml
  src/analyses/symbLocks.ml
  src/analyses/threadId.ml
  src/analyses/uninit.ml
  src/cdomains/addressDomain.ml
  src/cdomains/apronDomain.ml
  src/cdomains/arincDomain.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/baseDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/concDomain.ml
  src/cdomains/containDomain.ml
  src/cdomains/deadlockDomain.ml
  src/cdomains/exp.ml
  src/cdomains/flagModeDomain.ml
  src/cdomains/intDomain.ml
  src/cdomains/listDomain.ml
  src/cdomains/lockDomain.ml
  src/cdomains/lval.ml
  src/cdomains/lvalMapDomain.ml
  src/cdomains/musteqDomain.ml
  src/cdomains/osektupel.ml
  src/cdomains/regionDomain.ml
  src/cdomains/shapeDomain.ml
  src/cdomains/structDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/access.ml
  src/domains/mapDomain.ml
  src/domains/octagonDomain.ml
  src/domains/octagonMapDomain.ml
  src/domains/partitionDomain.ml
  src/domains/printable.ml
  src/domains/queries.ml
  src/domains/setDomain.ml
  src/framework/analyses.ml
  src/framework/control.ml
  src/maindomaintest.ml
  src/util/hash.ml
  src/witness/witnessConstraints.ml
Labels: cleanup

#216 Add documentation on how to debug Goblint with VS Code
  docs/developer-guide/debugging.md
  make.sh
Labels: documentation, usability

#225 Cast values for threadreturns to void*
  src/analyses/base.ml
  src/util/defaults.ml
  tests/regression/04-mutex/57-thread_ret.c
Labels: bug, precision

#230 Fix for serialization issue in HashCached
  src/domains/printable.ml
  src/util/goblintutil.ml
  tests/regression/35-marshaling/01-disable_hashcons.c
Labels: bug

#223 Invalidate memory reachable from structs and unions passed to unknown functions.
  src/analyses/base.ml
  tests/regression/02-base/48-unknown_func_struct.c
  tests/regression/02-base/49-unknown_func_union.c
  tests/regression/02-base/50-unknown_func_array.c
Labels: bug

#221 Make queries type safe using GADTs
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/condVars.ml
  src/analyses/contain.ml
  src/analyses/deadlock.ml
  src/analyses/expRelation.ml
  src/analyses/extract_arinc.ml
  src/analyses/extract_osek.ml
  src/analyses/fileUse.ml
  src/analyses/flagModes.ml
  src/analyses/mCP.ml
  src/analyses/mallocWrapperAnalysis.ml
  src/analyses/malloc_null.ml
  src/analyses/mayLocks.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/octagon.ml
  src/analyses/osek.ml
  src/analyses/osektransactionality.ml
  src/analyses/poly.ml
  src/analyses/region.ml
  src/analyses/shapes.ml
  src/analyses/spec.ml
  src/analyses/symbLocks.ml
  src/analyses/threadAnalysis.ml
  src/analyses/threadEscape.ml
  src/analyses/threadFlag.ml
  src/analyses/threadId.ml
  src/analyses/threadReturn.ml
  src/analyses/uninit.ml
  src/analyses/varEq.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/containDomain.ml
  src/cdomains/lockDomain.ml
  src/cdomains/lvalMapDomain.ml
  src/cdomains/shapeDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/boolDomain.ml
  src/domains/queries.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/transform/expressionEvaluation.ml
  src/transform/transform.ml
  src/witness/witness.ml
  src/witness/witnessConstraints.ml
Labels: cleanup, type-safety

#227 Reduce equal & compare boilerplate using deriving eq & ord
  src/analyses/base.ml
  src/analyses/contain.ml
  src/cdomains/arincDomain.ml
  src/cdomains/baseDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/containDomain.ml
  src/cdomains/deadlockDomain.ml
  src/cdomains/exp.ml
  src/cdomains/intDomain.ml
  src/cdomains/lval.ml
  src/cdomains/lvalMapDomain.ml
  src/cdomains/osektupel.ml
  src/cdomains/valueDomain.ml
  src/domains/access.ml
  src/domains/printable.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/node.ml
  src/maindomaintest.ml
  src/solvers/generic.ml
  src/solvers/sLR.ml
  src/solvers/sLRphased.ml
  src/solvers/sLRterm.ml
  src/solvers/td3.ml
  src/solvers/topDown.ml
  src/solvers/topDown_deprecated.ml
  src/solvers/topDown_space_cache_term.ml
  src/solvers/topDown_term.ml
  src/witness/observerAnalysis.ml
  src/witness/witnessUtil.ml
Labels: cleanup

#232 show widening points
  src/solvers/sLR.ml
  src/solvers/sLRphased.ml
  src/solvers/sLRterm.ml
  src/solvers/td3.ml
  src/util/defaults.ml
Labels: feature, usability

#235 Documentation: Add basic description on how to run Goblint and on need for context widening
  docs/developer-guide/debugging.md
  docs/developer-guide/testing.md
  docs/user-guide/running.md
  mkdocs.yml
Labels: documentation

#229 Enums: Make comparison functions more precise
  src/cdomains/intDomain.ml
  tests/regression/31-ikind-aware-ints/16-enums-compare.c
Labels: precision

#196 Make octagon based on Apron useable
  .github/workflows/tests.yml
  dune-project
  goblint.opam
  goblint.opam.locked
  make.sh
  scripts/travis-ci.sh
  scripts/update_suite.rb
  src/analyses/apron/dune
  src/analyses/apron/octApron.apron.ml
  src/analyses/apron/octApron.no-apron.ml
  src/analyses/apron/poly.apron.ml
  src/analyses/apron/poly.no-apron.ml
  src/analyses/base.ml
  src/analyses/mCP.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/apron/apronDomain.no-apron.ml
  src/cdomains/apron/dune
  src/cdomains/apron/octApronDomain.apron.ml
  src/cdomains/apron/octApronDomain.no-apron.ml
  src/cdomains/intDomain.mli
  src/domains/queries.ml
  src/dune
  src/util/defaults.ml
  src/util/goblintutil.ml
  tests/regression/01-cpa/03-loops.c
  tests/regression/01-cpa/35-intervals.c
  tests/regression/17-arinc/05-term-simple.c
  tests/regression/21-casts/03-Exc-overflow.c
  tests/regression/31-ikind-aware-ints/07-defexc-large.c
  tests/regression/31-ikind-aware-ints/13-intervals-large.c
  tests/regression/31-ikind-aware-ints/14-enums-large.c
  tests/regression/36-octapron/01-octagon_simple.c
  tests/regression/36-octapron/02-octagon_interprocudral.c
  tests/regression/36-octapron/03-problem-types.c
  tests/regression/36-octapron/04-problem-rec.c
  tests/regression/36-octapron/05-problem-rec2.c
  tests/regression/36-octapron/06-problem-overflow.c
  tests/regression/36-octapron/07-problem-pointer.c
  tests/regression/36-octapron/08-problem-signed-unsigned-overflow.c
  tests/regression/36-octapron/09-branch.c
  tests/regression/36-octapron/10-float.c
Labels: feature, precision, usability
