Repository goblint/analyzer, pull requests merged in 2021-06, with the labels that each got.

#234 Extract `Printable` implementations for CIL types into separate `CilType` module
  src/analyses/base.ml
  src/analyses/expRelation.ml
  src/analyses/malloc_null.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/uninit.ml
  src/analyses/varEq.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/apron/octApronDomain.apron.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/baseDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/containDomain.ml
  src/cdomains/exp.ml
  src/cdomains/intDomain.ml
  src/cdomains/lockDomain.ml
  src/cdomains/lval.ml
  src/cdomains/regionDomain.ml
  src/cdomains/shapeDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/access.ml
  src/domains/invariantCil.ml
  src/domains/mapDomain.ml
  src/domains/printable.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/framework/myCFG.ml
  src/framework/node.ml
  src/incremental/compareAST.ml
  src/solvers/sLR.ml
  src/util/cilType.ml
  src/util/goblintutil.ml
  src/util/lazyEval.ml
  src/util/xmlUtil.ml
  src/witness/myARG.ml
  src/witness/violationZ3.ml
  src/witness/witnessConstraints.ml
Labels: cleanup

#249 HoarePO.merge_join: Merge smaller map into larger one to improve performance
  src/domains/hoareDomain.ml
Labels: performance

#253 Remove floats from octApron
  src/analyses/apron/octApron.apron.ml
  src/cdomains/apron/octApronDomain.apron.ml
  src/util/defaults.ml
Labels: cleanup

#261 Improve to_yojson output
  src/analyses/mCP.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/baseDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/intDomain.ml
  src/cdomains/lval.ml
  src/cdomains/valueDomain.ml
  src/domains/mapDomain.ml
  src/domains/printable.ml
  src/domains/setDomain.ml
  src/framework/analyses.ml
Labels: cleanup, usability
