Repository goblint/analyzer, pull requests merged in 2021-12, with the labels that each got.

#471 Flag Helper for Binary Flag Configured `Printable`s, `Groupable`s, and `Lattice.PO`s
  src/cdomains/arrayDomain.ml
  src/cdomains/structDomain.ml
  src/cdomains/threadIdDomain.ml
  src/domains/flagHelper.ml
Labels: cleanup

#474 Remove containment, deadlocksByRaces and shapes analyses
  src/analyses/base.ml
  src/analyses/contain.ml
  src/analyses/deadlocksByRaces.ml
  src/analyses/shapes.ml
  src/analyses/threadAnalysis.ml
  src/cdomains/basetype.ml
  src/cdomains/containDomain.ml
  src/cdomains/lval.ml
  src/cdomains/shapeDomain.ml
  src/domains/setDomain.ml
  src/maingoblint.ml
  src/util/goblintutil.ml
  tests/regression/12-containment/01-analyse.c
  tests/regression/12-containment/CXX.json
  tests/regression/12-containment/README.txt
  tests/regression/12-containment/SAFE.json
  tests/regression/13-privatized/05-dll_inlined_nr.c
  tests/regression/13-privatized/06-dll_inlined_rc.c
  tests/regression/13-privatized/07-dll_example.c
  tests/regression/13-privatized/08-dll_splice_nr.c
  tests/regression/13-privatized/09-dll_splice_rc.c
  tests/regression/13-privatized/10-dll_movetail.c
  tests/regression/13-privatized/11-opencode_rc.c
  tests/regression/13-privatized/12-opencode_nr.c
  tests/regression/13-privatized/13-opencode_sound.c
  tests/regression/13-privatized/14-opencode_dyn.c
  tests/regression/13-privatized/15-opencode_backptr.c
  tests/regression/13-privatized/16-opencode_offs.c
Labels: cleanup

#475 Find non-Clang, non-Apple `cpp` at runtime
  src/dune
  src/maingoblint.ml
  src/util/defaults.ml
  src/util/preprocessor.ml
Labels: cleanup, setup

#464 Adapt to CIL without MSVC support
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/framework/cfgTools.ml
  src/incremental/compareAST.ml
  src/util/cilfacade.ml
Labels: cleanup

#479 Adapt to new CIL with CInt instead of CInt64
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/deadlock.ml
  src/analyses/expRelation.ml
  src/analyses/fileUse.ml
  src/analyses/flag.ml
  src/analyses/malloc_null.ml
  src/analyses/mayLocks.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/octagon.ml
  src/analyses/osek.ml
  src/analyses/spec.ml
  src/analyses/symbLocks.ml
  src/analyses/tutorials/constants.ml
  src/analyses/tutorials/signs.ml
  src/analyses/uninit.ml
  src/analyses/varEq.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/exp.ml
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/incremental/compareAST.ml
  src/util/cilfacade.ml
  src/util/wideningThresholds.ml
  tests/regression/27-inv_invariants/01-ints.c
Labels: cleanup

#483 Output either release version or commit hash
  scripts/hooks/pre-commit
  src/maingoblint.ml
  src/version.ml
Labels: setup

#484 Fix mismatch between thread ID sets and reachable threads
  src/analyses/threadId.ml
  src/cdomains/threadIdDomain.ml
Labels: bug

#481 Add option `incremental.force-reanalyze.funs`
  src/incremental/compareCIL.ml
  src/incremental/serialize.ml
  src/util/defaults.ml
Labels: feature

#477 Do not evaluate global integer variables when writing them.
  src/analyses/base.ml
  tests/regression/02-base/65-no-eval-on-write.c
  tests/regression/02-base/66-no-eval-on-write-multi.c
Labels: precision, performance

#487 Fix protected/mutex_inits unsoundness in branched thread creation with protection/mutex-oplus/mutex-meet
  src/analyses/apron/apronPriv.apron.ml
  src/analyses/basePriv.ml
  tests/regression/13-privatized/71-branched-thread-creation-priv.c
  tests/regression/13-privatized/72-pthread_cond_wait_mutexoplus.c
  tests/regression/36-apron/96-branched-thread-creation-apron-priv.c
Labels: bug, unsound

#486 Fix meet of arrays with different partitioning expressions
  src/cdomains/arrayDomain.ml
  tests/regression/22-partitioned_arrays/16-refine-meet.c
Labels: bug, sv-comp

#493 Annotations via options
  src/analyses/base.ml
  src/util/contextUtil.ml
  src/util/defaults.ml
  tests/regression/02-base/67-no-int-context-option.c
  tests/regression/02-base/68-int-context-option.c
  tests/regression/23-partitioned_arrays_last/01-simple_array.c
  tests/regression/42-annotated-precision/01-def_exc.c
  tests/regression/42-annotated-precision/02-interval.c
  tests/regression/42-annotated-precision/03-congruence.c
  tests/regression/42-annotated-precision/04-struct.c
  tests/regression/42-annotated-precision/05-array.c
  tests/regression/42-annotated-precision/06-global.c
  tests/regression/42-annotated-precision/07-missing_annotation.c
  tests/regression/42-annotated-precision/08-22_01-simple_array.c
  tests/regression/42-annotated-precision/09-22_02-pointers_array.c
  tests/regression/42-annotated-precision/10-22_03-multidimensional_arrays.c
  tests/regression/42-annotated-precision/11-22_04-nesting_arrays.c
  tests/regression/42-annotated-precision/12-22_06-interprocedural.c
  tests/regression/42-annotated-precision/13-22_07-global_array.c
  tests/regression/42-annotated-precision/14-22_10-array_octagon.c
  tests/regression/42-annotated-precision/15-23_01-simple_array.c
  tests/regression/42-annotated-precision/16-23_02-pointers_array.c
  tests/regression/42-annotated-precision/17-23_03-multidimensional_arrays.c
  tests/regression/42-annotated-precision/18-23_04-nesting_arrays.c
  tests/regression/42-annotated-precision/19-23_06-interprocedural.c
  tests/regression/42-annotated-precision/20-23_10-array_octagon.c
  tests/regression/42-annotated-precision/21-23_14-replace_with_const.c
  tests/regression/42-annotated-precision/22-26_05-dynamically-sized-array-oob-access.c
  tests/regression/42-annotated-precision/23-26_07-arrays-within-structures.c
  tests/regression/42-annotated-precision/24-30_02-off.c
  tests/regression/42-annotated-precision/25-34_01-nested.c
  tests/regression/42-annotated-precision/26-34_02-hybrid.c
  tests/regression/42-annotated-precision/27-01_03-loops.c
  tests/regression/42-annotated-precision/28-02_36-calloc_struct.c
  tests/regression/42-annotated-precision/29-07_14-struct_in_struct.c
  tests/regression/42-annotated-precision/30-31_12-log-bitwise-enums.c
  tests/regression/42-annotated-precision/31-37_04-branching.c
  tests/regression/42-annotated-precision/32-01_03-loops_i.c
  tests/regression/42-annotated-precision/33-02_36-calloc_struct_i.c
  tests/regression/42-annotated-precision/34-07_14-struct_in_struct_i.c
  tests/regression/42-annotated-precision/35-31_12-log-bitwise-enums_i.c
  tests/regression/42-annotated-precision/36-37_04-branching_i.c
  tests/regression/42-annotated-precision/37-def_exc-via-option.c
Labels: feature

#489 Incremental/automated tests
  .github/workflows/locked.yml
  .github/workflows/unlocked.yml
  scripts/update_suite.rb
  tests/incremental/00-basic/00-local.c
  tests/incremental/00-basic/00-local.json
  tests/incremental/00-basic/00-local.patch
  tests/incremental/00-basic/01-global.c
  tests/incremental/00-basic/01-global.json
  tests/incremental/00-basic/01-global.patch
  tests/incremental/00-basic/02-changed_start_state1.c
  tests/incremental/00-basic/02-changed_start_state1.json
  tests/incremental/00-basic/02-changed_start_state1.patch
  tests/incremental/00-basic/03-changed_start_state2.c
  tests/incremental/00-basic/03-changed_start_state2.json
  tests/incremental/00-basic/03-changed_start_state2.patch
  tests/incremental/00-basic/04-rename_ids.c
  tests/incremental/00-basic/04-rename_ids.json
  tests/incremental/00-basic/04-rename_ids.patch
  tests/incremental/00-basic/05-sideeffects.c
  tests/incremental/00-basic/05-sideeffects.json
  tests/incremental/00-basic/05-sideeffects.patch
  tests/incremental/00-basic/06-threadid.c
  tests/incremental/00-basic/06-threadid.json
  tests/incremental/00-basic/06-threadid.patch
  tests/incremental/02-changed_start_state.c
  tests/incremental/02-changed_start_state.patch
  tests/incremental/03-changed_start_state.c
  tests/incremental/03-changed_start_state.patch
Labels: feature, testing, usability

#494 Bump goblint-cil to add C11 generic support
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  includes/stdlib.c
Labels: feature, c11

#495 Fix known addresses not escaping when address set contains unknown
  src/analyses/base.ml
  src/analyses/malloc_null.ml
  src/analyses/threadEscape.ml
  src/analyses/uninit.ml
  tests/regression/02-base/70-escape-unknown.c
Labels: bug, unsound

#498 Store and load analysis specific data in incremental run
  src/framework/control.ml
  src/incremental/serialize.ml
  src/maingoblint.ml
Labels: bug

#502 DefExc.widen Excluded range to static size instead of join
  src/cdomains/intDomain.ml
Labels: performance

#500 Remove custom octagon analysis, make Apron Analysis answer MustBeEqual, MayBeEqual, and MayBeLess queries
  .github/workflows/locked.yml
  .github/workflows/unlocked.yml
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/octagon.ml
  src/domains/octagonDomain.ml
  src/domains/octagonMapDomain.ml
  tests/regression/23-partitioned_arrays_last/13-advantage_for_last.c
  tests/regression/24-octagon/01-octagon_simple.c
  tests/regression/24-octagon/02-octagon_interprocedural.c
  tests/regression/24-octagon/03-previously_problematic_a.c
  tests/regression/24-octagon/04-previously_problematic_b.c
  tests/regression/24-octagon/05-previously_problematic_c.c
  tests/regression/24-octagon/06-previously_problematic_d.c
  tests/regression/24-octagon/07-previously_problematic_e.c
  tests/regression/24-octagon/08-previously_problematic_f.c
  tests/regression/24-octagon/09-previously_problematic_g.c
  tests/regression/24-octagon/10-previously_problematic_h.c
  tests/regression/24-octagon/11-previously_problematic_i.c
  tests/regression/24-octagon/12-previously_problematic_j.c
  tests/regression/24-octagon/13-array_octagon.c
  tests/regression/24-octagon/14-array_octagon_keep_last.c
  tests/regression/24-octagon/15-array_octagon_prec.c
  tests/regression/24-octagon/16-array_octagon_keep_last_prec.c
Labels: cleanup

#506 Remove `exp.lower-constants`
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/analyses/base.ml
  src/maingoblint.ml
  src/util/cilfacade.ml
  src/util/defaults.ml
  tests/regression/39-signed-overflows/05-lower-constants.c
Labels: cleanup

#499 Replace `Defaults` module with JSON schema
  docs/user-guide/configuring.md
  dune-project
  goblint.opam
  goblint.opam.locked
  mkdocs.yml
  src/dune
  src/maindomaintest.ml
  src/maingoblint.ml
  src/util/defaults.ml
  src/util/gobConfig.ml
  src/util/jsonSchema.ml
  src/util/options.ml
  src/util/options.schema.json
  src/util/precCompare.ml
  unittest/mainTest.ml
Labels: cleanup, feature, usability, documentation

#510 Avoid back-and-forth cast between bigint and int64 for array domains
  src/cdomains/arrayDomain.ml
  src/cdomains/arrayDomain.mli
  src/cdomains/baseDomain.ml
  src/cdomains/valueDomain.ml
Labels: cleanup
