Repository goblint/analyzer, pull requests merged in 2022-02, with the labels that each got.

#570 Optimize short-circuitable folds in `MCP`
  src/analyses/mCPAccess.ml
  src/analyses/mCPRegistry.ml
  src/util/gobList.ml
Labels: performance

#584 Preprocessor directives to disable Goblint includes
  includes/pthread.c
  includes/stdlib.c
  tests/regression/41-stdlib/03-noqsort.c
Labels: feature, bug

#579 Fix int domain test failures
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/domains/intDomainProperties.ml
  src/util/intOps.ml
  unittest/cdomains/intDomainTest.ml
  unittest/maindomaintest.ml
Labels: bug, unsound

#586 Optimize `Queries.ID`
  bench/basic/benchTuple4.ml
  bench/basic/dune
  src/analyses/base.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/intDomain.ml
  src/domains/hoareDomain.ml
  src/domains/queries.ml
  src/transform/expressionEvaluation.ml
  src/witness/witnessConstraints.ml
  unittest/cdomains/intDomainTest.ml
Labels: cleanup, performance

#593 Fix most catch-alls
  src/analyses/base.ml
  src/analyses/extract_arinc.ml
  src/analyses/extract_osek.ml
  src/analyses/flag.ml
  src/analyses/osek.ml
  src/cdomains/intDomain.ml
  src/cdomains/lval.ml
  src/cdomains/valueDomain.ml
  src/domains/access.ml
  src/prelude.ml
  src/util/gobConfig.ml
  src/util/jsonSchema.ml
Labels: cleanup, type-safety

#590 Refactor MCP transfer functions and add query cache
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/extract_arinc.ml
  src/analyses/extract_osek.ml
  src/analyses/mCP.ml
  src/domains/events.ml
  src/domains/queries.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/witness/witness.ml
Labels: cleanup, performance

#587 Compute dependencies of file via CIL instead of from `.d` files generated during pre-processing
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/framework/analyses.ml
  src/maingoblint.ml
  src/util/compilationDatabase.ml
  src/util/dune
  src/util/makefileLexer.mll
  src/util/makefileParser.mly
  src/util/preprocessor.ml
Labels: cleanup

#594 Fix unknown pointer case in base get
  src/analyses/base.ml
Labels: bug

#573 Add option for manual restarting of globals
  src/framework/analyses.ml
  src/framework/varQuery.ml
  src/framework/varQuery.mli
  src/incremental/compareCIL.ml
  src/maingoblint.ml
  src/solvers/td3.ml
  src/util/options.schema.json
  src/util/server.ml
  tests/incremental/04-manual-restart/01-restart_manual_simple.c
  tests/incremental/04-manual-restart/01-restart_manual_simple.json
  tests/incremental/04-manual-restart/01-restart_manual_simple.patch
  tests/incremental/04-manual-restart/02-read_write_global.c
  tests/incremental/04-manual-restart/02-read_write_global.json
  tests/incremental/04-manual-restart/02-read_write_global.patch
  tests/incremental/04-manual-restart/03-partial_contexts.c
  tests/incremental/04-manual-restart/03-partial_contexts.json
  tests/incremental/04-manual-restart/03-partial_contexts.patch
Labels: performance

#595 Extract MHP analysis, simplify printing in race output
  src/analyses/mHPAnalysis.ml
  src/analyses/threadId.ml
  src/analyses/tutorials/unitAnalysis.ml
  src/cdomains/mHP.ml
  src/cdomains/threadIdDomain.ml
  src/util/options.schema.json
  tests/regression/10-synch/13-two_threads_nr.c
  tests/regression/10-synch/15-join_other_nr.c
  tests/regression/53-races-mhp/01-not-created.c
  tests/regression/53-races-mhp/02-join.c
  tests/regression/53-races-mhp/03-not-created_rc.c
Labels: usability, precision, performance

#585 Adaptations to preprocessing
  src/incremental/makefileUtil.ml
  src/util/compilationDatabase.ml
Labels: bug

#602 Fix imprecise AD.meet with NULL
  src/cdomains/addressDomain.ml
  tests/regression/27-inv_invariants/15-unknown-null-ptr.c
  tests/regression/27-inv_invariants/16-sedgewick.c
Labels: bug, precision

#601 Simplify function annotation options
  src/util/contextUtil.ml
  src/util/gobConfig.ml
  src/util/jsonSchema.ml
  src/util/options.ml
  src/util/options.schema.json
  tests/incremental/01-force-reanalyze/00-int.patch
  tests/regression/02-base/67-no-int-context-option.c
  tests/regression/02-base/68-int-context-option.c
  tests/regression/42-annotated-precision/37-def_exc-via-option.c
Labels: cleanup

#604 Bump CIL to support Universal Character Names, `char16_t`, and `char32_t` (part of C99/C11)
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/analyses/base.ml
  src/analyses/fileUse.ml
  src/analyses/spec.ml
  src/analyses/varEq.ml
  src/cdomains/exp.ml
  src/util/cilfacade.ml
Labels: c99, dependencies, c11

#591 Reparse files before each analysis run in server mode
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/apron/apronDomain.no-apron.ml
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/framework/control.ml
  src/goblint.ml
  src/incremental/compareCIL.ml
  src/maingoblint.ml
  src/util/cilfacade.ml
  src/util/goblintutil.ml
  src/util/options.schema.json
  src/util/resettableLazy.ml
  src/util/resettableLazy.mli
  src/util/server.ml
  src/util/wideningThresholds.ml
  src/util/wideningThresholds.mli
Labels: feature

#599 Allow analysis abort in server mode
  src/util/server.ml
Labels: feature, usability

#600 Incremental analysis: Eagerly analyze functions in `force-reanalyze`, even when `reluctant` is on
  src/incremental/compareCIL.ml
  src/solvers/td3.ml
  tests/incremental/01-force-reanalyze/01-int-reluctant.c
  tests/incremental/01-force-reanalyze/01-int-reluctant.json
  tests/incremental/01-force-reanalyze/01-int-reluctant.patch
  tests/incremental/03-precision-annotation/02-reluctant-int-annotation.c
  tests/incremental/03-precision-annotation/02-reluctant-int-annotation.json
  tests/incremental/03-precision-annotation/02-reluctant-int-annotation.patch
  tests/incremental/03-precision-annotation/03-reluctant-int-annotation-dyn.c
  tests/incremental/03-precision-annotation/03-reluctant-int-annotation-dyn.json
  tests/incremental/03-precision-annotation/03-reluctant-int-annotation-dyn.patch
Labels: bug

#608 Add more invalidate actions for library functions
  src/analyses/libraryFunctions.ml
Labels: cleanup, unsound

#612 Call `sync` after `assign` transfer function in global initializers to make `None` privatization work properly
  src/framework/control.ml
  tests/regression/00-sanity/30-both_branches.c
Labels: bug, unsound

#610 Refactor preprocessing
  .github/workflows/unlocked.yml
  .gitignore
  scripts/update_suite.rb
  src/framework/control.ml
  src/goblint.ml
  src/incremental/serialize.ml
  src/maingoblint.ml
  src/solvers/generic.ml
  src/solvers/postSolver.ml
  src/util/compilationDatabase.ml
  src/util/gobSys.ml
  src/util/goblintDir.ml
  src/util/goblintutil.ml
  src/util/oilUtil.ml
  src/util/options.schema.json
  src/util/server.ml
  tests/regression/41-stdlib/03-noqsort.c
Labels: cleanup
