Repository goblint/analyzer, pull requests merged in 2022-10, with the labels that each got.

#833 Privatized location invariants in YAML witnesses
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/apron/apronPriv.apron.ml
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/basePriv.mli
  src/analyses/commonPriv.ml
  src/analyses/mutexAnalysis.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/domains/queries.ml
Labels: feature, unsound, sv-comp

#819 Limit YAML witness invariants to to-be-read and just-written variables
  src/analyses/accessAnalysis.ml
  src/analyses/base.ml
  src/analyses/extractPthread.ml
  src/analyses/mCP.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/raceAnalysis.ml
  src/analyses/tutorials/unitAnalysis.ml
  src/cdomains/cilLval.ml
  src/cdomains/structDomain.ml
  src/cdomains/structDomain.mli
  src/cdomains/unionDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/access.ml
  src/domains/accessDomain.ml
  src/domains/events.ml
  src/domains/invariant.ml
  src/domains/queries.ml
  src/dune
  src/transform/evalAssert.ml
  src/util/options.schema.json
  src/witness/yamlWitness.ml
  tests/regression/06-symbeq/17-type_nr.c
Labels: feature, usability, sv-comp, performance

#844 Improve timing, add Trace Event Format output
  .semgrep/stats.yml
  .semgrep/timing.yml
  conf/incremental.json
  conf/minimal_incremental.json
  conf/zstd-race.json
  docs/developer-guide/profiling.md
  dune-project
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  scripts/test-incremental-multiple.sh
  scripts/test-incremental.sh
  scripts/update_suite.rb
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/basePriv.ml
  src/analyses/deadlock.ml
  src/analyses/raceAnalysis.ml
  src/domains/mapDomain.ml
  src/dune
  src/framework/analyses.ml
  src/framework/cfgTools.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/goblint.ml
  src/incremental/compareCFG.ml
  src/incremental/compareCIL.ml
  src/maingoblint.ml
  src/solvers/generic.ml
  src/solvers/postSolver.ml
  src/solvers/td3.ml
  src/solvers/topDown_space_cache_term.ml
  src/util/cilfacade.ml
  src/util/options.schema.json
  src/util/processPool.ml
  src/util/timing.ml
  src/util/timing/dune
  src/util/timing/goblint_timing.ml
  src/util/timing/goblint_timing.mli
  src/util/timing/goblint_timing_intf.ml
  src/witness/witness.ml
  src/witness/witnessUtil.ml
  tests/regression/46-apron2/18-evalint-torture.c
Labels: feature, bug, performance, debugging

#772 Autotuning of Configuration
  docs/user-guide/annotating.md
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/base.ml
  src/autoTune.ml
  src/autoTune0.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/arrayDomain.mli
  src/cdomains/intDomain.ml
  src/cdomains/valueDomain.ml
  src/goblint.ml
  src/maingoblint.ml
  src/util/cilfacade.ml
  src/util/loopUnrolling.ml
  src/util/options.schema.json
  src/util/server.ml
  src/util/wideningThresholds.ml
  src/util/wideningThresholds.mli
  src/witness/svcomp.ml
  src/witness/svcompSpec.ml
  tests/regression/54-unroll_arrays/03-large_index_type.c
  tests/regression/54-unroll_arrays/04-access_no_bounds.c
  tests/regression/60-array_annotations/01-var_array_annotation.c
  tests/regression/60-array_annotations/02-function_array_annotation.c
  tests/regression/60-array_annotations/03-change_domain_array_annotation.c
  tests/regression/60-array_annotations/04-structure_array_annotation.c
  tests/regression/60-array_annotations/05-type_array_annotation.c
  tests/regression/60-array_annotations/07-array_domain_project.c
Labels: feature, student-job, sv-comp, precision, performance

#853 Fix Incorrect Shebangs
  scripts/trace_off.sh
  scripts/trace_on.sh
Labels: bug, setup

#851 Generate invariants about local variables again in EvalAssert transformation
  src/framework/control.ml
  src/maingoblint.ml
  src/transform/evalAssert.ml
  src/transform/expressionEvaluation.ml
  src/transform/transform.ml
Labels: cleanup, bug

#858 Use correct `ikind` for result in `inv_exp`
  src/analyses/base.ml
  tests/regression/02-base/98-refine-unsigned.c
Labels: bug, precision

#861 Fix base Invariant query lval and offset handling
  src/analyses/base.ml
  src/cdomains/structDomain.ml
  src/cdomains/structDomain.mli
  src/cdomains/unionDomain.ml
  src/cdomains/valueDomain.ml
Labels: bug

#862 Avoid cyclic destabilize in destabilize_with_sides leading to less fuel than expected
  src/solvers/td3.ml
  tests/incremental/11-restart/14-mutex-simple-wrap2.c
  tests/incremental/11-restart/14-mutex-simple-wrap2.patch
  tests/incremental/11-restart/15-mutex-simple-wrap1.c
  tests/incremental/11-restart/15-mutex-simple-wrap1.json
  tests/incremental/11-restart/15-mutex-simple-wrap1.patch
  tests/incremental/11-restart/16-mutex-simple-wrap1-global.c
  tests/incremental/11-restart/16-mutex-simple-wrap1-global.patch
Labels: bug

#846 Attempt to optimize base eval mustbeequal layer
  src/analyses/base.ml
Labels: cleanup, performance

#863 Introduce new possible widening strategy `sides-local` for globals
  src/solvers/td3.ml
  src/util/options.schema.json
  tests/regression/01-cpa/71-widen-sides.c
Labels: feature, precision

#865 Add definitions for library functions used in `cp` program
  src/analyses/libraryFunctions.ml
Labels: feature, precision

#855 Fix EvalAssert transformation to work on coreutil programs
  src/cdomains/valueDomain.ml
  src/framework/control.ml
  src/transform/evalAssert.ml
  src/util/cilfacade.ml
  src/util/gobList.ml
  src/util/options.schema.json
  tests/regression/61-evalAssert/01-union_evalAssert.c
Labels: bug, sv-comp, benchmarking

#871 var_eq unsoundness with dereferenced floats
  src/analyses/expRelation.ml
  src/analyses/varEq.ml
  src/util/cilfacade.ml
  tests/regression/01-cpa/45-float.c
Labels: cleanup, bug, unsound

#874 Check `space` option for TD3 and removal of wpoints & `sides-local` widening strategy are not enabled at the same time
  src/maingoblint.ml
  src/solvers/td3.ml
  src/util/options.schema.json
Labels: cleanup, bug, unsound

#872 Fix stack overflow in CompareAST
  src/incremental/compareAST.ml
  src/incremental/compareCFG.ml
  src/incremental/compareCIL.ml
  tests/incremental/00-basic/12-rec-type.c
  tests/incremental/00-basic/12-rec-type.json
  tests/incremental/00-basic/12-rec-type.patch
Labels: bug

#869 Equip float domain to handle definite NaN, +Inf, -Inf, and some missing float stubs
  src/analyses/base.ml
  src/analyses/libraryDesc.ml
  src/analyses/libraryFunctions.ml
  src/cdomains/floatDomain.ml
  src/cdomains/floatDomain.mli
  src/cdomains/floatOps/floatOps.ml
  src/cdomains/floatOps/floatOps.mli
  tests/regression/57-floats/06-library_functions.c
  tests/regression/57-floats/14-builtin-comparisons.c
  tests/regression/57-floats/15-more-library.c
  tests/regression/57-floats/16-more-stuff.c
  tests/regression/57-floats/17-other.c
  tests/regression/57-floats/18-zerodiv.c
  unittest/cdomains/floatDomainTest.ml
Labels: feature, precision
