Repository goblint/analyzer, pull requests merged in 2022-08, with the labels that each got.

#808 Limit address sets to include at most one string pointer
  conf/examples/very-precise.json
  src/cdomains/lval.ml
  src/util/options.schema.json
  tests/regression/02-base/88-string-ptrs-limited.c
  tests/regression/02-base/89-string-ptrs-not-limited.c
Labels: unsound, performance

#812 Remove ARINC analyses
  scripts/old/airbus/bench.sh
  scripts/old/airbus/bisect.sh
  scripts/spec/check.sh
  spin/airbus.pml
  spin/arinc.base.pml
  spin/check.sh
  spin/deadlock.pml
  spin/deadlock_provided.pml
  spin/graph.sh
  spin/inlineBench.pml
  spin/starvation_provided.pml
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/extract_arinc.ml
  src/analyses/libraryFunctions.ml
  src/analyses/mCP.ml
  src/analyses/mutexEventsAnalysis.ml
  src/cdomains/arincDomain.ml
  src/dune
  src/extract/pml.ml
  src/extract/pml_arinc.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/main.camldoc
  src/mainarinc.ml
  src/util/arincUtil.ml
  src/util/goblintutil.ml
  src/util/options.schema.json
  src/witness/witness.ml
  src/witness/yamlWitness.ml
  tests/regression/01-cpa/24-library_functions.c
  tests/regression/17-arinc/01-sema.c
  tests/regression/17-arinc/02-unique_proc.c
  tests/regression/17-arinc/03-preemt_lock.c
  tests/regression/17-arinc/04-sema-strcpy.c
  tests/regression/17-arinc/05-term-simple.c
  tests/regression/17-arinc/06-term.c
  tests/regression/17-arinc/07-cond-var.c
  tests/regression/17-arinc/08-multi-cond.c
  tests/regression/17-arinc/09-cond-var-scope.c
  tests/regression/17-arinc/10-term-phases.c
  tests/regression/17-arinc/README.md
  tests/regression/17-arinc/arinc_sema.spec
Labels: cleanup

#801 Add static module for top-level Control Spec context
  src/domains/printable.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/witness/witness.ml
  src/witness/yamlWitness.ml
Labels: cleanup

#786 Precondition Invariant: Disjunct over matching state invariants
  src/util/gobList.ml
  src/witness/yamlWitness.ml
  tests/regression/56-witness/05-prec-problem.c
Labels: unsound

#752 Add experimental generation and validation of YAML witness invariants with preconditions
  .gitignore
  src/util/gobList.ml
  src/util/gobYaml.ml
  src/witness/witnessUtil.ml
  src/witness/yamlWitness.ml
  src/witness/yamlWitnessType.ml
  tests/regression/56-witness/05-prec-problem.c
Labels: cleanup, feature, type-safety, sv-comp, precision

#815 Check type of source and destination in handling of memcpy in Base
  src/analyses/base.ml
  tests/regression/02-base/90-memcpy.c
Labels: bug

#740 Add server command `pre_files`
  src/goblint.ml
  src/maingoblint.ml
  src/util/server.ml
Labels: feature, usability, preprocessing

#220 Liveness analysis of multi-threaded C with POSIX threads
  .github/workflows/locked.yml
  .gitignore
  spin/pthread.base.pml
  src/analyses/extractPthread.ml
  src/cdomains/pthreadDomain.ml
  src/util/options.schema.json
  tests/extraction/00-sanity.c
  tests/extraction/01-base.c
  tests/extraction/02-starve.c
  tests/extraction/test.sh
Labels: feature, student-job

#820 Remove phases
  src/maingoblint.ml
  src/util/gobConfig.ml
  src/util/jsonSchema.ml
  src/util/options.ml
  src/util/options.schema.json
  tests/sv-comp/observer/path_nofun_true-unreach-call.c
Labels: cleanup

#821 Add support for `pthread_spin_lock`
  src/analyses/libraryFunctions.ml
  src/cdomains/valueDomain.ml
  src/domains/access.ml
  tests/regression/04-mutex/73-simple_nr_spinlock.c
Labels: precision

#817 Add server command to merge config by file name
  src/goblint.ml
  src/maingoblint.ml
  src/util/cilfacade.ml
  src/util/server.ml
Labels: feature, usability

#829 Add Apron octagon narrow
  src/cdomains/apron/apronDomain.apron.ml
  tests/regression/46-apron2/22-oct-narrow.c
Labels: feature, precision
