Repository goblint/analyzer, pull requests merged in 2022-06, with the labels that each got.

#749 Remove `inthack` and fix i-lock star display
  src/analyses/symbLocks.ml
  src/cdomains/intDomain.ml
  src/cdomains/lval.ml
  src/cdomains/symbLocksDomain.ml
  src/util/goblintutil.ml
Labels: cleanup, usability, type-safety

#748 Store all incremental data into single file
  src/framework/control.ml
  src/incremental/maxIdUtil.ml
  src/incremental/serialize.ml
  src/maingoblint.ml
  src/util/server.ml
Labels: cleanup

#753 Add general expression threshold widening to Apron
  src/cdomains/apron/apronDomain.apron.ml
  src/util/wideningThresholds.ml
  src/util/wideningThresholds.mli
  tests/regression/36-apron/57-vectorsize-lazy-downsize.c
Labels: feature, precision

#756 Fix unsound Apron dummy privatization
  src/analyses/apron/apronPriv.apron.ml
  src/util/options.schema.json
  tests/regression/36-apron/01-octagon_simple.c
  tests/regression/36-apron/02-octagon_interprocudral.c
  tests/regression/36-apron/03-problem-signextension.c
  tests/regression/36-apron/04-problem-rec.c
  tests/regression/36-apron/05-problem-rec2.c
  tests/regression/36-apron/06-problem-overflow.c
  tests/regression/36-apron/07-problem-pointer.c
  tests/regression/36-apron/08-problem-implicitunsignedconversion.c
  tests/regression/36-apron/64-dummy-sound.c
  tests/regression/36-apron/94-simple-apron-interval.c
  tests/regression/36-apron/95-simple-polyhedra.c
Labels: cleanup, bug, unsound

#720 OCaml DSL for specifying `LibraryFunctions`
  docs/developer-guide/extending-library.md
  mkdocs.yml
  src/analyses/accessAnalysis.ml
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/base.ml
  src/analyses/libraryDesc.ml
  src/analyses/libraryDsl.ml
  src/analyses/libraryDsl.mli
  src/analyses/libraryFunctions.ml
  src/analyses/libraryFunctions.mli
  src/analyses/mallocFresh.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/mutexEventsAnalysis.ml
  src/analyses/region.ml
  src/analyses/symbLocks.ml
  src/analyses/threadAnalysis.ml
  src/analyses/threadJoins.ml
  src/analyses/varEq.ml
  src/domains/access.ml
  src/domains/accessKind.ml
  src/transform/evalAssert.ml
  src/witness/witnessUtil.ml
  tests/regression/02-base/79-unknown-spawn.c
  tests/regression/02-base/80-unknown-no-spawn.c
  tests/regression/02-base/81-invalidate_indirect_base.c
  tests/regression/04-mutex/58-strange-spawn.c
  tests/regression/04-mutex/72-memset_arg_rc.c
  unittest/analyses/libraryDslTest.ml
  unittest/mainTest.ml
Labels: cleanup, feature, type-safety, precision

#757 Add `LOr` eval to base for address and enum set validation
  scripts/update_suite.rb
  src/analyses/base.ml
  src/cdomains/intDomain.mli
  tests/regression/01-cpa/33-asserts.c
  tests/regression/56-witness/01-base-lor-enums.c
  tests/regression/56-witness/01-base-lor-enums.yml
  tests/regression/56-witness/02-base-lor-addr.c
  tests/regression/56-witness/02-base-lor-addr.yml
Labels: feature, precision

#759 Replace `Printable.invariant` entirely with `Invariant` query
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/base.ml
  src/analyses/mCPRegistry.ml
  src/analyses/varEq.ml
  src/cdomains/addressDomain.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/baseDomain.ml
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/cdomains/structDomain.ml
  src/cdomains/structDomain.mli
  src/cdomains/unionDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/flagHelper.ml
  src/domains/invariant.ml
  src/domains/mapDomain.ml
  src/domains/printable.ml
  src/domains/queries.ml
  src/domains/setDomain.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/transform/evalAssert.ml
  src/witness/witness.ml
  src/witness/witnessConstraints.ml
  src/witness/yamlWitness.ml
Labels: cleanup, bug, unsound

#768 IntDomain logcal operation short-circuiting
  src/cdomains/intDomain.ml
  tests/regression/56-witness/03-int-log-short.c
  tests/regression/56-witness/03-int-log-short.yml
Labels: precision, benchmarking
