Repository goblint/analyzer, pull requests merged in 2022-05, with the labels that each got.

#709 Fix incremental warnings with reluctant destabilization
  src/solvers/td3.ml
  tests/incremental/13-restart-write/06-mutex-simple-reluctant.c
  tests/incremental/13-restart-write/06-mutex-simple-reluctant.json
  tests/incremental/13-restart-write/06-mutex-simple-reluctant.patch
  tests/incremental/13-restart-write/07-mutex-simple-reluctant2.c
  tests/incremental/13-restart-write/07-mutex-simple-reluctant2.json
  tests/incremental/13-restart-write/07-mutex-simple-reluctant2.patch
  tests/incremental/13-restart-write/08-mutex-simple-reluctant3.c
  tests/incremental/13-restart-write/08-mutex-simple-reluctant3.json
  tests/incremental/13-restart-write/08-mutex-simple-reluctant3.patch
Labels: bug, precision

#713 Incremental: (Cheap!) Full Reachability to Prune
  src/solvers/postSolver.ml
  src/solvers/td3.ml
  src/util/options.schema.json
  tests/incremental/00-basic/09-unreach.c
  tests/incremental/00-basic/09-unreach.json
  tests/incremental/00-basic/09-unreach.patch
  tests/incremental/00-basic/10-reach.c
  tests/incremental/00-basic/10-reach.json
  tests/incremental/00-basic/10-reach.patch
  tests/incremental/00-basic/11-unreach-reusesuper.c
  tests/incremental/00-basic/11-unreach-reusesuper.json
  tests/incremental/00-basic/11-unreach-reusesuper.patch
  tests/incremental/01-force-reanalyze/01-int-reluctant.json
  tests/incremental/03-precision-annotation/02-reluctant-int-annotation.json
  tests/incremental/03-precision-annotation/03-reluctant-int-annotation-dyn.json
  tests/incremental/13-restart-write/05-race-call-remove.c
  tests/incremental/13-restart-write/05-race-call-remove.json
  tests/incremental/13-restart-write/05-race-call-remove.patch
Labels: bug, precision

#695 Add option for ignoring races from `free`
  src/analyses/accessAnalysis.ml
  src/analyses/libraryFunctions.ml
  src/analyses/libraryFunctions.mli
  src/analyses/mutexAnalysis.ml
  src/domains/access.ml
  src/domains/accessKind.ml
  src/domains/events.ml
  src/domains/queries.ml
  src/util/options.schema.json
  tests/regression/04-mutex/64-free_direct_rc.c
  tests/regression/04-mutex/65-free_indirect_rc.c
  tests/regression/04-mutex/66-free_direct_nc.c
  tests/regression/04-mutex/67-free_indirect_nr.c
Labels: usability, precision

#707 Add option sem.unknown_function.invalidate.args
  src/analyses/accessAnalysis.ml
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/base.ml
  src/analyses/symbLocks.ml
  src/analyses/varEq.ml
  src/util/options.schema.json
Labels: feature, precision, benchmarking

#717 Interactive: fix expression locations
  .semgrep/cil.yml
  src/transform/evalAssert.ml
  src/util/cilfacade0.ml
  tests/regression/04-mutex/81-if-cond-race-loc.c
Labels: bug, usability

#712 Add `realloc` support
  src/analyses/base.ml
  src/analyses/libraryFunctions.ml
  src/analyses/region.ml
  src/cdomains/valueDomain.ml
  src/util/cilfacade.ml
  tests/regression/02-base/76-realloc.c
  tests/regression/02-base/77-chrony-sched-array.c
  tests/regression/02-base/78-realloc-free.c
Labels: bug, precision

#705 Add template for Taint Analysis Tutorial
  docs/developer-guide/debugging.md
  docs/developer-guide/firstanalysis.md
  make.sh
  src/analyses/libraryFunctions.ml
  src/analyses/tutorials/taint.ml
  src/domains/setDomain.ml
  tests/regression/99-tutorials/03-taint_simple.c
  tests/regression/99-tutorials/04-taint_inter.c
  unittest/maindomaintest.ml
Labels: usability, documentation

#724 Interactive: improvements for chrony story
  docs/user-guide/annotating.md
  scripts/update_suite.rb
  src/analyses/accessAnalysis.ml
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/apron/apronPriv.apron.ml
  src/analyses/libraryFunctions.ml
  src/analyses/symbLocks.ml
  src/analyses/threadJoins.ml
  src/analyses/varEq.ml
  src/cdomains/exp.ml
  src/cdomains/mHP.ml
  src/util/options.schema.json
  tests/regression/02-base/78-realloc-free.c
  tests/regression/06-symbeq/37-funloop_index.c
  tests/regression/06-symbeq/38-chrony-name2ipaddress.c
  tests/regression/06-symbeq/39-funloop_index_bad.c
  tests/regression/46-apron2/03-other-assume.c
  tests/regression/46-apron2/04-other-assume-inprec.c
  tests/regression/51-threadjoins/03-other-assume.c
  tests/regression/51-threadjoins/04-assume-recreate.c
  tests/regression/51-threadjoins/05-assume-unknown.c
Labels: feature, benchmarking

#729 Interactive: improvements for smtprc story
  src/analyses/base.ml
  src/analyses/libraryFunctions.ml
  tests/regression/03-practical/27-charptr_null.c
Labels: bug, benchmarking

#629 Incremental TD3: limit side-effected restarting using fuel
  src/solvers/td3.ml
  src/util/options.schema.json
  tests/incremental/11-restart/14-mutex-simple-wrap2.c
  tests/incremental/11-restart/14-mutex-simple-wrap2.json
  tests/incremental/11-restart/14-mutex-simple-wrap2.patch
  tests/incremental/11-restart/15-mutex-simple-wrap1.c
  tests/incremental/11-restart/15-mutex-simple-wrap1.json
  tests/incremental/11-restart/15-mutex-simple-wrap1.patch
  tests/incremental/11-restart/16-mutex-simple-wrap1-global.c
  tests/incremental/11-restart/16-mutex-simple-wrap1-global.json
  tests/incremental/11-restart/16-mutex-simple-wrap1-global.patch
  tests/incremental/11-restart/17-mutex-simple-fuel.c
  tests/incremental/11-restart/17-mutex-simple-fuel.json
  tests/incremental/11-restart/17-mutex-simple-fuel.patch
Labels: precision, performance

#745 Add YAML witness validation by invariant checking
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/analyses/base.ml
  src/analyses/malloc_null.ml
  src/analyses/tutorials/taint.ml
  src/analyses/uninit.ml
  src/analyses/varEq.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/basetype.ml
  src/cdomains/intDomain.ml
  src/cdomains/lockDomain.ml
  src/cdomains/symbLocksDomain.ml
  src/domains/access.ml
  src/domains/invariantCil.ml
  src/framework/control.ml
  src/incremental/compareAST.ml
  src/transform/evalAssert.ml
  src/util/messageCategory.ml
  src/util/options.schema.json
  src/witness/yamlWitness.ml
Labels: feature, sv-comp, benchmarking
