Repository goblint/analyzer, pull requests merged in 2022-07, with the labels that each got.

#770 Replace MustBeEqual, MayBeEqual and MayBeLess queries with EvalInt
  conf/traces-rel.json
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/base.ml
  src/analyses/expRelation.ml
  src/analyses/mCP.ml
  src/analyses/symbLocks.ml
  src/analyses/varEq.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/intDomain.ml
  src/domains/queries.ml
  src/util/cilfacade.ml
  src/util/options.schema.json
  tests/regression/02-base/82-eq-no-overflow.c
  tests/regression/02-base/83-evalint-mustbeequal.c
  tests/regression/02-base/84-evalint-maybeequal.c
  tests/regression/02-base/85-evalint-maybeless.c
  tests/regression/46-apron2/18-evalint-torture.c
  tests/regression/54-unroll_arrays/02-simple_array_in_loops.c
Labels: cleanup, precision, performance

#779 Pass Escaped Locals to Callee as They Need to Be Considered Globals
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/cdomains/basetype.ml
  tests/regression/11-heap/03-linked.c
  tests/regression/45-escape/05-global-single-threaded.c
Labels: unsound

#781 Modify Library Function Specification for assert to not dereference its argument
  src/analyses/libraryFunctions.ml
  src/domains/events.ml
  tests/regression/02-base/86-spurious.c
Labels: bug, usability, precision

#782 Remove erroneous call to `truncateCilint` in `min_for`
  src/cdomains/intDomain.ml
  tests/regression/38-int-refinements/02-strange-ulong.c
Labels: bug, unsound

#281 OCaml's `let*` instead of `ocaml-monadic` ppx
  dune-project
  goblint.opam
  goblint.opam.locked
  src/dune
  src/extract/pml.ml
  src/extract/pml_arinc.ml
Labels: cleanup, setup

#790 Fix get_ikind in eval_rv_ask_mustbeequal and is_safe_cast
  src/analyses/base.ml
  src/cdomains/valueDomain.ml
Labels: bug, benchmarking

#788 Provide Common Configurations
  .github/workflows/options.yml
  conf/dune
  conf/examples/large-program.json
  conf/examples/medium-program.json
  conf/examples/very-precise.json
  docs/user-guide/configuring.md
  docs/user-guide/running.md
  dune-project
  src/maingoblint.ml
  src/sites/goblint_sites.mli
  src/sites/sites_dune/goblint_sites.ml
  src/sites/sites_js/goblint_sites.ml
  src/util/gobConfig.ml
Labels: feature, usability, documentation

#794 Make `mutex-meet-tid` Sound for Threads Exited by `pthread_exit(...)` & Improve Precision of `threadJoins` Analysis
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/threadJoins.ml
  tests/regression/46-apron2/19-tid-toy-10-exit.c
  tests/regression/46-apron2/20-inprecise-returns.c
  tests/regression/46-apron2/21-tid-toy-10-exit-othert.c
Labels: bug, unsound, precision

#761 Interval Analysis for Floating-point values
  src/analyses/base.ml
  src/analyses/libraryDesc.ml
  src/analyses/libraryFunctions.ml
  src/cdomains/floatDomain.ml
  src/cdomains/floatDomain.mli
  src/cdomains/floatOps/floatOps.ml
  src/cdomains/floatOps/floatOps.mli
  src/cdomains/floatOps/stubs.c
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/cdomains/preValueDomain.ml
  src/cdomains/valueDomain.ml
  src/dune
  src/util/cilfacade.ml
  src/util/messageCategory.ml
  src/util/options.schema.json
  src/util/precisionUtil.ml
  tests/regression/57-floats/01-base.c
  tests/regression/57-floats/02-node_configuration.c
  tests/regression/57-floats/03-infinity_or_nan.c
  tests/regression/57-floats/04-casts.c
  tests/regression/57-floats/05-invariant.c
  tests/regression/57-floats/06-library_functions.c
  tests/regression/57-floats/07-equality.c
  tests/regression/57-floats/08-bit_casts.c
  tests/regression/57-floats/09-svcomp_float_req_bl_1252b.c
  tests/regression/57-floats/10-svcomp_floats_cbmc_regression_float11.c
  tests/regression/57-floats/11-advanced_invariants.c
  tests/regression/57-floats/12-subtraction_assignment.c
  tests/regression/57-floats/13-refine-branch.c
  unittest/cdomains/floatDomainTest.ml
  unittest/mainTest.ml
Labels: feature, student-job, sv-comp, precision, practical-course

#795 Fix ARINC testing
  src/analyses/arinc.ml
  src/analyses/mutexEventsAnalysis.ml
  tests/regression/17-arinc/01-sema.c
  tests/regression/17-arinc/02-unique_proc.c
  tests/regression/17-arinc/03-preemt_lock.c
  tests/regression/17-arinc/04-sema-strcpy.c
Labels: bug, unsound

#722 Malloc uniqueness
  src/analyses/base.ml
  src/analyses/libraryFunctions.ml
  src/analyses/mallocWrapperAnalysis.ml
  src/cdomains/threadFlagDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/lattice.ml
  src/domains/printable.ml
  src/util/options.schema.json
  src/witness/observerAnalysis.ml
  src/witness/yamlWitness.ml
  tests/regression/11-heap/04-malloc_unique_addresses.c
  tests/regression/11-heap/05-malloc_not_unique_address.c
  tests/regression/11-heap/06-wrapper_plus_unique_addresses.c
  tests/regression/11-heap/07-strong_updates.c
  tests/regression/11-heap/08-no_strong_update.c
  tests/regression/11-heap/09-no_strong_update_not_unique_thread.c
  tests/regression/11-heap/10-no_strong_update_different_size.c
  tests/regression/11-heap/11-threads_malloc_no_race.c
  tests/regression/11-heap/12-calloc.c
  tests/regression/11-heap/13-linear-search.c
  tests/regression/22-partitioned_arrays/17-large_arrays.c
  unittest/cdomains/floatDomainTest.ml
Labels: student-job, precision

#797 Fix some asserts in tests
  tests/regression/01-cpa/22-null_ptr.c
  tests/regression/08-malloc_null/02-paths-malloc.c
  tests/regression/30-fast_global_inits/04-non-zero.c
  tests/regression/30-fast_global_inits/05-non-zero-performance.c
Labels: bug, testing

#746 Hide mutex structure contents and standard globals in base analysis
  src/analyses/base.ml
  src/cdomains/valueDomain.ml
  src/framework/control.ml
  src/util/options.schema.json
Labels: bug, unsound, usability

#802 Fix Crash When the Index Offset has Abstract Type `Address`
  src/analyses/base.ml
  src/cdomains/addressDomain.ml
  src/cdomains/valueDomain.ml
  src/maingoblint.ml
  src/util/cilfacade.ml
  tests/regression/02-base/87-casts-dep-on-param.c
Labels: bug

#806 Fixed errors when using Unroll ArrayDomain on svcomp-tests
  src/cdomains/arrayDomain.ml
  tests/regression/54-unroll_arrays/03-large_index_type.c
  tests/regression/54-unroll_arrays/04-access_no_bounds.c
Labels: bug, sv-comp
