Repository goblint/analyzer, pull requests merged in 2022-09, with the labels that each got.

#828 Remove `ID.is_bool` and `ID.is_int`
  src/analyses/assert.ml
  src/analyses/base.ml
  src/analyses/extractPthread.ml
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/cdomains/lockDomain.ml
  src/cdomains/lval.ml
  src/cdomains/symbLocksDomain.ml
  src/domains/intDomainProperties.ml
  src/domains/queries.ml
  src/transform/expressionEvaluation.ml
  src/transform/transform.ml
  src/witness/yamlWitness.ml
  tests/regression/01-cpa/57-def_exc-interval-inconsistent.c
  unittest/cdomains/intDomainTest.ml
Labels: cleanup, bug, sv-comp

#834 Remove side effects from base privatization invariant `write_global`-s
  src/analyses/basePriv.ml
Labels: performance

#809 Optimize and refactor "Hoare" domains
  src/analyses/base.ml
  src/cdomains/addressDomain.ml
  src/cdomains/lval.ml
  src/cdomains/valueDomain.ml
  src/domains/disjointDomain.ml
  src/domains/hoareDomain.ml
  src/domains/lattice.ml
  src/domains/mapDomain.ml
  src/domains/setDomain.ml
  src/framework/constraints.ml
  src/framework/edge.ml
  src/framework/node.ml
  src/witness/myARG.ml
  src/witness/witnessConstraints.ml
  tests/regression/00-sanity/33-hoare-over-paths.c
  tests/regression/00-sanity/34-hoare-over-addrs.c
  tests/regression/02-base/94-ad-first-field.c
  tests/regression/02-base/95-ad-zero-index.c
  tests/regression/56-witness/50-witness-lifter-fp1.c
  tests/regression/56-witness/51-witness-lifter-ps1.c
  unittest/domains/mapDomainTest.ml
Labels: cleanup, bug, performance

#827 Fix verify errors on sv-benchmarks
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/cdomains/valueDomain.ml
  src/domains/disjointDomain.ml
  src/domains/lattice.ml
  src/domains/partitionDomain.ml
  src/util/cilType.ml
  tests/regression/01-cpa/56-def_exc-fp1.c
  tests/regression/06-symbeq/40-var_eq-widen1.c
Labels: bug, sv-comp

#831 Generalize protection logging from apron
  src/analyses/apron/apronPriv.apron.ml
  src/analyses/commonPriv.ml
  src/analyses/mutexAnalysis.ml
Labels: cleanup, feature

#838 Add option `sem.null-pointer.dereference`
  conf/svcomp.json
  conf/svcomp21.json
  conf/svcomp22.json
  src/analyses/base.ml
  src/util/options.schema.json
  tests/regression/02-base/96-null-deref-top.c
  tests/regression/02-base/97-null-deref-none.c
Labels: bug, unsound, precision

#520 Analysis of `pthread_cond`
  src/analyses/accessAnalysis.ml
  src/analyses/extractPthread.ml
  src/analyses/libraryDesc.ml
  src/analyses/libraryFunctions.ml
  src/analyses/mHPAnalysis.ml
  src/analyses/mutexEventsAnalysis.ml
  src/analyses/pthreadSignals.ml
  src/cdomains/mHP.ml
  tests/regression/59-signals/01-simple.c
  tests/regression/59-signals/02-unsignaled.c
  tests/regression/59-signals/03-too-early.c
  tests/regression/59-signals/04-too-late.c
  tests/regression/59-signals/05-too-early-many.c
  tests/regression/59-signals/06-simple-many.c
  tests/regression/59-signals/07-too-early-mhp.c
Labels: feature, precision

#830 Flow-insensitive YAML witness invariants
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/basePriv.mli
  src/analyses/mCP.ml
  src/cdomains/valueDomain.ml
  src/domains/queries.ml
  src/framework/constraints.ml
  src/witness/yamlWitness.ml
  src/witness/yamlWitnessType.ml
Labels: feature, sv-comp

#787 Use Cram for tests
  .github/workflows/locked.yml
  .github/workflows/unlocked.yml
  dune-project
  tests/extraction/00-sanity.t
  tests/extraction/01-base.t
  tests/extraction/02-starve.t
  tests/extraction/dune
  tests/extraction/dune-project
  tests/extraction/test.sh
  tests/regression/00-sanity/01-assert.t
  tests/regression/00-sanity/dune
  tests/regression/04-mutex/01-simple_rc.t
  tests/regression/04-mutex/dune
  tests/regression/dune
Labels: testing

#840 Derive `CilType` with ppx
  src/cdomains/intDomain.ml
  src/util/cilType.ml
Labels: cleanup, type-safety, performance

#497 Expression splitting analysis prototype
  docs/user-guide/annotating.md
  includes/goblint.h
  src/analyses/expsplit.ml
  src/analyses/libraryFunctions.ml
  src/domains/events.ml
  src/framework/constraints.ml
  src/util/options.schema.json
  tests/regression/49-expsplit/01-null-exp-split.c
  tests/regression/49-expsplit/02-null-value-split.c
  tests/regression/49-expsplit/03-int-value-split.c
  tests/regression/49-expsplit/04-multi-split.c
  tests/regression/49-expsplit/05-fun-split.c
  tests/regression/49-expsplit/06-fun-combine-split.c
Labels: feature, precision

#842 Add some information on how to build Goblint for benchmarking
  docs/user-guide/benchmarking.md
  mkdocs.yml
Labels: documentation, benchmarking

#837 Clean up some special functions
  src/analyses/accessAnalysis.ml
  src/analyses/base.ml
  src/analyses/extractPthread.ml
  src/analyses/libraryDesc.ml
  src/analyses/libraryDsl.ml
  src/analyses/libraryDsl.mli
  src/analyses/libraryFunctions.ml
  src/analyses/libraryFunctions.mli
  src/analyses/malloc_null.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/mutexEventsAnalysis.ml
  src/analyses/symbLocks.ml
  src/analyses/varEq.ml
  tests/regression/04-mutex/40-rw_lock_rc.c
Labels: cleanup
