Repository goblint/analyzer, pull requests merged in 2022-11, with the labels that each got.

#877 First approximation of `pthread_setspecific` by escaping things reachable from the argument and invalidating all globals
  src/analyses/libraryFunctions.ml
  src/analyses/threadEscape.ml
  tests/regression/41-stdlib/04-pthread-specific.c
Labels: bug, unsound

#878 Add some further library functions
  src/analyses/libraryFunctions.ml
  tests/regression/41-stdlib/04-more.c
Labels: bug, precision

#875 Add `abortUnless` analysis
  src/analyses/abortUnless.ml
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/base.ml
  src/domains/events.ml
  tests/regression/46-apron2/25-abortUnless.c
  tests/regression/62-abortUnless/01-simple.c
  tests/regression/62-abortUnless/02-unsound-abortUnless.c
  tests/regression/62-abortUnless/03-unsound-min.c
Labels: feature, precision

#882 Do not deref into function or mutex in invariant
  src/cdomains/valueDomain.ml
  src/witness/witness.ml
  tests/regression/28-race_reach/95-deref-fun.c
  tests/regression/28-race_reach/96-deref-fun2.c
  tests/regression/29-svcomp/29-witness.c
Labels: bug, sv-comp

#886 Add missing `__VERIFIER_nondet_X()`s
  lib/sv-comp/stub/src/sv-comp.c
  src/analyses/libraryFunctions.ml
  tests/regression/29-svcomp/30-nondets.c
Labels: sv-comp, precision

#883 Make autotuner set `apron.no-context` for functions where it sets `base.no-interval`
  src/autoTune.ml
  tests/regression/46-apron2/26-autotune.c
Labels: performance

#890 Do not produce overflow warnings from Apron & Unroll typedefs for `invariant`
  src/analyses/base.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/domains/queries.ml
  tests/regression/02-base/99-refine-typedef.c
  tests/regression/46-apron2/26-overflow.c
Labels: bug, precision

#896 Fix handling of labels in unrolling & add possibility to run CIL checks on CFGs
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/util/cilCfg.ml
  src/util/loopUnrolling.ml
  src/util/options.schema.json
  tests/regression/55-loop-unrolling/01-simple-cases.c
  tests/regression/55-loop-unrolling/02-break.c
  tests/regression/55-loop-unrolling/03-break-right-place.c
  tests/regression/55-loop-unrolling/04-simple.c
  tests/regression/55-loop-unrolling/05-continue.c
  tests/regression/55-loop-unrolling/06-simple-cases-unrolled.c
  tests/regression/55-loop-unrolling/07-nested-unroll.c
  tests/regression/55-loop-unrolling/08-bad.c
  tests/regression/55-loop-unrolling/09-weird.c
Labels: bug, pr-dependency

#897 Move let syntax for applicative functor/monad to general library
  src/analyses/base.ml
  src/analyses/threadId.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/valueDomain.ml
  src/util/gobList.ml
  src/util/gobOption.ml
  src/util/gobResult.ml
  src/util/gobYaml.ml
  src/util/messageUtil.ml
  src/util/messages.ml
  src/witness/myARG.ml
  src/witness/witnessUtil.ml
  src/witness/yamlWitnessType.ml
Labels: cleanup

#904 Int Domains: Do not refine on joining or widening
  src/cdomains/intDomain.ml
  tests/regression/38-int-refinements/05-invalid-widen.c
Labels: bug

#902 Cleanup array domain
  src/analyses/base.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/arrayDomain.mli
  src/cdomains/expDomain.ml
  src/cdomains/valueDomain.ml
Labels: cleanup

#907 Catch `Top` case for `TS.elements` call in `threadAnalysis`
  src/analyses/threadAnalysis.ml
  tests/regression/10-synch/27-tid-array-malloc-2.c
Labels: bug

#894 Handle overflows in congruence domain more precisely
  src/cdomains/intDomain.ml
  src/util/intOps.ml
  tests/regression/37-congruence/08-mod-16-unsigned-overflow.c
  tests/regression/37-congruence/09-mod-pow-two-unsigned-overflow.c
  tests/regression/37-congruence/10-overflow-unsigned-special-cases.c
  tests/regression/37-congruence/11-overflow-signed.c
Labels: sv-comp, precision

#916 Fix Apron reading globals with offsets
  src/analyses/apron/apronAnalysis.apron.ml
  src/util/xmlUtil.ml
  tests/regression/46-apron2/28-sv-comp-unroll-term.c
  tests/regression/46-apron2/29-read-var-offset.c
Labels: bug, sv-comp, performance

#911 Autotune: Conditionally activate congruence integer domain
  src/autoTune.ml
Labels: sv-comp

#924 Fix address set meet
  src/cdomains/lval.ml
  tests/regression/29-svcomp/31-dd-address-meet.c
Labels: bug, unsound

#926 Make Address Representatives Use Unit-domain for Index-Offsets
  src/cdomains/lval.ml
Labels: cleanup, bug, unsound

#905 Option to set the C language standard for CIL in Goblint
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/util/cilfacade.ml
  src/util/options.schema.json
Labels: feature, c99, c11, pr-dependency

#836 Group globals for comparison and updating of ids
  src/incremental/compareAST.ml
  src/incremental/compareCIL.ml
  src/incremental/updateCil.ml
  src/solvers/td3.ml
  src/util/server.ml
Labels: bug

#841 Fixes for the incremental analysis with cfg comparison
  .github/workflows/locked.yml
  .github/workflows/unlocked.yml
  docs/developer-guide/testing.md
  scripts/update_suite.rb
  src/solvers/td3.ml
Labels: bug

#918 ArrayDomain: `normalize` after `widen` and `join`
  src/cdomains/arrayDomain.ml
  tests/regression/22-partitioned_arrays/20-more-fixpoint.c
Labels: cleanup, bug

#922 Base.invariant: Refine congruence information on `x % 2 != c`
  src/analyses/base.ml
  src/util/precisionUtil.ml
  tests/regression/37-congruence/12-invariant-ineq.c
Labels: precision

#923 Remove hack to `--undef __BLOCKS__`
  src/maingoblint.ml
Labels: cleanup

#908 Support `location_invariant` entry type in YAML witnesses
  src/witness/yamlWitness.ml
  src/witness/yamlWitnessType.ml
  tests/regression/56-witness/01-base-lor-enums.yml
  tests/regression/56-witness/02-base-lor-addr.yml
  tests/regression/56-witness/03-int-log-short.yml
  tests/regression/56-witness/04-base-priv-sync-prune.yml
Labels: feature

#931 Add custom location marks to exception backtraces
  src/dune
  src/framework/constraints.ml
  src/framework/control.ml
  src/maingoblint.ml
  src/util/backtrace/dune
  src/util/backtrace/goblint_backtrace.ml
  src/util/backtrace/goblint_backtrace.mli
Labels: feature, bug, debugging

#933 Marshal `array_map` in `Base`, only collect entries when needed
  src/analyses/base.ml
Labels: bug

#596 Extract function and node specific logic from TD3
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/solvers/td3.ml
  unittest/solver/solverTest.ml
Labels: cleanup
