Repository goblint/analyzer, pull requests merged in 2022-12, with the labels that each got.

#935 Read offsets separately in eval_rv_base for pointer dereference
  src/analyses/base.ml
  src/cdomains/structDomain.ml
  src/cdomains/structDomain.mli
  tests/regression/43-struct-domain/27-chrony-nameserv-sched-array.c
  tests/regression/43-struct-domain/28-chrony-nameserv-sched-array2.c
  tests/regression/43-struct-domain/29-chrony-nameserv-sched-array2-set-struct.c
  tests/regression/43-struct-domain/30-ambig-field.c
Labels: bug, unsound, precision

#945 Fix compilation on OCaml 5.0.0~rc1
  .github/workflows/unlocked.yml
  src/cdomains/fileDomain.ml
  src/util/processPool.ml
Labels: setup

#738 Eager destab, cheap abort
  src/solvers/postSolver.ml
  src/solvers/td3.ml
  src/util/options.schema.json
  tests/incremental/14-manual-restart/04-restarting_and_aborting.c
  tests/incremental/14-manual-restart/04-restarting_and_aborting.json
  tests/incremental/14-manual-restart/04-restarting_and_aborting.patch
Labels: feature, performance

#944 Prevent modification of options while the solver runs
  src/analyses/malloc_null.ml
  src/framework/control.ml
  src/maingoblint.ml
  src/util/gobConfig.ml
  src/util/server.ml
Labels: cleanup, student-job

#950 Fix Unreached Fixpoint in Reluctant Incremental Analysis
  conf/zstd-race.json
  src/solvers/td3.ml
  src/util/options.schema.json
  tests/incremental/00-basic/15-reluctant-test.c
  tests/incremental/00-basic/15-reluctant-test.json
  tests/incremental/00-basic/15-reluctant-test.patch
Labels: bug, unsound

#957 Fix: not found global should be added not removed
  src/incremental/compareCIL.ml
Labels: bug

#960 Only pass stable `reluctant_vs` to postsolver
  src/solvers/td3.ml
Labels: bug
