Repository goblint/analyzer, pull requests merged in 2022-04, with the labels that each got.

#661 Fix read-write lock access handling
  src/analyses/mutexAnalysis.ml
  src/cdomains/lockDomain.ml
  src/domains/access.ml
  tests/regression/04-mutex/40-rw_lock_rc.c
  tests/regression/04-mutex/41-pt_rwlock.c
Labels: bug, precision

#618 ldv-benchmarks races benchmarking
  conf/ldv-races.json
  src/analyses/varEq.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/cdomains/regionDomain.ml
  src/cdomains/valueDomain.ml
  src/util/options.schema.json
  src/witness/witness.ml
  tests/regression/06-symbeq/32-var_eq-unknown-invalidate.c
  tests/regression/21-casts/04-neg-to-unsigned-invariant.c
Labels: bug, unsound, sv-comp, benchmarking

#663 Exclude functions with changed header from reluctant destabilization
  src/incremental/compareCIL.ml
  src/solvers/td3.ml
  src/util/server.ml
Labels: performance

#157 Add transformation to instrument a program with asserts & Produce invariants from Apron
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/baseDomain.ml
  src/domains/queries.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/transform/evalAssert.ml
  src/util/options.schema.json
  tests/regression/24-octagon/01-octagon_simple.c
  tests/regression/36-apron/01-octagon_simple.c
Labels: testing, student-job

#646 Add nodes (with joined contexts) comparison
  scripts/creduce/incremental.sh
  scripts/test-incremental.sh
  src/framework/constraints.ml
  src/framework/control.ml
  src/util/options.schema.json
  src/util/precCompare.ml
Labels: precision, benchmarking, debugging

#656 Improve cfg comparison
  src/incremental/compareCFG.ml
  src/incremental/compareCIL.ml
Labels: cleanup, performance

#675 Rename and split `exp.precious_globs` to `exp.exclude_from_earlyglobs` and `exp.exclude_from_invalidation`
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/baseUtil.ml
  src/analyses/baseUtil.mli
  src/analyses/commonPriv.ml
  src/util/options.schema.json
  tests/regression/01-cpa/50-earlyglobs_precious.c
Labels: cleanup, usability

#632 Add splitting of Compilation Database entries with multiple .c files
  src/util/compilationDatabase.ml
  src/util/gobFpath.ml
  src/util/options.schema.json
  unittest/mainTest.ml
  unittest/util/compilationDatabaseTest.ml
Labels: benchmarking, preprocessing

#682 Remove `version_map` that was used for `updateCIL`
  src/incremental/compareCIL.ml
  src/incremental/maxIdUtil.ml
  src/incremental/updateCil.ml
  src/incremental/versionLookup.ml
  src/maingoblint.ml
  src/util/server.ml
Labels: cleanup

#680 Fix incorrect relative paths when parsing preprocessed files
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/domains/access.ml
  src/framework/analyses.ml
  src/maingoblint.ml
  src/util/gobFpath.ml
  src/util/preprocessor.ml
Labels: usability

#687 Fix fixpoint error when comparing blobs with non-blobs
  src/cdomains/valueDomain.ml
  tests/regression/02-base/69-ipmi-struct-blob-fixpoint.c
Labels: bug

#686 Handle thread escaping via global and after thread creation
  src/analyses/threadEscape.ml
  tests/regression/45-escape/01-local-in-pthread.c
  tests/regression/45-escape/02-local-in-global.c
  tests/regression/45-escape/03-local-in-pthread-a.c
  tests/regression/45-escape/04-imprecision.c
Labels: bug, unsound

#690 Primitive malloc freshness analysis
  src/analyses/base.ml
  src/analyses/libraryFunctions.ml
  src/analyses/mallocFresh.ml
  src/analyses/symbLocks.ml
  tests/regression/03-practical/25-zstd-customMem.c
  tests/regression/06-symbeq/35-zstd-thread-pool-multi.c
  tests/regression/45-escape/50-fresh-malloc.c
  tests/regression/45-escape/51-fresh-global.c
Labels: feature, precision

#694 Fix unsound var_eq unknown function invalidation
  src/analyses/base.ml
  src/analyses/varEq.ml
  tests/regression/06-symbeq/32-var_eq-unknown-invalidate.c
Labels: bug, unsound

#696 Improve `memset` analysis
  src/analyses/accessAnalysis.ml
  src/analyses/base.ml
  src/analyses/libraryFunctions.ml
  tests/regression/02-base/75-memset.c
  tests/regression/04-mutex/70-memset_indirect_nr.c
  tests/regression/04-mutex/71-memset_direct_rc.c
  tests/regression/06-symbeq/31-zstd-thread-pool.c
  tests/regression/06-symbeq/35-zstd-thread-pool-multi.c
Labels: feature, unsound, usability, precision
