Repository goblint/analyzer, pull requests merged in 2022-01, with the labels that each got.

#512 Describe incremental tests in developer docs
  docs/developer-guide/testing.md
Labels: documentation

#515 Threshold widening for Interval & Configurable DefExc widen
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/intDomain.ml
  src/util/options.schema.json
  src/util/wideningThresholds.ml
  src/util/wideningThresholds.mli
  tests/regression/03-practical/23-knot-timeout.c
  tests/regression/03-practical/24-threshold.c
  tests/regression/34-localization/02-hybrid.c
  tests/regression/42-annotated-precision/26-34_02-hybrid.c
Labels: feature, precision

#519 Refactor race warnings (accesses) to use global invariant on master
  conf/svcomp.json
  conf/svcomp21.json
  conf/svcomp22.json
  src/analyses/accessAnalysis.ml
  src/analyses/mCP.ml
  src/analyses/mutexAnalysis.ml
  src/domains/access.ml
  src/domains/events.ml
  src/domains/queries.ml
  src/framework/control.ml
  src/solvers/postSolver.ml
  src/util/options.schema.json
  src/witness/witness.ml
  tests/incremental/00-basic/06-threadid.c
  tests/regression/02-base/06-side_effect1.c
  tests/regression/02-base/07-side_effect2.c
  tests/regression/02-base/09-ambigpointer.c
  tests/regression/02-base/10-init_allfuns.c
  tests/regression/02-base/23-malloc_globmt.c
  tests/regression/02-base/30-escape_sound.c
  tests/regression/02-base/41-calloc_globmt.c
  tests/regression/03-practical/14-call_by_pointer.c
Labels: cleanup, feature

#514 Fix unsoundness for large partitioned arrays
  src/cdomains/arrayDomain.ml
  tests/regression/22-partitioned_arrays/17-large_arrays.c
  tests/regression/22-partitioned_arrays/18-large_arrays-nocalloc.c
Labels: bug, unsound

#530 Ignore `.s` files (assembly) in compilation database
  src/util/compilationDatabase.ml
Labels: bug, usability

#531 Incremental: fix cfg comparison
  src/incremental/compareCFG.ml
  tests/incremental/02-cfg-comparison/00-infinite-loop.c
  tests/incremental/02-cfg-comparison/00-infinite-loop.json
  tests/incremental/02-cfg-comparison/00-infinite-loop.patch
Labels: bug

#536 Reuse more simple printing code
  src/analyses/tutorials/signs.ml
  src/cdomains/arincDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/intDomain.ml
  src/cdomains/lval.ml
  src/cdomains/lvalMapDomain.ml
  src/cdomains/osektupel.ml
  src/cdomains/threadIdDomain.ml
  src/domains/access.ml
  src/domains/printable.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/node.ml
  src/maindomaintest.ml
  src/util/cilType.ml
  src/witness/witnessConstraints.ml
Labels: cleanup

#537 Store and load data of analyses in incremental runs. (Cherry-picking #498 onto master)
  src/framework/control.ml
  src/incremental/serialize.ml
  src/maingoblint.ml
Labels: feature

#539 Add option `ana.thread.include-node` to disable nodes in TIDs
  src/cdomains/threadIdDomain.ml
  src/util/options.schema.json
  tests/regression/36-apron/97-no-loc.c
  tests/regression/36-apron/98-loc.c
Labels: feature, precision, performance

#540 Ignore atomic types in race detection
  src/domains/access.ml
  tests/regression/04-mutex/62-simple_atomic_nr.c
Labels: feature, precision, c11

#522 Server mode
  dune-project
  goblint.opam
  goblint.opam.locked
  src/dune
  src/incremental/serialize.ml
  src/maingoblint.ml
  src/util/gobConfig.ml
  src/util/options.schema.json
  src/util/server.ml
Labels: feature

#518 Use MHP to exclude races & Refactoring MHP
  src/analyses/accessAnalysis.ml
  src/analyses/apron/apronPriv.apron.ml
  src/cdomains/mHP.ml
  src/domains/access.ml
  tests/regression/10-synch/13-two_threads_nr.c
  tests/regression/10-synch/14-two_threads_rc.c
  tests/regression/10-synch/15-join_other_nr.c
  tests/regression/10-synch/16-join_loop_nr.c
  tests/regression/53-races-mhp/01-not-created.c
  tests/regression/53-races-mhp/02-join.c
Labels: cleanup, feature, precision

#528 Add more `__builtin`s and `strsignal` to library functions
  src/analyses/libraryFunctions.ml
  tests/regression/04-mutex/61-allfuns-globs.c
Labels: precision

#525 Use global invariant for dead branch detection
  src/cdomains/basetype.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/util/deadcode.ml
  tests/incremental/00-basic/07-dead-branch.c
  tests/incremental/00-basic/07-dead-branch.json
  tests/incremental/00-basic/07-dead-branch.patch
  tests/regression/01-cpa/55-dead-branch-multiple.c
Labels: bug, precision

#548 LvalDomain: Print offset of rich varinfo as well
  src/cdomains/lval.ml
Labels: bug

#546 Fix implementation of `equal` and `compare` in `IntDomTupleImpl`
  src/cdomains/intDomain.ml
  tests/incremental/03-precision-annotation/01-change_precision.c
  tests/incremental/03-precision-annotation/01-change_precision.json
  tests/incremental/03-precision-annotation/01-change_precision.patch
Labels: bug

#535 Add files list to json-messages output
  src/framework/analyses.ml
  src/maingoblint.ml
  src/util/compilationDatabase.ml
  src/util/dune
  src/util/makefileLexer.mll
  src/util/makefileParser.mly
  src/util/preprocessor.ml
Labels: feature, usability

#529 Generalize pairwise race detection
  src/analyses/accessAnalysis.ml
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/mCP.ml
  src/analyses/mCPAccess.ml
  src/analyses/mCPRegistry.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/region.ml
  src/analyses/symbLocks.ml
  src/analyses/threadFlag.ml
  src/analyses/threadId.ml
  src/cdomains/lval.ml
  src/cdomains/mHP.ml
  src/domains/access.ml
  src/domains/oldAccess.ml
  src/domains/queries.ml
  src/framework/analyses.ml
Labels: cleanup, feature, type-safety

#562 Avoid calling `context` with top of context insensitive analyses
  src/analyses/mCP.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/witness/witnessConstraints.ml
  tests/regression/00-sanity/29-earlyglobs-insens.c
Labels: bug

#561 Direct conversion between Zarith and Apron via `Z_mlgmpidl`
  src/cdomains/apron/apronDomain.apron.ml
  src/dune
  src/vendor/dune
  src/vendor/zarith/dune
  src/vendor/zarith/z_mlgmpidl.ml
  src/vendor/zarith/z_mlgmpidl.mli
Labels: cleanup

#551 Group racing accesses into disjoint components
  src/domains/access.ml
  tests/regression/10-synch/05-two_unique_two_lock.c
  tests/regression/10-synch/06-thread_nonunique_plain.c
Labels: usability, precision

#547 Add implementation for `pthread_once`
  includes/dune
  includes/pthread.c
  src/maingoblint.ml
  sv-comp/archive.sh
  tests/regression/02-base/10-init_allfuns.c
  tests/regression/02-base/71-pthread-once.c
  tests/regression/07-uninit/14-struct_in_struct.c
Labels: bug, unsound

#556 Document usage of `creduce`
  docs/developer-guide/debugging.md
Labels: documentation

#559 Fix address domain widening creating duplicates
  src/cdomains/intDomain.ml
  src/cdomains/lval.ml
  src/domains/hoareDomain.ml
  tests/regression/02-base/72-ad-widen-duplicate.c
  unittest/cdomains/lvalTest.ml
  unittest/mainTest.ml
Labels: bug

#560 Reenable and fix some OCaml warnings
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/extract_arinc.ml
  src/analyses/extract_osek.ml
  src/analyses/libraryFunctions.ml
  src/analyses/mCP.ml
  src/analyses/mCPRegistry.ml
  src/analyses/symbLocks.ml
  src/analyses/varEq.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/arincDomain.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/cdomains/lval.ml
  src/cdomains/lvalMapDomain.ml
  src/cdomains/osektupel.ml
  src/cdomains/threadIdDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/mapDomain.ml
  src/dune
  src/extract/pml.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/incremental/compareAST.ml
  src/prelude.ml
  src/solvers/sLR.ml
  src/spec/specLexer.mll
  src/spec/specUtil.ml
  src/util/arincUtil.ml
  src/util/gobConfig.ml
  src/util/oilParser.mly
  src/util/options.schema.json
  src/util/richVarinfo.ml
  src/util/server.ml
  src/util/tracing.ml
  src/witness/myARG.ml
  src/witness/witnessConstraints.ml
  tests/regression/36-apron/99-mine14-strengthening.c
  unittest/dune
  unittest/maindomaintest.ml
Labels: cleanup

#568 Add ikind argument to IntDomain arbitraries, fix some bugs
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/domains/intDomainProperties.ml
  unittest/maindomaintest.ml
Labels: bug, testing, unsound

#542 Add sim642/ppx_deriving_hash
  dune-project
  goblint.opam
  goblint.opam.locked
  src/analyses/base.ml
  src/analyses/tutorials/signs.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/arincDomain.ml
  src/cdomains/baseDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/exp.ml
  src/cdomains/fileDomain.ml
  src/cdomains/intDomain.ml
  src/cdomains/lval.ml
  src/cdomains/lvalMapDomain.ml
  src/cdomains/osektupel.ml
  src/cdomains/specDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/access.ml
  src/domains/oldAccess.ml
  src/domains/printable.ml
  src/dune
  src/framework/analyses.ml
  src/framework/cfgTools.ml
  src/framework/constraints.ml
  src/framework/node.ml
  src/incremental/compareCFG.ml
  src/solvers/sLR.ml
  src/solvers/sLRphased.ml
  src/solvers/sLRterm.ml
  src/solvers/td3.ml
  src/solvers/topDown.ml
  src/solvers/topDown_deprecated.ml
  src/solvers/topDown_space_cache_term.ml
  src/solvers/topDown_term.ml
  src/util/intOps.ml
  src/util/messageCategory.ml
  src/util/messages.ml
  src/witness/witnessUtil.ml
  tests/incremental/02-cfg-comparison/00-infinite-loop.c
  unittest/dune
  unittest/maindomaintest.ml
Labels: cleanup, type-safety

#581 Fix no offset assert
  src/analyses/base.ml
  tests/regression/02-base/73-no-eval-on-write-offset.c
Labels: bug
