Repository goblint/analyzer, pull requests merged in 2022-03, with the labels that each got.

#622 Clean up incremental comparison
  src/analyses/varEq.ml
  src/incremental/compareAST.ml
  src/incremental/compareCFG.ml
  src/incremental/compareCIL.ml
  src/util/gobList.ml
  src/witness/myARG.ml
Labels: cleanup

#625 Fix unnecessary initial double parsing in server mode with reparse
  src/framework/control.ml
  src/framework/node.ml
  src/goblint.ml
  src/incremental/updateCil.ml
  src/incremental/updateCil0.ml
  src/util/cilfacade.ml
  src/util/server.ml
Labels: bug

#616 Quote source code in messages output
  src/util/messages.ml
  src/util/options.schema.json
Labels: feature, usability

#634 Incremental TD3: optimize write-only unknown restarting
  scripts/test-incremental.sh
  src/analyses/accessAnalysis.ml
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/arinc.ml
  src/analyses/base.ml
  src/analyses/extract_arinc.ml
  src/analyses/mCP.ml
  src/analyses/mCPRegistry.ml
  src/analyses/region.ml
  src/analyses/threadAnalysis.ml
  src/analyses/threadJoins.ml
  src/cdomains/basetype.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/solvers/postSolver.ml
  src/solvers/td3.ml
  tests/incremental/11-restart/07-local-wpoint-nochange.c
  tests/incremental/11-restart/07-local-wpoint-nochange.json
  tests/incremental/11-restart/07-local-wpoint-nochange.patch
  tests/incremental/13-restart-write/01-mutex-simple.c
  tests/incremental/13-restart-write/01-mutex-simple.json
  tests/incremental/13-restart-write/01-mutex-simple.patch
  tests/incremental/13-restart-write/02-mutex-simple-wrap.c
  tests/incremental/13-restart-write/02-mutex-simple-wrap.json
  tests/incremental/13-restart-write/02-mutex-simple-wrap.patch
  tests/incremental/13-restart-write/03-mutex-simple-nochange.c
  tests/incremental/13-restart-write/03-mutex-simple-nochange.json
  tests/incremental/13-restart-write/03-mutex-simple-nochange.patch
  unittest/solver/solverTest.ml
Labels: cleanup, precision, performance

#638 Ignore exceptions from `Cilfacade.typeOf` when computing an equivalent array expression
  src/cdomains/valueDomain.ml
Labels: bug

#563 Loop Unrolling for the first `exp.unrolling-factor` Iterations
  src/util/cilfacade.ml
  src/util/options.schema.json
  tests/regression/55-loop-unrolling/01-simple-cases.c
  tests/regression/55-loop-unrolling/02-break.c
  tests/regression/55-loop-unrolling/03-break-right-place.c
  tests/regression/55-loop-unrolling/04-simple.c
  tests/regression/55-loop-unrolling/05-continue.c
  tests/regression/55-loop-unrolling/06-simple-cases-unrolled.c
  tests/regression/55-loop-unrolling/07-nested-unroll.c
Labels: feature, student-job, precision

#615 Do not allow to collect globals with duplicate identifiers in map
  src/incremental/compareCIL.ml
Labels: debugging

#640 Refine intervals with def_exc exclusion range
  src/cdomains/addressDomain.ml
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/domains/intDomainProperties.ml
  src/util/options.schema.json
  tests/incremental/00-basic/08-refine_interval_with_def_exc.c
  tests/incremental/00-basic/08-refine_interval_with_def_exc.json
  tests/incremental/00-basic/08-refine_interval_with_def_exc.patch
  tests/incremental/01-force-reanalyze/00-int.json
  unittest/cdomains/intDomainTest.ml
Labels: bug, precision

#614 Optimize CFG construction
  src/framework/cfgTools.ml
  src/framework/constraints.ml
  src/util/gobHashtbl.ml
Labels: performance

#641 Add zstd thread pool example to regression tests
  tests/regression/06-symbeq/31-zstd-thread-pool.c
  tests/regression/09-regions/38-escape_malloc.c
Labels: testing

#649 Apron: Better handling of asserts containing `LNot`
  src/cdomains/apron/apronDomain.apron.ml
  tests/regression/36-apron/01-octagon_simple.c
  tests/regression/36-apron/09-branch.c
Labels: bug, precision

#654 Make annotation in 6/22 more precise
  tests/regression/06-symbeq/22-var_eq_types.c
Labels: testing

#652 Cleanup future regression tests
  src/maingoblint.ml
  tests/regression/02-base/12-init_otherfun.c
  tests/regression/03-practical/18-no_ctx_box.c
  tests/regression/14-osek/04-cubbyhole.c
  tests/regression/14-osek/06-suffix.c
  tests/regression/14-osek/17-multicore.c
  tests/regression/29-svcomp/26-ikinds_if.c
Labels: cleanup

#666 Update README.md for installation on M1 processors
  README.md
Labels: documentation, setup

#648 Add messagesCompare for comparing json-messages results
  .gitignore
  make.sh
  src/dune
  src/messagesCompare.ml
  src/util/cilType.ml
  src/util/messageCategory.ml
  src/util/messages.ml
Labels: feature, benchmarking, debugging

#670 `exp.apron.prec-dump`: Speedup Apron dumping for Octagons, Warning in general
  src/analyses/apron/apronAnalysis.apron.ml
Labels: testing, performance

#665 Bump goblint-cil (https://github.com/goblint/cil/pull/85)
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
Labels: dependencies

#669 Add command line argument completion
  dune-project
  goblint.opam
  goblint.opam.locked
  scripts/bash-completion.sh
  src/dune
  src/maingoblint.ml
  src/util/gobConfig.ml
  src/util/options.ml
Labels: feature, usability

#662 Refactor mutex analyses
  src/analyses/apron/apronAnalysis.apron.ml
  src/analyses/apron/apronPriv.apron.ml
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/commonPriv.ml
  src/analyses/deadlock.ml
  src/analyses/locksetAnalysis.ml
  src/analyses/mayLocks.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/mutexEventsAnalysis.ml
  src/analyses/osek.ml
  src/analyses/tutorials/unitAnalysis.ml
  src/domains/events.ml
  src/domains/queries.ml
  src/util/options.schema.json
  tests/regression/02-base/06-side_effect1.c
  tests/regression/02-base/07-side_effect2.c
  tests/regression/02-base/09-ambigpointer.c
  tests/regression/02-base/10-init_allfuns.c
  tests/regression/02-base/23-malloc_globmt.c
  tests/regression/02-base/30-escape_sound.c
  tests/regression/02-base/41-calloc_globmt.c
  tests/regression/03-practical/14-call_by_pointer.c
  tests/regression/04-mutex/63-unknown_unlock_rc.c
  tests/regression/15-deadlock/19-fail_deadlock.c
  tests/regression/15-deadlock/20-ambig_deadlock.c
  tests/regression/15-deadlock/21-unknown_deadlock.c
  tests/regression/15-deadlock/22-ambig_unlock_deadlock.c
  tests/regression/15-deadlock/23-unknown_unlock_deadlock.c
  tests/regression/15-deadlock/24-malloc_unlock_deadlock.c
  tests/regression/15-deadlock/25-malloc_deadlock.c
  tests/regression/15-deadlock/26-unknown_deadlock2.c
  tests/regression/15-deadlock/27-self_deadlock.c
Labels: cleanup, unsound, precision
