Repository goblint/analyzer, pull requests merged in 2023-06, with the labels that each got.

#66 Fix/region
  src/cdomains/regionDomain.ml
  src/domains/partitionDomain.ml
  tests/regression/09-regions/39-evilcollapse_rc_wpoint.c
Labels: bug, unsound

#1048 String Literals Domain
  src/analyses/base.ml
  src/analyses/libraryDesc.ml
  src/analyses/libraryFunctions.ml
  src/cdomains/addressDomain.ml
  src/cdomains/lval.ml
  tests/regression/73-strings/01-string_literals.c
  tests/regression/73-strings/02-string_literals_with_null.c
  tests/regression/73-strings/03-string_basics.c
Labels: feature, student-job, precision

#1071 Ignore accesses to variables with `__thread` keyword
  src/domains/access.ml
  tests/regression/04-mutex/82-thread-local-storage.c
Labels: precision, benchmarking

#1068 Remove polymorphic variants for VD.Compound
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/cdomains/baseDomain.ml
  src/cdomains/valueDomain.ml
Labels: cleanup

#1065 Also allow `threadid` to recover from multi-threaded mode
  src/analyses/threadId.ml
  src/analyses/threadJoins.ml
  src/cdomains/threadIdDomain.ml
  src/domains/queries.ml
  tests/regression/40-threadid/04-recover.c
  tests/regression/58-base-mm-tid/25-phases-intricate-sound.c
  tests/regression/58-base-mm-tid/32-phases-sound-tid.c
  tests/regression/58-base-mm-tid/33-phases-sound-tid-other.c
Labels: precision

#1067 Refactor offsets, lvals and addresses
  src/analyses/accessAnalysis.ml
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/analyses/commonPriv.ml
  src/analyses/condVars.ml
  src/analyses/extractPthread.ml
  src/analyses/fileUse.ml
  src/analyses/malloc_null.ml
  src/analyses/mayLocks.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/mutexEventsAnalysis.ml
  src/analyses/mutexTypeAnalysis.ml
  src/analyses/pthreadSignals.ml
  src/analyses/raceAnalysis.ml
  src/analyses/region.ml
  src/analyses/spec.ml
  src/analyses/symbLocks.ml
  src/analyses/taintPartialContexts.ml
  src/analyses/threadEscape.ml
  src/analyses/uninit.ml
  src/analyses/varEq.ml
  src/cdomains/addressDomain.ml
  src/cdomains/addressDomain.mli
  src/cdomains/addressDomain_intf.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/cilLval.ml
  src/cdomains/fileDomain.ml
  src/cdomains/lockDomain.ml
  src/cdomains/lval.ml
  src/cdomains/musteqDomain.ml
  src/cdomains/mval.ml
  src/cdomains/mval.mli
  src/cdomains/mvalMapDomain.ml
  src/cdomains/mval_intf.ml
  src/cdomains/offset.ml
  src/cdomains/offset.mli
  src/cdomains/offset_intf.ml
  src/cdomains/preValueDomain.ml
  src/cdomains/regionDomain.ml
  src/cdomains/specDomain.ml
  src/cdomains/symbLocksDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/access.ml
  src/domains/invariant.ml
  src/domains/queries.ml
  src/domains/valueDomainQueries.ml
  src/framework/cfgTools.ml
  src/goblint_lib.ml
  src/transform/evalAssert.ml
  src/util/cilfacade.ml
  src/witness/yamlWitness.ml
  tests/regression/05-lval_ls/19-idxunknown_unlock_precise.c
  unittest/cdomains/lvalTest.ml
Labels: cleanup

#1080 Generate code coverage reports with GitHub Actions workflows
  .github/workflows/coverage.yml
  .gitignore
  README.md
  docs/developer-guide/testing.md
  make.sh
  src/cdomains/intDomain.ml
  src/dune
  src/witness/yamlWitness.ml
Labels: testing, setup, github_actions

#1073 Track multiplicities for mustLocks
  src/analyses/mutexAnalysis.ml
  src/analyses/mutexTypeAnalysis.ml
  tests/regression/71-doublelocking/14-rec-dyn-no-race.c
  tests/regression/71-doublelocking/15-rec-dyn-nested.c
  tests/regression/71-doublelocking/16-rec-dyn-no-path-sense.c
Labels: feature, precision

#1083 Ignore indentation for blank lines suggested by ocp-indent
  .git-blame-ignore-revs
  scripts/hooks/pre-commit
  src/analyses/baseInvariant.ml
Labels: setup

#1087 Document regression test annotations fully
  docs/developer-guide/testing.md
  scripts/update_suite.rb
  tests/regression/00-sanity/02-minimal.c
  tests/regression/00-sanity/03-no_succ.c
  tests/regression/00-sanity/05-inf_loop.c
  tests/regression/00-sanity/06-term1.c
  tests/regression/00-sanity/07-term2.c
  tests/regression/00-sanity/08-asm_nop.c
  tests/regression/00-sanity/10-loop_label.c
  tests/regression/03-practical/05-deslash.c
  tests/regression/03-practical/10-big_init.c
  tests/regression/03-practical/16-union_index.c
Labels: testing, documentation

#1077 ThreadCreate analysis to improve partially context-sensitive threadID analysis
  src/analyses/threadId.ml
  src/util/options.schema.json
  tests/regression/40-threadid/05-nc-simple.c
  tests/regression/40-threadid/06-nc-deep.c
  tests/regression/40-threadid/07-nc-createEdges.c
  tests/regression/40-threadid/08-nc-fromThread.c
Labels: feature, student-job, precision
