Repository goblint/analyzer, pull requests merged in 2023-08, with the labels that each got.

#1079 Convert library functions to new specifications
  src/analyses/accessAnalysis.ml
  src/analyses/libraryFunctions.ml
Labels: cleanup, precision, benchmarking

#1041 Analysis tracking equality between calls to math library functions to improve invariant
  src/analyses/baseInvariant.ml
  src/analyses/libraryDesc.ml
  src/analyses/tmpSpecial.ml
  src/cdomains/floatDomain.ml
  src/cdomains/floatDomain.mli
  src/domains/queries.ml
  tests/regression/57-floats/19-library-invariant.c
  tests/regression/57-floats/20-library-invariant-invalidate.c
  tests/regression/57-floats/21-library-invariant-ceil-floor.c
Labels: student-job, precision

#1125 Fix `Queries.BlobSize`
  src/analyses/base.ml
Labels: bug

#1135 Add support for `quick_exit`
  src/analyses/libraryFunctions.ml
Labels: feature, student-job

#1082 Detect calls of thread-unsafe functions as races
  src/analyses/libraryFunctions.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/raceAnalysis.ml
  src/domains/accessKind.ml
  src/util/options.schema.json
  tests/regression/04-mutex/90-thread-unsafe_fun_rc.c
  tests/regression/04-mutex/91-thread-unsafe_fun_nr.c
Labels: feature

#1127 Memory Leak Analysis
  src/analyses/memLeak.ml
  src/util/messageCategory.ml
  tests/regression/76-memleak/01-simple-no-mem-leak.c
  tests/regression/76-memleak/02-simple-mem-leak.c
  tests/regression/76-memleak/03-simple-exit-mem-leak.c
  tests/regression/76-memleak/04-simple-abort-mem-leak.c
  tests/regression/76-memleak/05-simple-assert-no-mem-leak.c
  tests/regression/76-memleak/06-simple-assert-mem-leak.c
  tests/regression/76-memleak/07-simple-quick-exit-mem-leak.c
Labels: feature, student-job, sv-comp

#1139 Detect memory deallocation at offset from memory start
  src/analyses/base.ml
  tests/regression/75-invalid_dealloc/05-free-at-offset.c
  tests/regression/75-invalid_dealloc/06-realloc-at-offset.c
  tests/regression/75-invalid_dealloc/07-free-at-struct-offset.c
  tests/regression/75-invalid_dealloc/08-realloc-at-struct-offset.c
Labels: feature, student-job, sv-comp
