Repository goblint/analyzer, pull requests merged in 2023-10, with the labels that each got.

#1179 Support stack-allocating functions when allocating heap vars
  src/analyses/base.ml
  src/analyses/libraryDesc.ml
  src/analyses/libraryFunctions.ml
  src/analyses/mallocFresh.ml
  src/analyses/memLeak.ml
  src/analyses/useAfterFree.ml
  src/analyses/wrapperFunctionAnalysis.ml
  src/domains/queries.ml
  tests/regression/74-use_after_free/14-alloca-uaf.c
  tests/regression/75-invalid_dealloc/09-juliet-invalid-dealloc-alloca.c
Labels: precision

#1197 Add out-of-bounds check for `memset` and `memcpy`
  src/analyses/base.ml
  src/analyses/libraryDesc.ml
  src/analyses/libraryFunctions.ml
  src/analyses/memOutOfBounds.ml
  tests/regression/77-mem-oob/06-memset-oob.c
  tests/regression/77-mem-oob/07-memcpy-oob.c
  tests/regression/77-mem-oob/08-memset-memcpy-array.c
  tests/regression/77-mem-oob/09-memset-memcpy-addr-offs.c
Labels: student-job, precision

#1200 Port ~50 library specifications to the new system
  src/analyses/libraryDesc.ml
  src/analyses/libraryFunctions.ml
  tests/regression/28-race_reach/01-simple_racing.c
  tests/regression/28-race_reach/02-simple_racefree.c
  tests/regression/28-race_reach/03-munge_racing.c
  tests/regression/28-race_reach/04-munge_racefree.c
  tests/regression/28-race_reach/05-lockfuns_racefree.c
  tests/regression/28-race_reach/06-cond_racing1.c
  tests/regression/28-race_reach/07-cond_racing2.c
  tests/regression/28-race_reach/08-cond_racefree.c
  tests/regression/28-race_reach/09-ptrmunge_racing.c
  tests/regression/28-race_reach/10-ptrmunge_racefree.c
  tests/regression/28-race_reach/11-ptr_racing.c
  tests/regression/28-race_reach/12-ptr_racefree.c
  tests/regression/28-race_reach/19-callback_racing.c
  tests/regression/28-race_reach/20-callback_racefree.c
  tests/regression/28-race_reach/21-deref_read_racing.c
  tests/regression/28-race_reach/22-deref_read_racefree.c
  tests/regression/28-race_reach/23-sound_unlock_racing.c
  tests/regression/28-race_reach/24-sound_lock_racing.c
  tests/regression/28-race_reach/27-funptr_racing.c
  tests/regression/28-race_reach/28-funptr_racefree.c
  tests/regression/28-race_reach/36-indirect_racefree.c
  tests/regression/28-race_reach/37-indirect_racing.c
  tests/regression/28-race_reach/40-trylock_racing.c
  tests/regression/28-race_reach/41-trylock_racefree.c
  tests/regression/28-race_reach/42-trylock2_racefree.c
  tests/regression/28-race_reach/45-escape_racing.c
  tests/regression/28-race_reach/46-escape_racefree.c
  tests/regression/28-race_reach/51-mutexptr_racefree.c
  tests/regression/28-race_reach/60-invariant_racefree.c
  tests/regression/28-race_reach/61-invariant_racing.c
  tests/regression/28-race_reach/70-funloop_racefree.c
  tests/regression/28-race_reach/71-funloop_racing.c
  tests/regression/28-race_reach/72-funloop_hard_racing.c
  tests/regression/28-race_reach/73-funloop_hard_racefree.c
  tests/regression/28-race_reach/74-tricky_address1_racefree.c
  tests/regression/28-race_reach/75-tricky_address2_racefree.c
  tests/regression/28-race_reach/76-tricky_address3_racefree.c
  tests/regression/28-race_reach/77-tricky_address4_racing.c
  tests/regression/28-race_reach/78-equ_racing.c
  tests/regression/28-race_reach/79-equ_racefree.c
  tests/regression/28-race_reach/81-list_racing.c
  tests/regression/28-race_reach/82-list_racefree.c
  tests/regression/28-race_reach/83-list2_racing1.c
  tests/regression/28-race_reach/84-list2_racing2.c
  tests/regression/28-race_reach/85-list2_racefree.c
  tests/regression/28-race_reach/86-lists_racing.c
  tests/regression/28-race_reach/87-lists_racefree.c
  tests/regression/28-race_reach/90-arrayloop2_racing.c
  tests/regression/28-race_reach/91-arrayloop2_racefree.c
  tests/regression/28-race_reach/92-evilcollapse_racing.c
  tests/regression/28-race_reach/93-evilcollapse_racefree.c
  tests/regression/28-race_reach/94-alloc_region_racing.c
  tests/regression/36-apron/15-globals-st.c
Labels: cleanup

#1202 Remove spurious `long double` constant warning
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/analyses/base.ml
  src/util/cilfacade.ml
  tests/regression/00-sanity/37-long-double.c
  tests/regression/00-sanity/37-long-double.t
Labels: cleanup

#1203 Some ~15 more library functions
  src/analyses/libraryFunctions.ml
Labels: cleanup

#1213 Check duplicate library functions
  src/analyses/libraryFunctions.ml
Labels: cleanup

#1201 SV-COMP "Memory Safety" benchmark additions
  src/analyses/base.ml
  src/analyses/memLeak.ml
  src/analyses/memOutOfBounds.ml
  src/analyses/useAfterFree.ml
  src/autoTune.ml
  src/cdomains/arrayDomain.ml
  src/common/framework/analysisState.ml
  src/common/util/cilfacade.ml
  src/common/util/options.schema.json
  src/maingoblint.ml
  src/util/analysisStateUtil.ml
  src/witness/svcomp.ml
  src/witness/svcompSpec.ml
  src/witness/witness.ml
  tests/regression/74-invalid_deref/01-oob-heap-simple.c
  tests/regression/74-invalid_deref/02-conditional-uaf.c
  tests/regression/74-invalid_deref/03-nested-ptr-uaf.c
  tests/regression/74-invalid_deref/04-function-call-uaf.c
  tests/regression/74-invalid_deref/05-oob-implicit-deref.c
  tests/regression/74-invalid_deref/06-memset-oob.c
  tests/regression/74-invalid_deref/07-memcpy-oob.c
  tests/regression/74-invalid_deref/08-memset-memcpy-array.c
  tests/regression/74-invalid_deref/09-juliet-uaf.c
  tests/regression/74-invalid_deref/10-oob-two-loops.c
  tests/regression/74-invalid_deref/11-address-offset-oob.c
  tests/regression/74-invalid_deref/12-memcpy-oob-src.c
  tests/regression/74-invalid_deref/13-mem-oob-packed-struct.c
  tests/regression/74-invalid_deref/14-alloca-uaf.c
  tests/regression/74-invalid_deref/15-juliet-uaf-global-var.c
  tests/regression/74-invalid_deref/16-uaf-packed-struct.c
  tests/regression/74-invalid_deref/17-scopes-no-static.c
  tests/regression/74-invalid_deref/18-simple-uaf.c
  tests/regression/74-invalid_deref/19-oob-stack-simple.c
  tests/regression/74-invalid_deref/20-scopes-global-var.c
  tests/regression/74-invalid_deref/21-oob-loop.c
  tests/regression/74-invalid_deref/22-scopes-static.c
  tests/regression/74-invalid_deref/23-oob-deref-after-ptr-arith.c
  tests/regression/74-invalid_deref/24-uaf-free-in-wrapper-fun.c
  tests/regression/74-invalid_deref/25-uaf-struct.c
  tests/regression/74-invalid_deref/26-memset-memcpy-addr-offs.c
  tests/regression/74-invalid_deref/27-wrapper-funs-uaf.c
  tests/regression/74-invalid_deref/28-multi-threaded-uaf.c
  tests/regression/74-invalid_deref/29-multi-threaded-uaf-with-joined-thread.c
  tests/regression/75-invalid_free/01-invalid-dealloc-simple.c
  tests/regression/75-invalid_free/02-invalid-dealloc-struct.c
  tests/regression/75-invalid_free/03-invalid-dealloc-array.c
  tests/regression/75-invalid_free/04-invalid-realloc.c
  tests/regression/75-invalid_free/05-free-at-offset.c
  tests/regression/75-invalid_free/06-realloc-at-offset.c
  tests/regression/75-invalid_free/07-free-at-struct-offset.c
  tests/regression/75-invalid_free/08-itc-no-double-free.c
  tests/regression/75-invalid_free/09-juliet-invalid-dealloc-alloca.c
  tests/regression/75-invalid_free/10-invalid-dealloc-union.c
  tests/regression/75-invalid_free/11-itc-double-free.c
  tests/regression/75-invalid_free/12-realloc-at-struct-offset.c
  tests/regression/75-invalid_free/13-juliet-double-free.c
  tests/sv-comp/valid-memcleanup.prp
Labels: feature, student-job, sv-comp, benchmarking

#1210 Fix longjmp crash on Uninitialized
  src/analyses/base.ml
  src/framework/constraints.ml
  tests/regression/68-longjmp/56-longjmp-top.c
Labels: bug, benchmarking

#1186 No shortcut for `narrow` and `meet` in HConsed when int refinement is active
  src/common/domains/lattice.ml
  tests/regression/38-int-refinements/06-narrow.c
Labels: bug

#1212 Add missing library functions for large Concrat benchmarks
  src/analyses/libraryFunctions.ml
Labels: precision, benchmarking
