Repository goblint/analyzer, pull requests merged in 2023-04, with the labels that each got.

#1027 Exclude pruned witness lifter prevs from ARG construction
  src/witness/argTools.ml
Labels: bug, debugging

#1030 Refactor to Remove Dependency of `ValueDomain` on `Queries`
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/arrayDomain.mli
  src/cdomains/valueDomain.ml
  src/domains/queries.ml
  src/domains/valueDomainQueries.ml
Labels: cleanup

#1028 Add option `lib.activated`
  conf/zstd-race.json
  src/analyses/libraryFunctions.ml
  src/analyses/libraryFunctions.mli
  src/maingoblint.ml
  src/util/options.schema.json
  src/util/server.ml
  tests/regression/03-practical/25-zstd-customMem.c
  tests/regression/06-symbeq/31-zstd-thread-pool.c
  tests/regression/06-symbeq/35-zstd-thread-pool-multi.c
  tests/regression/06-symbeq/36-zstd-thread-pool-add.c
Labels: feature

#1032 Make address semantic equality more precise for 0-index
  src/analyses/base.ml
  src/cdomains/lval.ml
  tests/regression/02-base/91-ad-meet.c
  tests/regression/69-addresses/03-issue-564.c
Labels: precision

#995 Skip preprocessing for `.i` files and add option `pre.enabled` to always skip preprocessor
  conf/svcomp.json
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/maingoblint.ml
  src/util/options.schema.json
Labels: feature, performance, preprocessing

#1031 Remove unnecessary lval domain special cases
  src/analyses/base.ml
  src/cdomains/lval.ml
  unittest/cdomains/lvalTest.ml
Labels: cleanup, bug
