Repository goblint/analyzer, pull requests merged in 2023-05, with the labels that each got.

#1036 Fix missing dead code warning from strictly dead loop body
  src/framework/constraints.ml
  tests/regression/00-sanity/36-strict-loop-dead.c
  tests/regression/00-sanity/36-strict-loop-dead.t
Labels: bug, precision

#979 Dead Code Elimination Transformation
  src/framework/cfgTools.ml
  src/framework/control.ml
  src/framework/myCFG.ml
  src/incremental/compareCIL.ml
  src/maingoblint.ml
  src/transform/deadCode.ml
  src/transform/evalAssert.ml
  src/transform/expressionEvaluation.ml
  src/transform/transform.ml
  src/util/goblintutil.ml
  src/util/options.schema.json
  tests/regression/70-transform/01-empty.c
  tests/regression/70-transform/01-ordering.t
  tests/regression/70-transform/02-deadcode.c
  tests/regression/70-transform/02-deadcode.t
  tests/regression/70-transform/03-deadcode-globals.c
  tests/regression/70-transform/03-deadcode-globals.t
  tests/regression/70-transform/04-unchecked-condition.c
  tests/regression/70-transform/04-unchecked-condition.t
  tests/regression/70-transform/dune
  tests/regression/70-transform/transform.sh
Labels: feature, student-job, debugging

#1046 Make privatizations sound in presence of analyses that can recover from multi-threaded mode
  src/analyses/accessAnalysis.ml
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/apron/relationPriv.apron.ml
  src/analyses/base.ml
  src/analyses/commonPriv.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/raceAnalysis.ml
  src/analyses/threadAnalysis.ml
  src/analyses/threadEscape.ml
  src/analyses/threadFlag.ml
  src/analyses/varEq.ml
  src/domains/queries.ml
  tests/regression/58-base-mm-tid/24-phases-sound.c
Labels: bug, unsound

#1045 Witness invariants for arrays and principled handling of unknown indices
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/analyses/malloc_null.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/region.ml
  src/analyses/uninit.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/arrayDomain.mli
  src/cdomains/lval.ml
  src/cdomains/valueDomain.ml
  src/framework/cfgTools.ml
  src/framework/myCFG.ml
  src/util/options.schema.json
  tests/regression/56-witness/44-base-unassume-array.c
  tests/regression/56-witness/44-base-unassume-array.yml
Labels: cleanup, feature, sv-comp

#1051 Fix `--html` when Goblint is run from elsewhere
  src/maingoblint.ml
  src/util/options.schema.json
Labels: cleanup, usability

#1053 Add documentation about Goblint's transfer functions
  docs/developer-guide/firstanalysis.md
  src/framework/analyses.ml
Labels: documentation

#1042 Replace `should_join` with path representative
  src/analyses/activeSetjmp.ml
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/apron/relationPriv.apron.ml
  src/analyses/expsplit.ml
  src/analyses/mCP.ml
  src/analyses/mCPRegistry.ml
  src/analyses/malloc_null.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/stackTrace.ml
  src/analyses/threadAnalysis.ml
  src/analyses/threadFlag.ml
  src/analyses/unassumeAnalysis.ml
  src/analyses/uninit.ml
  src/domains/disjointDomain.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/util/wideningTokens.ml
  src/witness/observerAnalysis.ml
  src/witness/witnessConstraints.ml
Labels: performance

#839 MayLock Analysis & Sanity Checks of Mutex Usage & Analysis of Mutex Types
  src/analyses/base.ml
  src/analyses/libraryDesc.ml
  src/analyses/libraryFunctions.ml
  src/analyses/mayLocks.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/mutexTypeAnalysis.ml
  src/analyses/threadAnalysis.ml
  src/autoTune.ml
  src/cdomains/lockDomain.ml
  src/cdomains/lval.ml
  src/cdomains/mutexAttrDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/queries.ml
  src/util/messageCategory.ml
  tests/regression/71-doublelocking/01-simple.c
  tests/regression/71-doublelocking/02-unknown.c
  tests/regression/71-doublelocking/03-thread-exit-with-mutex.c
  tests/regression/71-doublelocking/04-unlock.c
  tests/regression/71-doublelocking/05-rec.c
  tests/regression/71-doublelocking/06-rec-dyn.c
  tests/regression/71-doublelocking/07-rec-dyn-osx.c
  tests/regression/71-doublelocking/08-other-type.c
  tests/regression/71-doublelocking/09-other-dyn.c
  tests/regression/71-doublelocking/10-thread-exit-recursive.c
  tests/regression/71-doublelocking/11-rec-dyn-branch.c
  tests/regression/71-doublelocking/12-rec-dyn-struct.c
  tests/regression/71-doublelocking/13-rec-struct.c
Labels: feature

#1021 Thread Wrappers
  src/analyses/mallocWrapperAnalysis.ml
  src/analyses/threadId.ml
  src/analyses/wrapperFunctionAnalysis.ml
  src/analyses/wrapperFunctionAnalysis0.ml
  src/cdomains/threadIdDomain.ml
  src/domains/lattice.ml
  src/domains/queries.ml
  src/util/options.schema.json
  tests/regression/04-mutex/01-simple_rc.t
  tests/regression/72-thread_create_wrapper/01-wrapper.c
  tests/regression/72-thread_create_wrapper/02-unique-counter.c
  tests/regression/72-thread_create_wrapper/03-wrapper-unique-counter.c
  tests/regression/72-thread_create_wrapper/04-unique-counter-id-count-0.c
  tests/regression/72-thread_create_wrapper/05-wrapper-unique-counter-id-count-0.c
Labels: feature, student-job
