Repository goblint/analyzer, pull requests merged in 2023-02, with the labels that each got.

#953 Warnings and Dead Code Handling for `noreturn`
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/analyses/base.ml
  src/framework/cfgTools.ml
  src/util/cilfacade.ml
  src/util/messageCategory.ml
  src/util/options.schema.json
  tests/regression/64-noreturn/00-noreturn-deadcode-off.c
  tests/regression/64-noreturn/01-noreturn-deadcode-on.c
Labels: feature, student-job, c11

#969 Value Domain: Rm code duplication caused by "smart" operations
  src/cdomains/valueDomain.ml
Labels: cleanup

#975 Seq-optimization clean version
  src/analyses/base.ml
Labels: student-job, performance

#982 Improve `threadJoins` when it is used context-insensitively
  src/analyses/threadJoins.ml
  tests/regression/51-threadjoins/06-ctxinsens.c
Labels: precision, performance

#912 Enable constant loop unrolling for small files
  src/util/cilCfg.ml
  src/util/loopUnrolling.ml
  src/util/options.schema.json
Labels: sv-comp, precision

#984 Handle escaping in `varEq` analysis
  src/analyses/varEq.ml
  tests/regression/06-symbeq/41-vareq_global.c
  tests/regression/06-symbeq/42-vareq_escape.c
Labels: bug, unsound

#987 Autotuner: Do not activate Apron for `val` variables from Goblint header for `__VERIFIER_nondet_*`
  lib/sv-comp/stub/src/sv-comp.c
  src/autoTune.ml
  tests/regression/46-apron2/30-autotune-stub.c
Labels: cleanup, sv-comp

#985 Support for machines where `float128` is not the same size as `long double`
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/analyses/base.ml
  src/cdomains/floatDomain.ml
  src/cdomains/valueDomain.ml
  src/util/cilfacade.ml
Labels: feature

#986 Short-circuiting operations inside `HConsed`
  src/domains/lattice.ml
Labels: performance

#956 Optimization: monomorphization
  src/util/cilType.ml
Labels: type-safety, student-job, performance

#952 Taint analysis to improve the precision loss of partial contexts
  src/analyses/abortUnless.ml
  src/analyses/accessAnalysis.ml
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/assert.ml
  src/analyses/base.ml
  src/analyses/condVars.ml
  src/analyses/expRelation.ml
  src/analyses/expsplit.ml
  src/analyses/extractPthread.ml
  src/analyses/fileUse.ml
  src/analyses/mCP.ml
  src/analyses/mallocFresh.ml
  src/analyses/mallocWrapperAnalysis.ml
  src/analyses/malloc_null.ml
  src/analyses/pthreadSignals.ml
  src/analyses/region.ml
  src/analyses/spec.ml
  src/analyses/stackTrace.ml
  src/analyses/symbLocks.ml
  src/analyses/taintPartialContexts.ml
  src/analyses/termination.ml
  src/analyses/threadAnalysis.ml
  src/analyses/threadEscape.ml
  src/analyses/threadFlag.ml
  src/analyses/threadId.ml
  src/analyses/threadJoins.ml
  src/analyses/threadReturn.ml
  src/analyses/tutorials/constants.ml
  src/analyses/tutorials/taint.ml
  src/analyses/tutorials/unitAnalysis.ml
  src/analyses/unassumeAnalysis.ml
  src/analyses/uninit.ml
  src/analyses/varEq.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/arrayDomain.mli
  src/domains/queries.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/util/wideningTokens.ml
  src/witness/observerAnalysis.ml
  src/witness/witnessConstraints.ml
  tests/regression/06-symbeq/41-var_eq_multithread.c
  tests/regression/65-taint/01-simple.c
  tests/regression/65-taint/02-invalidate.c
  tests/regression/65-taint/03-lval.c
  tests/regression/65-taint/04-multithread.c
  tests/regression/65-taint/05-partArray.c
  tests/regression/65-taint/06-condVars.c
  tests/regression/65-taint/07-varEq.c
  tests/regression/65-taint/08-apron.c
  tests/regression/65-taint/09-multipleVar.c
  tests/regression/65-taint/10-callToMain.c
  tests/regression/65-taint/11-svcomp-cstrcmp.c
Labels: student-job, precision

#990 Fix various server mode crashes
  src/framework/control.ml
  src/framework/node.ml
  src/maingoblint.ml
  src/util/cilfacade.ml
  src/util/server.ml
Labels: bug

#992 Use `Z` instead of `Big_int_Z` and `Cilint`
  .semgrep/cilint.yml
  .semgrep/zarith.yml
  bench/zarith/benchZarith.ml
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/analyses/expRelation.ml
  src/analyses/fileUse.ml
  src/analyses/spec.ml
  src/analyses/tutorials/signs.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/floatDomain.ml
  src/cdomains/floatOps/floatOps.ml
  src/cdomains/floatOps/floatOps.mli
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
  src/cdomains/symbLocksDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/myCheck.ml
  src/incremental/compareAST.ml
  src/util/intOps.ml
  src/util/loopUnrolling.ml
  src/util/wideningThresholds.ml
  unittest/cdomains/floatDomainTest.ml
  unittest/cdomains/lvalTest.ml
  unittest/mainTest.ml
  unittest/util/intOpsTest.ml
Labels: cleanup

#991 Fix timing root accumulating in server mode
  src/util/timing/goblint_timing.ml
Labels: bug, benchmarking, debugging

#1000 Handle pseudo return nodes in `Node.of_id` and improve their location
  src/framework/cfgTools.ml
  src/framework/control.ml
  src/util/cilfacade.ml
Labels: bug, debugging
