Repository goblint/analyzer, pull requests merged in 2023-11, with the labels that each got.

#1226 Refactor GraphML witness options
  conf/ldv-races.json
  conf/svcomp-yaml.json
  conf/svcomp.json
  conf/svcomp21.json
  conf/svcomp22-intervals-novareq-affeq-apron.json
  conf/svcomp22-intervals-novareq-affeq-native.json
  conf/svcomp22-intervals-novareq-octagon-apron.json
  conf/svcomp22-intervals-novareq-polyhedra-apron.json
  conf/svcomp22.json
  conf/svcomp23.json
  src/common/util/options.schema.json
  src/framework/control.ml
  src/maingoblint.ml
  src/witness/myARG.ml
  src/witness/witness.ml
  src/witness/yamlWitness.ml
  sv-comp/sv-comp-run-no-overflow.py
  sv-comp/sv-comp-run.py
  tests/sv-comp/observer/path_nofun_true-unreach-call.c
Labels: cleanup, sv-comp

#1230 `threadAnalysis`: Only add to set of must-joined threads if argument to `pthread_join` evaluates to a singleton
  src/analyses/threadAnalysis.ml
  tests/regression/10-synch/28-join-array.c
Labels: bug, unsound, sv-comp

#1187 Spawn threads created from unknown functions as non-unique
  src/analyses/abortUnless.ml
  src/analyses/accessAnalysis.ml
  src/analyses/activeLongjmp.ml
  src/analyses/activeSetjmp.ml
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/commonPriv.ml
  src/analyses/condVars.ml
  src/analyses/expsplit.ml
  src/analyses/extractPthread.ml
  src/analyses/fileUse.ml
  src/analyses/locksetAnalysis.ml
  src/analyses/mCP.ml
  src/analyses/mallocFresh.ml
  src/analyses/malloc_null.ml
  src/analyses/modifiedSinceLongjmp.ml
  src/analyses/mutexTypeAnalysis.ml
  src/analyses/poisonVariables.ml
  src/analyses/pthreadSignals.ml
  src/analyses/region.ml
  src/analyses/spec.ml
  src/analyses/stackTrace.ml
  src/analyses/symbLocks.ml
  src/analyses/taintPartialContexts.ml
  src/analyses/termination.ml
  src/analyses/threadAnalysis.ml
  src/analyses/threadEscape.ml
  src/analyses/threadFlag.ml
  src/analyses/threadId.ml
  src/analyses/threadJoins.ml
  src/analyses/threadReturn.ml
  src/analyses/tmpSpecial.ml
  src/analyses/tutorials/taint.ml
  src/analyses/tutorials/unitAnalysis.ml
  src/analyses/uninit.ml
  src/analyses/useAfterFree.ml
  src/analyses/varEq.ml
  src/analyses/vla.ml
  src/analyses/wrapperFunctionAnalysis.ml
  src/cdomains/threadIdDomain.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/framework/resultQuery.ml
  src/util/wideningTokens.ml
  src/witness/observerAnalysis.ml
  src/witness/witnessConstraints.ml
  tests/regression/40-threadid/09-multiple.c
  tests/regression/40-threadid/10-multiple-thread.c
  tests/regression/40-threadid/11-multiple-unique-counter.c
Labels: cleanup, feature, unsound

#1242 Add some library functions from SV-COMP
  src/analyses/libraryFunctions.ml
Labels: sv-comp, precision

#1234 Experiment with path- and context-sensitivity for memLeak analysis
  src/analyses/memLeak.ml
  src/autoTune.ml
  src/common/util/options.schema.json
Labels: sv-comp, precision

#1247 Fix region escaping in per-thread-array-init-race
  src/analyses/region.ml
  src/cdomains/regionDomain.ml
  tests/regression/09-regions/38-escape_malloc.c
  tests/regression/09-regions/41-per-thread-array-init-race.c
Labels: bug, unsound, sv-comp

#1252 Be more precise for `<<` of Intervals
  src/cdomains/intDomain.ml
  tests/regression/39-signed-overflows/06-shiftleft.c
Labels: sv-comp, precision

#1254 Handle `sqrt` & Some Bodged Solution for computing through `abs`
  conf/svcomp.json
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/analyses/libraryDesc.ml
  src/analyses/libraryFunctions.ml
  src/autoTune.ml
  src/cdomains/floatDomain.ml
  src/cdomains/floatDomain.mli
  src/cdomains/floatOps/floatOps.ml
  src/cdomains/floatOps/floatOps.mli
  src/cdomains/floatOps/stubs.c
  src/common/util/options.schema.json
  tests/regression/39-signed-overflows/06-abs.c
  tests/regression/39-signed-overflows/07-abs-sqrt.c
  tests/regression/39-signed-overflows/08-labs.c
  tests/regression/39-signed-overflows/09-labs-sqrt.c
  tests/regression/39-signed-overflows/10-shiftleft.c
Labels: feature, sv-comp, precision

#1262 Fix `BlobSize` for calloc
  src/analyses/base.ml
  src/analyses/memOutOfBounds.ml
  tests/regression/74-invalid_deref/30-calloc.c
Labels: sv-comp, precision

#1270 Fix ordering of queries by deduplicating indices.
  src/domains/queries.ml
Labels: bug

#1271 Fix `Not_found` exception in autotuner with congruences and termination.
  src/autoTune.ml
  tests/regression/78-termination/51-modulo.c
Labels: bug

#1241 Account for allocated heap memory which is unreachable from globals
  src/analyses/memLeak.ml
  tests/regression/76-memleak/08-unreachable-mem.c
  tests/regression/76-memleak/09-unreachable-with-local-var.c
  tests/regression/76-memleak/10-global-struct-no-ptr.c
  tests/regression/76-memleak/11-global-struct-ptr.c
  tests/regression/76-memleak/12-global-nested-struct-ptr.c
  tests/regression/76-memleak/13-global-nested-struct-ptr-reachable.c
  tests/regression/76-memleak/14-global-nested-struct-non-ptr-reachable.c
Labels: sv-comp, precision

#1246 Improve multi-threaded `valid-memcleanup`
  src/analyses/memLeak.ml
  src/analyses/threadAnalysis.ml
  src/common/util/options.schema.json
  tests/regression/76-memleak/20-invalid-memcleanup-multi-threaded.c
  tests/regression/76-memleak/21-invalid-memcleanup-multi-threaded-abort.c
  tests/regression/76-memleak/22-leak-later.c
  tests/regression/76-memleak/23-leak-later-nested.c
  tests/regression/76-memleak/24-multi-threaded-assert.c
  tests/regression/76-memleak/25-assert-unknown-multi-threaded.c
  tests/regression/76-memleak/26-invalid-memcleanup-multi-threaded-betterpiv.c
  tests/regression/76-memleak/27-mem-leak-not-joined-thread.c
  tests/regression/76-memleak/28-no-mem-leak-thread-exit-main.c
  tests/regression/76-memleak/29-mem-leak-thread-return.c
  tests/regression/76-memleak/30-mem-leak-thread-exit.c
  tests/regression/76-memleak/31-no-mem-leak-return.c
Labels: feature, student-job, sv-comp, precision

#1264 Do not invalidate special function lvals recursively
  src/analyses/base.ml
  tests/regression/00-sanity/51-base-special-lval.c
  tests/regression/04-mutex/49-type-invariants.t
  tests/regression/04-mutex/77-type-nested-fields.t
  tests/regression/04-mutex/79-type-nested-fields-deep1.t
  tests/regression/04-mutex/80-type-nested-fields-deep2.t
  tests/regression/04-mutex/90-distribute-fields-type-1.t
  tests/regression/04-mutex/91-distribute-fields-type-2.t
  tests/regression/04-mutex/92-distribute-fields-type-deep.t
  tests/regression/04-mutex/93-distribute-fields-type-global.t
Labels: bug, usability, precision

#1208 Add `ana.base.strings.domain` option and unit string domain
  conf/examples/very-precise.json
  src/cdomains/addressDomain.ml
  src/cdomains/addressDomain_intf.ml
  src/cdomains/stringDomain.ml
  src/cdomains/stringDomain.mli
  src/common/util/options.schema.json
  src/goblint_lib.ml
  src/util/server.ml
  tests/regression/02-base/88-string-ptrs-limited.c
  tests/regression/02-base/89-string-ptrs-not-limited.c
  tests/regression/73-strings/01-string_literals.c
  tests/regression/73-strings/02-string_literals_with_null.c
  tests/regression/73-strings/03-string_basics.c
  tests/regression/73-strings/05-string-unit-domain.c
Labels: cleanup, feature, performance, benchmarking

#1265 Test for `mutex-meet-tid` for ValidDeref & Move `Afterconfig.run` to ensure privatizations can potentially be auto-tuned
  src/autoTune.ml
  src/maingoblint.ml
  tests/regression/74-invalid_deref/31-multithreaded.c
Labels: sv-comp, precision

#1274 Generalize and clean up `abs` invariant in base analysis
  src/analyses/baseInvariant.ml
  tests/regression/39-signed-overflows/06-abs.c
Labels: cleanup
