Repository goblint/analyzer, pull requests merged in 2023-07, with the labels that each got.

#1050 Use-After-Free (UAF) Analysis First Iteration
  src/analyses/baseInvariant.ml
  src/analyses/libraryDesc.ml
  src/analyses/libraryFunctions.ml
  src/analyses/useAfterFree.ml
  src/util/messageCategory.ml
  src/util/sarifRules.ml
  tests/regression/74-use_after_free/01-simple-uaf.c
  tests/regression/74-use_after_free/02-conditional-uaf.c
  tests/regression/74-use_after_free/03-nested-ptr-uaf.c
  tests/regression/74-use_after_free/04-function-call-uaf.c
  tests/regression/74-use_after_free/05-uaf-free-in-wrapper-fun.c
  tests/regression/74-use_after_free/06-uaf-struct.c
  tests/regression/74-use_after_free/07-itc-double-free.c
  tests/regression/74-use_after_free/08-itc-no-double-free.c
  tests/regression/74-use_after_free/09-juliet-uaf.c
  tests/regression/74-use_after_free/10-juliet-double-free.c
  tests/regression/74-use_after_free/11-wrapper-funs-uaf.c
  tests/regression/74-use_after_free/12-multi-threaded-uaf.c
Labels: feature, student-job

#1101 Consider thread-local variables non-unique
  src/analyses/base.ml
  src/domains/queries.ml
  tests/regression/04-mutex/98-thread-local-eq.c
Labels: unsound, c11

#1112 Remove most `MapDomain.Groupable`
  src/analyses/apron/relationPriv.apron.ml
  src/analyses/commonPriv.ml
  src/analyses/spec.ml
  src/cdomains/addressDomain.ml
  src/cdomains/addressDomain_intf.ml
  src/cdomains/baseDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/lockDomain.ml
  src/cdomains/mval_intf.ml
  src/cdomains/threadIdDomain.ml
  src/domains/disjointDomain.ml
  src/domains/flagHelper.ml
  src/domains/hoareDomain.ml
  src/domains/mapDomain.ml
  src/domains/printable.ml
  src/domains/trieDomain.ml
  src/util/cilType.ml
  unittest/domains/mapDomainTest.ml
Labels: cleanup

#1081 Add location to group messages
  src/domains/access.ml
  src/framework/analyses.ml
  src/framework/control.ml
  src/util/gobFormat.ml
  src/util/messages.ml
  src/util/sarif.ml
  tests/regression/04-mutex/01-simple_rc.t
  tests/regression/04-mutex/49-type-invariants.t
  tests/regression/04-mutex/84-distribute-fields-1.t
  tests/regression/04-mutex/85-distribute-fields-2.t
  tests/regression/04-mutex/86-distribute-fields-3.t
  tests/regression/04-mutex/87-distribute-fields-4.t
  tests/regression/04-mutex/88-distribute-fields-5.t
  tests/regression/04-mutex/89-distribute-fields-6.t
Labels: usability

#1111 Fix `cast` for `IBool`
  src/cdomains/intDomain.ml
  tests/regression/03-practical/28-bool.c
  tests/regression/03-practical/29-bool-interval.c
  tests/regression/03-practical/30-bool-congr.c
  unittest/maindomaintest.ml
Labels: bug, unsound, precision

#1104 Make `join` and related operations for Unions preserve equal arguments
  src/cdomains/valueDomain.ml
Labels: bug

#1109 `UnionDomain.meet`: Throw `Uncomparable` exception for abstract unions with different active fields
  src/analyses/baseInvariant.ml
  src/cdomains/unionDomain.ml
  tests/regression/27-inv_invariants/18-union-float-int.c
  tests/regression/27-inv_invariants/19-union-char-int.c
Labels: bug, unsound

#1114 Multi-threaded UAF Analysis
  src/analyses/useAfterFree.ml
Labels: feature, student-job

#1116 Fix GobView Test
  .github/workflows/locked.yml
  docs/user-guide/inspecting.md
  scripts/test-gobview.py
Labels: bug, testing

#1099 Warn for {d,r}eallocation of non-dynamically allocated memory
  src/analyses/base.ml
  src/util/messageCategory.ml
  tests/regression/75-invalid_dealloc/01-invalid-dealloc-simple.c
  tests/regression/75-invalid_dealloc/02-invalid-dealloc-struct.c
  tests/regression/75-invalid_dealloc/03-invalid-dealloc-array.c
  tests/regression/75-invalid_dealloc/04-invalid-realloc.c
Labels: student-job
