Repository goblint/analyzer, pull requests merged in 2023-12, with the labels that each got.

#1282 Bump batteries to 3.5.1 & Remove hacks
  dune-project
  goblint.opam
  src/framework/cfgTools.ml
  src/solvers/postSolver.ml
  src/util/std/gobHashtbl.ml
Labels: cleanup

#1224 Add unknown thread ID
  src/analyses/apron/relationPriv.apron.ml
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/threadAnalysis.ml
  src/analyses/threadJoins.ml
  src/analyses/useAfterFree.ml
  src/cdomains/concDomain.ml
  src/cdomains/mHP.ml
  src/cdomains/threadIdDomain.ml
  src/cdomains/valueDomain.ml
  tests/regression/51-threadjoins/07-trivial-unknowntid.c
Labels: cleanup

#1076 Null Byte Array Domain
  src/analyses/base.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/arrayDomain.mli
  src/cdomains/nullByteSet.ml
  src/cdomains/valueDomain.ml
  src/common/util/xmlUtil.ml
  src/config/options.schema.json
  tests/regression/73-strings/01-string_literals.c
  tests/regression/73-strings/02-string_literals_with_null.c
  tests/regression/73-strings/03-string_basics.c
  tests/regression/73-strings/06-juliet.c
  tests/regression/73-strings/07-larger_example.c
  tests/regression/73-strings/08-cursed.c
  tests/regression/73-strings/09-malloc.c
  tests/regression/73-strings/10-char_arrays.c
Labels: feature, student-job, precision

#1289 Port 16 more library functions
  src/util/library/libraryFunctions.ml
Labels: cleanup

#1292 Make some exception printers lazy, do not use plain CIL printers in messages
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/cdomains/offset.ml
  tests/regression/04-mutex/49-type-invariants.t
  tests/regression/04-mutex/77-type-nested-fields.t
  tests/regression/04-mutex/79-type-nested-fields-deep1.t
  tests/regression/04-mutex/80-type-nested-fields-deep2.t
  tests/regression/04-mutex/90-distribute-fields-type-1.t
  tests/regression/04-mutex/91-distribute-fields-type-2.t
  tests/regression/04-mutex/92-distribute-fields-type-deep.t
  tests/regression/04-mutex/93-distribute-fields-type-global.t
Labels: bug, usability, performance

#1294 Improve readability of global invariants
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/commonPriv.ml
  src/analyses/loopTermination.ml
  src/analyses/mCPRegistry.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/raceAnalysis.ml
  src/analyses/symbLocks.ml
  src/analyses/threadId.ml
  src/analyses/tutorials/signs.ml
  src/analyses/wrapperFunctionAnalysis0.ml
  src/cdomains/intDomain.ml
  src/cdomains/mutexAttrDomain.ml
  src/cdomains/regionDomain.ml
  src/cdomains/stackDomain.ml
  src/cdomains/symbLocksDomain.ml
  src/cdomains/threadIdDomain.ml
  src/cdomains/unionDomain.ml
  src/common/domains/printable.ml
  src/domain/boolDomain.ml
  src/domain/lattice.ml
  src/domains/invariant.ml
  src/domains/queries.ml
  src/domains/valueDomainQueries.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/util/library/libraryDesc.ml
  src/witness/observerAnalysis.ml
Labels: usability

#1295 Clean up SV-COMP directory
  docs/developer-guide/releasing.md
  docs/user-guide/inspecting.md
  docs/user-guide/running.md
  scripts/sv-comp/archive.sh
  scripts/sv-comp/sv-comp-run-no-overflow.py
  scripts/sv-comp/sv-comp-run.py
  scripts/sv-comp/witness-isomorphism.py
  scripts/sv-comp/yed-sv-comp.cnfx
  sv-comp/README.md
  sv-comp/my-bench-sv-comp/.gitignore
  sv-comp/my-bench-sv-comp/README.md
  sv-comp/my-bench-sv-comp/cpa-validate-correctness.xml
  sv-comp/my-bench-sv-comp/cpa-validate-violation.xml
  sv-comp/my-bench-sv-comp/goblint-all-fast.sh
  sv-comp/my-bench-sv-comp/goblint-all-fast.xml
  sv-comp/my-bench-sv-comp/goblint-data-race.sh
  sv-comp/my-bench-sv-comp/goblint-data-race.xml
  sv-comp/my-bench-sv-comp/goblint-lint.sh
  sv-comp/my-bench-sv-comp/goblint-lint.xml
  sv-comp/my-bench-sv-comp/goblint.sh
  sv-comp/my-bench-sv-comp/goblint.xml
  sv-comp/my-bench-sv-comp/table-generator-all-fast.xml
  sv-comp/my-bench-sv-comp/table-generator-data-race.xml
  sv-comp/my-bench-sv-comp/table-generator-lint.xml
  sv-comp/my-bench-sv-comp/table-generator-witness.xml
  sv-comp/my-bench-sv-comp/uautomizer-validate-correctness.xml
  sv-comp/my-bench-sv-comp/uautomizer-validate-violation.xml
  sv-comp/my-bench-sv-comp/witnesslint-validate.xml
  sv-comp/my-bench-sv-comp/witnesslint-validate2.xml
Labels: cleanup, sv-comp, documentation, benchmarking

#1307 Suppress thread-unsafe library function calls in single-threaded mode
  src/analyses/raceAnalysis.ml
  tests/regression/00-sanity/52-thread-unsafe-libfuns-single-thread.c
  tests/regression/00-sanity/52-thread-unsafe-libfuns-single-thread.t
  tests/regression/29-svcomp/32-no-ov.t
Labels: usability

#1311 Remove `OldDomainFacade`
  src/cdomains/intDomain.ml
  src/cdomains/intDomain.mli
Labels: cleanup
