Repository goblint/analyzer, pull requests merged in 2023-09, with the labels that each got.

#1124 Unassume benchmarking fixes
  .semgrep/tracing.yml
  conf/bench-yaml-validate.json
  conf/bench-yaml.json
  conf/svcomp-yaml-validate.json
  conf/svcomp-yaml.json
  src/analyses/base.ml
  src/analyses/unassumeAnalysis.ml
  src/analyses/varEq.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/intDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/partitionDomain.ml
  src/framework/analyses.ml
  src/framework/control.ml
  src/goblint.ml
  src/solvers/td3.ml
  src/witness/witness.ml
  tests/regression/56-witness/37-hh-ex3.c
  tests/regression/56-witness/37-hh-ex3.yml
  tests/regression/56-witness/40-bh-ex1-poly.yml
  tests/regression/56-witness/63-hh-ex3-term.c
  tests/regression/56-witness/63-hh-ex3-term.yml
  tests/regression/73-strings/04-smtprc_strlen_fp.c
Labels: sv-comp, precision, benchmarking

#1157 goblint: fix lower bound on yaml
  dune-project
  goblint.opam
Labels: setup, dependencies

#1138 Library functions that are used in `the silver searcher` including some from the `pcre` library
  src/analyses/libraryFunctions.ml
  src/util/options.schema.json
Labels: usability, precision, benchmarking

#1154 Handle some special cases of `bitand` in `invariant` and `Interval`, `DefExc`, and `Congruences`
  src/analyses/baseInvariant.ml
  src/cdomains/intDomain.ml
  tests/regression/37-congruence/13-bitand.c
Labels: feature, precision

#1160 Document Goblint benchmarking best practices
  README.md
  docs/user-guide/benchmarking.md
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
Labels: documentation

#1161 Congruences: Make `%` sound by restricting cases where we return a constant
  src/cdomains/intDomain.ml
  tests/regression/37-congruence/06-refinements.c
  tests/regression/37-congruence/07-refinements-o.c
  tests/regression/37-congruence/11-overflow-signed.c
  tests/regression/37-congruence/13-bitand.c
  tests/regression/37-congruence/14-negative.c
Labels: bug, unsound

#1162 Fix OCaml 5.0 Apron compatibility
  .github/workflows/unlocked.yml
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
Labels: setup, dependencies

#1170 Use record as `Access.A` type instead of a quintuple
  src/analyses/raceAnalysis.ml
  src/domains/access.ml
Labels: cleanup

#1167 Add `zlib` and `liblzma` functions used in `The Silver Searcher` to `LibraryFunctions`
  src/analyses/libraryFunctions.ml
  src/util/options.schema.json
Labels: precision, benchmarking

#1142 Use `AddressDomain` for `MayPointTo` and `ReachableFrom` queries
  src/analyses/accessAnalysis.ml
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/base.ml
  src/analyses/condVars.ml
  src/analyses/extractPthread.ml
  src/analyses/fileUse.ml
  src/analyses/libraryFunctions.ml
  src/analyses/mallocFresh.ml
  src/analyses/malloc_null.ml
  src/analyses/memLeak.ml
  src/analyses/modifiedSinceLongjmp.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/mutexEventsAnalysis.ml
  src/analyses/mutexTypeAnalysis.ml
  src/analyses/poisonVariables.ml
  src/analyses/pthreadSignals.ml
  src/analyses/raceAnalysis.ml
  src/analyses/spec.ml
  src/analyses/taintPartialContexts.ml
  src/analyses/threadEscape.ml
  src/analyses/uninit.ml
  src/analyses/useAfterFree.ml
  src/analyses/varEq.ml
  src/cdomains/addressDomain.ml
  src/cdomains/mvalMapDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/events.ml
  src/domains/queries.ml
  src/domains/valueDomainQueries.ml
  tests/regression/06-symbeq/21-mult_accs_rc.t
Labels: cleanup, unsound, type-safety, precision

#1172 Add some `setjump/longjump` tests for race detection
  tests/regression/68-longjmp/52-races.c
  tests/regression/68-longjmp/53-races-no.c
  tests/regression/68-longjmp/54-races-actually.c
  tests/regression/68-longjmp/55-races-no-return.c
Labels: testing

#1173 Fix thread analysis termination with a self-creating thread
  src/analyses/threadAnalysis.ml
  tests/regression/10-synch/07-thread_self_create.c
Labels: bug, benchmarking

#1143 fix: copying of files to GobView in projects with subdirectories
  src/maingoblint.ml
Labels: feature, bug, student-job

#1174 Add and fix library functions for Concrat benchmarks
  src/analyses/libraryDesc.ml
  src/analyses/libraryFunctions.ml
  tests/regression/04-mutex/58-pthread-lock-return.c
  tests/regression/41-stdlib/07-atexit.c
  tests/regression/41-stdlib/08-atexit-no-spawn.c
Labels: cleanup, bug, unsound, precision, benchmarking

#1176 Fix `NULL` and unknown pointer handling in `MayPointTo` and `ReachableFrom` for race analysis
  src/analyses/base.ml
  tests/regression/05-lval_ls/20-race-null-void.c
  tests/regression/05-lval_ls/21-race-null-type.c
  tests/regression/05-lval_ls/22-race-null-void-deep.c
  tests/regression/05-lval_ls/23-race-null-type-deep.c
Labels: bug, unsound, precision

#1144 Use `AddressDomain` for queries
  src/analyses/base.ml
  src/analyses/commonPriv.ml
  src/analyses/modifiedSinceLongjmp.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/poisonVariables.ml
  src/analyses/taintPartialContexts.ml
  src/analyses/varEq.ml
  src/cdomains/lockDomain.ml
  src/domains/queries.ml
  src/framework/constraints.ml
Labels: cleanup, precision

#1094 Memory Out-Of-Bounds Access Analysis
  src/analyses/base.ml
  src/analyses/memOutOfBounds.ml
  src/domains/queries.ml
  src/framework/analysisState.ml
  src/util/messageCategory.ml
  tests/regression/77-mem-oob/01-oob-heap-simple.c
  tests/regression/77-mem-oob/02-oob-stack-simple.c
  tests/regression/77-mem-oob/03-oob-loop.c
  tests/regression/77-mem-oob/04-oob-deref-after-ptr-arith.c
  tests/regression/77-mem-oob/05-oob-implicit-deref.c
Labels: feature, student-job

#1196 Fix `BlobSize` query compare
  src/domains/queries.ml
Labels: bug, student-job
