Repository goblint/analyzer, pull requests merged in 2023-03, with the labels that each got.

#1002 Add emoji and Wettlaufweltmeister to ReadTheDocs
  docs/img/wettlaufweltmeister.svg
  docs/index.md
  mkdocs.yml
Labels: documentation

#1004 Fix incremental write-only restarting for side effects from deleted nodes
  src/solvers/td3.ml
  tests/incremental/13-restart-write/09-mutex-self-fix.c
  tests/incremental/13-restart-write/09-mutex-self-fix.json
  tests/incremental/13-restart-write/09-mutex-self-fix.patch
Labels: bug

#1001 Add `arg/lookup` request to server mode
  .gitignore
  src/framework/control.ml
  src/framework/edge.ml
  src/util/options.schema.json
  src/util/server.ml
  src/witness/argTools.ml
  src/witness/myARG.ml
  src/witness/violation.ml
  src/witness/witness.ml
  src/witness/witnessConstraints.ml
Labels: cleanup, feature, debugging

#999 Render options JSON schema to Readthedocs
  .gitignore
  .readthedocs.yaml
  docs/user-guide/configuring.md
  jsfh.yml
  mkdocs.yml
Labels: documentation

#1014 Remove custom `SetDomain` operations
  bench/basic/benchSet.ml
  bench/basic/dune
  src/domains/setDomain.ml
Labels: cleanup, performance

#1008 Add `arg/dot`, `arg/state`, `arg/eval` and `arg/eval-int` requests to server mode
  src/analyses/base.ml
  src/analyses/mCP.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/valueDomain.ml
  src/domains/printable.ml
  src/domains/queries.ml
  src/util/gobZ.ml
  src/util/server.ml
  src/witness/argTools.ml
  src/witness/witnessConstraints.ml
  src/witness/witnessUtil.ml
Labels: feature, debugging

#1012 Add `cil/varinfos` request to server mode
  src/util/cilfacade.ml
  src/util/server.ml
Labels: feature, debugging

#943 IntDomain code optimizations
  src/cdomains/floatDomain.ml
  src/cdomains/intDomain.ml
  src/util/contextUtil.ml
  src/util/precisionUtil.ml
  src/util/server.ml
  unittest/cdomains/floatDomainTest.ml
Labels: student-job, performance, practical-course

#1010 Clear TD3 `sides` when not reusing `wpoint` incrementally
  src/solvers/td3.ml
Labels: bug, precision

#1017 Fix incremental invariant parser for server mode
  src/util/server.ml
  src/witness/witnessUtil.ml
Labels: bug

#490 TD3 cleanup
  src/solvers/td3.ml
Labels: cleanup

#963 ESOP '23 Artifact Description
  docs/artifact-descriptions/esop23.md
  mkdocs.yml
Labels: documentation, benchmarking

#1020 Documentation on cram tests
  docs/developer-guide/testing.md
Labels: testing, documentation

#1023 Fix longjmp marshaling tests, clean up relifting
  src/analyses/mCPRegistry.ml
  src/analyses/tutorials/signs.ml
  src/cdomains/apron/affineEqualityDomain.apron.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/apron/relationDomain.apron.ml
  src/cdomains/arrayDomain.ml
  src/cdomains/baseDomain.ml
  src/cdomains/basetype.ml
  src/cdomains/floatDomain.ml
  src/cdomains/intDomain.ml
  src/cdomains/jmpBufDomain.ml
  src/cdomains/lval.ml
  src/cdomains/lvalMapDomain.ml
  src/cdomains/mHP.ml
  src/cdomains/pthreadDomain.ml
  src/cdomains/structDomain.ml
  src/cdomains/symbLocksDomain.ml
  src/cdomains/valueDomain.ml
  src/domains/access.ml
  src/domains/accessDomain.ml
  src/domains/mapDomain.ml
  src/domains/printable.ml
  src/domains/setDomain.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/node.ml
  src/util/cilType.ml
  src/witness/myARG.ml
  unittest/maindomaintest.ml
Labels: cleanup, bug

#1024 Fix 00-sanity/35-join-contexts by syncing at function entry
  src/framework/constraints.ml
  tests/regression/00-sanity/35-join-contexts.c
Labels: bug, unsound

#1022 Split `combine` into `combine_env` and `combine_assign`
  src/analyses/abortUnless.ml
  src/analyses/accessAnalysis.ml
  src/analyses/activeSetjmp.ml
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/assert.ml
  src/analyses/base.ml
  src/analyses/condVars.ml
  src/analyses/expRelation.ml
  src/analyses/expsplit.ml
  src/analyses/extractPthread.ml
  src/analyses/fileUse.ml
  src/analyses/mCP.ml
  src/analyses/mallocFresh.ml
  src/analyses/mallocWrapperAnalysis.ml
  src/analyses/malloc_null.ml
  src/analyses/modifiedSinceLongjmp.ml
  src/analyses/poisonVariables.ml
  src/analyses/pthreadSignals.ml
  src/analyses/region.ml
  src/analyses/spec.ml
  src/analyses/stackTrace.ml
  src/analyses/symbLocks.ml
  src/analyses/taintPartialContexts.ml
  src/analyses/termination.ml
  src/analyses/threadAnalysis.ml
  src/analyses/threadEscape.ml
  src/analyses/threadFlag.ml
  src/analyses/threadId.ml
  src/analyses/threadJoins.ml
  src/analyses/threadReturn.ml
  src/analyses/tutorials/constants.ml
  src/analyses/tutorials/taint.ml
  src/analyses/tutorials/unitAnalysis.ml
  src/analyses/unassumeAnalysis.ml
  src/analyses/uninit.ml
  src/analyses/varEq.ml
  src/analyses/vla.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/util/wideningTokens.ml
  src/witness/observerAnalysis.ml
  src/witness/witnessConstraints.ml
  tests/regression/04-mutex/74-combine-env-assign-imprecise.c
  tests/regression/04-mutex/75-combine-env-assign-unsound.c
  tests/regression/46-apron2/56-combine-env-assign.c
  tests/regression/62-abortUnless/04-lval.c
Labels: cleanup, bug, unsound

#967 `AddressSet.meet`: Convert offsets to intdomain values to check overlap
  src/analyses/base.ml
  src/cdomains/addressDomain.ml
  src/cdomains/lval.ml
  src/cdomains/valueDomain.ml
  src/domains/disjointDomain.ml
  tests/regression/02-base/91-ad-meet.c
  tests/regression/02-base/92-ad-union-fields.c
  tests/regression/02-base/93-ad-struct-offset.c
  tests/regression/69-addresses/01-meet.c
  tests/regression/69-addresses/02-array-cast.c
Labels: bug, unsound
