Repository goblint/analyzer, pull requests merged in 2024-04, with the labels that each got.

#1320 Add Zulip badge and acknowledgement
  README.md
Labels: documentation

#1403 Record statement copies during loop unrolling
  src/common/framework/cfgTools.ml
  src/common/util/loopUnrolling0.ml
  src/config/options.schema.json
  src/util/loopUnrolling.ml
  src/util/loopUnrolling.mli
  tests/regression/55-loop-unrolling/11-unrolled-loop-invariant.c
  tests/regression/55-loop-unrolling/11-unrolled-loop-invariant.t
  tests/regression/55-loop-unrolling/dune
  tests/regression/cfg/util/cfgDot.ml
  tests/regression/cfg/util/dune
Labels: sv-comp

#1404 Move unit tests to tests/unit/
  docs/developer-guide/testing.md
  tests/unit/analyses/libraryDslTest.ml
  tests/unit/cdomains/floatDomainTest.ml
  tests/unit/cdomains/intDomainTest.ml
  tests/unit/cdomains/lvalTest.ml
  tests/unit/domains/mapDomainTest.ml
  tests/unit/dune
  tests/unit/mainTest.ml
  tests/unit/maindomaintest.ml
  tests/unit/solver/solverTest.ml
  tests/unit/util/cilfacadeTest.ml
  tests/unit/util/compilationDatabaseTest.ml
  tests/unit/util/intOpsTest.ml
Labels: cleanup, testing

#1405 Improve output for `NullByte`
  src/cdomain/value/cdomains/arrayDomain.ml
  src/cdomain/value/cdomains/nullByteSet.ml
Labels: cleanup, usability

#1357 Add cram tests for YAML witnesses
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/witness/yamlWitness.ml
  src/witness/yamlWitnessType.ml
  tests/regression/55-loop-unrolling/11-unrolled-loop-invariant.t
  tests/regression/56-witness/05-prec-problem.c
  tests/regression/56-witness/05-prec-problem.t
  tests/regression/56-witness/08-witness-all-locals.t
  tests/regression/70-transform/01-ordering.t
  tests/regression/cfg/foo.t/run.t
  tests/regression/cfg/issue-1356.t/run.t
  tests/regression/cfg/loops.t/loops.c
  tests/regression/cfg/loops.t/run.t
  tests/regression/cfg/pr-758.t/pr-758.c
  tests/regression/cfg/pr-758.t/run.t
  tests/regression/dune
  tests/util/dune
  tests/util/yamlWitnessStrip.ml
Labels: bug, testing, sv-comp

#1396 Avoid base invariant fallback not understood message on reflexive pointer literal equality
  src/analyses/baseInvariant.ml
Labels: bug, usability

#1399 Ego-Lane-Derived-Digests for Privatizations: `Lock- ` & `Write-Centered` Privatizations
  src/analyses/basePriv.ml
  src/config/options.schema.json
  tests/regression/13-privatized/18-first-reads.c
  tests/regression/13-privatized/53-pfscan_widen_dependent_minimal.c
  tests/regression/13-privatized/55-widen-dependent-local.c
  tests/regression/13-privatized/77-lock-tid.c
  tests/regression/13-privatized/78-write-tid.c
  tests/regression/13-privatized/79-write-lock-tid.c
  tests/regression/66-interval-set-one/62-pfscan_widen_dependent_minimal.c
  tests/regression/66-interval-set-one/98-widen-dependent-local.c
  tests/regression/67-interval-sets-two/43-first-reads.c
Labels: feature, precision

#1409 Check semantic indices of unlocked mutex
  src/cdomains/lockDomain.ml
  tests/regression/05-lval_ls/19-idxunknown_unlock_precise.c
Labels: cleanup, feature, precision

#1375 Unroll typedefs in witness invariants
  src/cdomain/value/domains/invariantCil.ml
  src/config/options.schema.json
  src/witness/witnessUtil.ml
  tests/regression/witness/typedef.t/run.t
  tests/regression/witness/typedef.t/typedef.c
Labels: bug, sv-comp

#1406 Suppress Overflow Warnings for Computations Not in the Program
  src/analyses/baseInvariant.ml
  src/cdomain/value/cdomains/intDomain.ml
  src/cdomain/value/cdomains/intDomain.mli
  tests/regression/27-inv_invariants/20-warns-unsigned.c
Labels: usability, precision

#1400 Change YAML witness columns to 1-indexed
  src/analyses/unassumeAnalysis.ml
  src/witness/yamlWitness.ml
  tests/regression/56-witness/01-base-lor-enums.yml
  tests/regression/56-witness/02-base-lor-addr.yml
  tests/regression/56-witness/03-int-log-short.yml
  tests/regression/56-witness/04-base-priv-sync-prune.yml
  tests/regression/56-witness/05-prec-problem.t
  tests/regression/56-witness/07-base-lor-interval.yml
  tests/regression/56-witness/08-witness-all-locals.t
  tests/regression/56-witness/10-apron-unassume-interval.yml
  tests/regression/56-witness/11-base-unassume-interval.yml
  tests/regression/56-witness/12-apron-unassume-branch.yml
  tests/regression/56-witness/13-base-unassume-branch.yml
  tests/regression/56-witness/14-base-unassume-precondition.yml
  tests/regression/56-witness/15-base-unassume-query.yml
  tests/regression/56-witness/16-base-unassume-dependent.yml
  tests/regression/56-witness/17-base-unassume-tauto.yml
  tests/regression/56-witness/18-base-unassume-contra.yml
  tests/regression/56-witness/19-base-unassume-mem.yml
  tests/regression/56-witness/20-apron-unassume-global.yml
  tests/regression/56-witness/21-apron-unassume-priv.yml
  tests/regression/56-witness/22-base-unassume-priv.yml
  tests/regression/56-witness/23-base-unassume-priv2.yml
  tests/regression/56-witness/24-apron-unassume-priv2.yml
  tests/regression/56-witness/25-apron-unassume-strengthening.yml
  tests/regression/56-witness/26-mine-tutorial-ex4.6.yml
  tests/regression/56-witness/27-mine-tutorial-ex4.7.yml
  tests/regression/56-witness/28-mine-tutorial-ex4.8.yml
  tests/regression/56-witness/29-mine-tutorial-ex4.10.yml
  tests/regression/56-witness/30-base-unassume-inc-dec.yml
  tests/regression/56-witness/31-base-unassume-mem-ex.yml
  tests/regression/56-witness/32-base-unassume-lor-addr.yml
  tests/regression/56-witness/33-base-unassume-lor-enums.yml
  tests/regression/56-witness/34-base-unassume-inc-dec-traces.yml
  tests/regression/56-witness/35-hh-ex1b.yml
  tests/regression/56-witness/36-hh-ex2b.yml
  tests/regression/56-witness/37-hh-ex3.yml
  tests/regression/56-witness/38-bh-ex3.yml
  tests/regression/56-witness/39-bh-ex-add.yml
  tests/regression/56-witness/40-bh-ex1-poly.yml
  tests/regression/56-witness/41-as-hybrid.yml
  tests/regression/56-witness/42-base-unassume-precheck.yml
  tests/regression/56-witness/43-apron-unassume-precheck.yml
  tests/regression/56-witness/44-base-unassume-array.yml
  tests/regression/56-witness/62-tm-inv-transfer-protection-witness.yml
  tests/regression/56-witness/63-hh-ex3-term.yml
  tests/regression/cfg/foo.t/run.t
  tests/regression/cfg/loops.t/run.t
  tests/regression/cfg/pr-758.t/run.t
Labels: sv-comp

#1410 Fix NULL pointer dereference error for NULL mutexattr
  src/analyses/base.ml
  tests/regression/71-doublelocking/17-default-dyn.c
Labels: bug, precision

#1411 Add flag `AnalysisState.executing_speculative_computations` to avoid flagging overflows during `invariant`
  src/analyses/baseInvariant.ml
  src/cdomain/value/cdomains/intDomain.ml
  src/common/framework/analysisState.ml
  tests/regression/27-inv_invariants/20-warns-unsigned.c
  tests/regression/cfg/issue-1356.t/run.t
Labels: usability, precision

#1414 `PTHREAD_MUTEX_DEFAULT` handling is unsound
  docs/user-guide/assumptions.md
  mkdocs.yml
  src/analyses/base.ml
  tests/regression/71-doublelocking/17-default-null-dyn.c
  tests/regression/71-doublelocking/18-default-explicit-dyn.c
  tests/regression/71-doublelocking/19-default-init.c
Labels: bug, unsound

#1413 `DefExc`,`Enums`: More precise `of_interval` and `starting` and `ending`
  src/cdomain/value/cdomains/intDomain.ml
  tests/regression/01-cpa/75-refine-def-exc.c
  tests/regression/cfg/foo.t/run.t
Labels: precision

#1416 Fix pthread mutex type from initializer on OSX
  docs/user-guide/assumptions.md
  src/analyses/mutexTypeAnalysis.ml
  tests/regression/71-doublelocking/05-rec.c
  tests/regression/71-doublelocking/08-other-type.c
  tests/regression/71-doublelocking/13-rec-struct.c
  tests/regression/71-doublelocking/19-default-init.c
  tests/regression/71-doublelocking/20-default-init-osx.c
Labels: bug, precision

#1419 Missing division by zero treatment in MaySignedOverflow
  src/analyses/base.ml
  tests/regression/77-lin2vareq/32-divbzero-in-overflow.c
Labels: bug

#1408 Improve `invariant` for unsigned types
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/cdomain/value/cdomains/intDomain.ml
  src/cdomain/value/cdomains/valueDomain.ml
  src/common/framework/analysisState.ml
  tests/regression/27-inv_invariants/20-warns-unsigned.c
  tests/regression/27-inv_invariants/21-unsigned.c
  tests/regression/cfg/issue-1356.t/run.t
Labels: precision

#1429 Fix SV-COMP Apron unassume crash
  src/analyses/apron/relationAnalysis.apron.ml
  tests/regression/56-witness/45-apron-tracked-global-annot.c
  tests/regression/56-witness/45-apron-tracked-global-annot.yml
Labels: bug

#1431 More useful stats output by privPrecCompare
  src/util/precCompare.ml
Labels: benchmarking

#1424 Improve `dune runtest` output
  scripts/update_suite.rb
  tests/incremental/dune
  tests/regression/24-octagon/dune
  tests/regression/36-apron/dune
  tests/regression/46-apron2/dune
  tests/regression/52-apron-mukherjee/dune
  tests/regression/56-witness/dune
  tests/regression/63-affeq/dune
  tests/regression/77-lin2vareq/dune
  tests/regression/78-termination/dune
  tests/regression/dune
  tests/unit/mainTest.ml
Labels: cleanup, testing, usability

#1436 Fix enums domain to not emit witness invariants for top booleans
  src/cdomain/value/cdomains/intDomain.ml
  tests/regression/56-witness/46-top-bool-invariant.c
  tests/regression/56-witness/46-top-bool-invariant.t
  tests/regression/56-witness/47-top-int-invariant.c
  tests/regression/56-witness/47-top-int-invariant.t
Labels: bug, sv-comp
