Repository goblint/analyzer, pull requests merged in 2024-09, with the labels that each got.

#1523 Use `String.starts_with` and `ends_with` from `Stdlib`
  src/analyses/mutexEventsAnalysis.ml
  src/autoTune.ml
  src/build-info/dune
  src/build-info/goblint_build_info.ml
  src/cdomain/value/domains/invariantCil.ml
  src/cdomains/apron/affineEqualityDomain.apron.ml
  src/common/util/cilfacade.ml
  src/domains/access.ml
  src/incremental/compareAST.ml
  src/incremental/makefileUtil.ml
  src/witness/svcomp.ml
Labels: cleanup, type-safety

#1554 Unvendor ppx_blob
  dune-project
  goblint.opam
  goblint.opam.locked
  src/vendor/ppx_blob/LICENSE.txt
  src/vendor/ppx_blob/README.md
  src/vendor/ppx_blob/src/dune
  src/vendor/ppx_blob/src/ppx_blob.ml
Labels: cleanup, setup, dependencies

#1560 Add backtrace markers around `LibraryFunctions` special calls
  src/autoTune.ml
  src/cdomain/value/util/wideningThresholds.ml
  src/common/dune
  src/common/util/cilfacade.ml
  src/transform/evalAssert.ml
  src/util/backtrace/goblint_backtrace.ml
  src/util/backtrace/goblint_backtrace.mli
  src/util/library/libraryFunctions.ml
  src/util/loopUnrolling.ml
  src/witness/witnessUtil.ml
Labels: bug, benchmarking

#1562 Fix base must-writing all invalidated variables
  src/analyses/base.ml
Labels: bug, unsound

#1512 Add primitive verdict-based YAML violation witness rejection
  conf/svcomp-validate.json
  src/analyses/unassumeAnalysis.ml
  src/config/options.schema.json
  src/witness/yamlWitness.ml
  src/witness/yamlWitnessType.ml
  tests/regression/witness/violation.t/correct-hard.c
  tests/regression/witness/violation.t/correct-hard.yml
  tests/regression/witness/violation.t/correct.c
  tests/regression/witness/violation.t/correct.yml
  tests/regression/witness/violation.t/incorrect.c
  tests/regression/witness/violation.t/incorrect.yml
  tests/regression/witness/violation.t/run.t
  tests/util/yamlWitnessStrip.ml
Labels: feature, sv-comp

#1570 Context Gas per Function ⛽
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/apron/relationPriv.apron.ml
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/basePriv.mli
  src/analyses/commonPriv.ml
  src/analyses/mCP.ml
  src/config/options.schema.json
  src/domains/queries.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/contextGasLifter.ml
  src/framework/contextGasLifter.mli
  src/framework/control.ml
  src/goblint_lib.ml
  tests/regression/80-context_gas/23-per-fun.c
  tests/regression/80-context_gas/24-per-fun-ex.c
Labels: cleanup, feature, precision, performance

#1575 Move `Spec` lifters out of `Constraints`
  src/framework/compareConstraints.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/goblint_lib.ml
  src/lifters/contextGasLifter.ml
  src/lifters/contextGasLifter.mli
  src/lifters/longjmpLifter.ml
  src/lifters/longjmpLifter.mli
  src/lifters/recursionTermLifter.ml
  src/lifters/recursionTermLifter.mli
  src/lifters/specLifters.ml
  src/lifters/wideningTokens.ml
Labels: cleanup

#1579 Add "ERROR (both branches dead)" verdict for SV-COMP
  src/common/framework/analysisState.ml
  src/goblint.ml
  src/lifters/specLifters.ml
  src/util/server.ml
  src/witness/witness.ml
Labels: bug, unsound, sv-comp

#1582 Refactor loopUnrolling autotuner
  src/util/loopUnrolling.ml
Labels: cleanup
