Repository goblint/analyzer, pull requests merged in 2024-10, with the labels that each got.

#1574 Change `Machdep` based on SV-COMP architecture
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
  src/analyses/base.ml
  src/cdomain/value/cdomains/arrayDomain.ml
  src/common/util/cilfacade.ml
  src/goblint.ml
  tests/regression/29-svcomp/36-svcomp-arch.c
  tests/regression/29-svcomp/36-svcomp-arch.t
  tests/regression/29-svcomp/dune
Labels: feature, unsound, sv-comp

#1584 Adjust loop unrolling defaults
  src/util/loopUnrolling.ml
Labels: sv-comp, precision, performance

#1592 Remove fixed malloc wrappers from svcomp conf
  conf/svcomp-validate.json
  conf/svcomp.json
Labels: cleanup, sv-comp

#1516 Detect fixed loops with autotuner even if there is no assignment of const value to the loop variable before loop
  src/util/loopUnrolling.ml
Labels: sv-comp, precision

#1590 Handle loop statement comparison between two variables in loop unrolling
  src/util/loopUnrolling.ml
Labels: sv-comp, precision

#1595 Restrict unrolling to loops that are nested within less than 4 loops
  src/util/loopUnrolling.ml
  tests/regression/55-loop-unrolling/08-bad.t
Labels: sv-comp, performance

#1597 Replace most physical equality on immutable types
  src/analyses/uninit.ml
  src/common/util/cilfacade.ml
  src/domain/boolDomain.ml
  src/domain/lattice.ml
  src/incremental/compareAST.ml
  src/incremental/compareCFG.ml
  src/incremental/compareCIL.ml
  src/util/loopUnrolling.ml
  src/witness/myARG.ml
Labels: cleanup, type-safety

#1598 ⛽: Use minimum to combine incoming gas values in per-context gas
  src/lifters/contextGasLifter.ml
  tests/regression/80-context_gas/25-per-fun-nonterm.c
Labels: bug, performance

#1599 Improve loop bound detection for loop unrolling by handling casts in loop statements
  src/util/loopUnrolling.ml
Labels: sv-comp, precision

#1593 Remove witness `exclude-vars` from svcomp conf
  conf/svcomp.json
Labels: cleanup, sv-comp

#1603 Fix `sem.unknown_function.spawn` handling in base
  src/analyses/base.ml
  src/config/options.schema.json
  src/util/library/libraryDsl.ml
  src/util/library/libraryDsl.mli
  src/util/library/libraryFunctions.ml
  tests/regression/41-stdlib/08-atexit-no-spawn.c
Labels: cleanup, bug, unsound, sv-comp

#1604 Consider all spawning functions in autotuner
  src/autoTune.ml
  src/util/autoSoundConfig.ml
Labels: bug, unsound, sv-comp

#1602 Improve flat string domain hash
  src/cdomain/value/cdomains/stringDomain.ml
Labels: cleanup, bug, type-safety, performance

#1607 Add `pthread_self` support
  src/analyses/base.ml
  src/cdomain/value/cdomains/threadIdDomain.ml
  src/util/library/libraryDesc.ml
  src/util/library/libraryFunctions.ml
  tests/regression/51-threadjoins/09-join-main.c
  tests/regression/51-threadjoins/10-join-main-plain.c
  tests/regression/51-threadjoins/11-join-main-plain-no-node.c
Labels: feature, precision
