Repository goblint/analyzer, pull requests merged in 2024-02, with the labels that each got.

#1349 Remove intermediate module definition in `AffineEqualityAnalysis`
  src/analyses/apron/affineEqualityAnalysis.apron.ml
  src/analyses/apron/apronAnalysis.apron.ml
  src/cdomains/apron/affineEqualityDomain.apron.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/apron/relationDomain.apron.ml
Labels: cleanup

#1344 Handle `LNot` for float in forward evaluation and refinement on guards
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  tests/regression/57-floats/22-lnot.c
Labels: bug, precision

#1334 Exclude Goblint stubs from YAML witnesses
  src/witness/yamlWitness.ml
Labels: bug, sv-comp

#1365 Add `context_to_yojson` in messages
  src/common/util/messages.ml
Labels: usability

#1362 Add option `witness.invariant.all-locals` to only print locals definitely in scope
  src/cdomain/value/domains/invariantCil.ml
  src/config/options.schema.json
  src/maingoblint.ml
  tests/regression/56-witness/08-witness-all-locals.c
  tests/regression/56-witness/08-witness-all-locals.t
  tests/regression/56-witness/dune
Labels: feature, sv-comp, pr-dependency

#1368 Clean up old `make` targets
  make.sh
Labels: cleanup

#1312 Small output readability improvements
  src/analyses/mHPAnalysis.ml
  src/analyses/wrapperFunctionAnalysis.ml
  src/cdomain/value/cdomains/intDomain.ml
  src/cdomain/value/cdomains/threadIdDomain.ml
  src/cdomains/mHP.ml
  src/config/options.schema.json
  tests/regression/02-base/87-casts-dep-on-param.t
  tests/regression/02-base/dune
  tests/regression/04-mutex/01-simple_rc.t
  tests/regression/04-mutex/49-type-invariants.t
  tests/regression/04-mutex/77-type-nested-fields.t
  tests/regression/04-mutex/79-type-nested-fields-deep1.t
  tests/regression/04-mutex/80-type-nested-fields-deep2.t
  tests/regression/04-mutex/84-distribute-fields-1.t
  tests/regression/04-mutex/85-distribute-fields-2.t
  tests/regression/04-mutex/86-distribute-fields-3.t
  tests/regression/04-mutex/87-distribute-fields-4.t
  tests/regression/04-mutex/88-distribute-fields-5.t
  tests/regression/04-mutex/89-distribute-fields-6.t
  tests/regression/04-mutex/90-distribute-fields-type-1.t
  tests/regression/04-mutex/91-distribute-fields-type-2.t
  tests/regression/04-mutex/92-distribute-fields-type-deep.t
  tests/regression/04-mutex/93-distribute-fields-type-global.t
  tests/regression/06-symbeq/14-list_entry_rc.t
  tests/regression/06-symbeq/16-type_rc.t
  tests/regression/06-symbeq/21-mult_accs_rc.t
  tests/regression/45-escape/51-fresh-global.t
  tests/regression/45-escape/dune
  tests/regression/74-invalid_deref/01-oob-heap-simple.c
  tests/regression/74-invalid_deref/01-oob-heap-simple.t
  tests/regression/74-invalid_deref/dune
Labels: usability

#1367 Move all tests to `dune runtest`
  .github/workflows/coverage.yml
  .github/workflows/locked.yml
  .github/workflows/unlocked.yml
  .gitignore
  docs/developer-guide/testing.md
  make.sh
  scripts/update_suite.rb
  src/dune
  src/util/library/libraryFunctions.ml
  tests/extraction/dune
  tests/incremental/dune
  tests/regression/24-octagon/dune
  tests/regression/36-apron/dune
  tests/regression/46-apron2/dune
  tests/regression/52-apron-mukherjee/dune
  tests/regression/63-affeq/dune
  tests/regression/78-termination/dune
  tests/regression/dune
  tests/suite_result/.gitignore
Labels: cleanup, testing, usability

#1369 Fix and refactor syntactic loop unrolling
  src/common/util/cilfacade.ml
  src/config/options.schema.json
  src/util/loopUnrolling.ml
  tests/regression/55-loop-unrolling/01-simple-cases.t
  tests/regression/55-loop-unrolling/02-break.t
  tests/regression/55-loop-unrolling/03-break-right-place.t
  tests/regression/55-loop-unrolling/04-simple.t
  tests/regression/55-loop-unrolling/05-continue.t
  tests/regression/55-loop-unrolling/06-simple-cases-unrolled.t
  tests/regression/55-loop-unrolling/07-nested-unroll.t
  tests/regression/55-loop-unrolling/08-bad.t
  tests/regression/55-loop-unrolling/09-weird.t
  tests/regression/55-loop-unrolling/10-continue-right-place.c
  tests/regression/55-loop-unrolling/10-continue-right-place.t
  tests/regression/55-loop-unrolling/dune
Labels: cleanup, bug, testing
