Repository goblint/analyzer, pull requests merged in 2024-03, with the labels that each got.

#1377 Fix `evalbinop_base` for `==` on `Int` and `Address`
  src/analyses/base.ml
  tests/regression/00-sanity/53-ptr-and-int.c
Labels: bug, unsound

#1387 Fix test for relational unassume with strengthening
  src/analyses/apron/relationAnalysis.apron.ml
  src/cdomains/apron/apronDomain.apron.ml
  tests/regression/56-witness/25-apron-unassume-strengthening.c
  tests/regression/56-witness/25-apron-unassume-strengthening.yml
Labels: bug, sv-comp, precision, relational

#1395 Use ppx_deriving_hash 0.1.2
  dune-project
  goblint.opam
  goblint.opam.locked
  src/cdomains/vectorMatrix.ml
  src/common/cdomains/floatOps/floatOps.ml
  src/common/util/cilType.ml
  src/domains/queries.ml
Labels: cleanup, setup, dependencies

#1398 Ego-Lane-Derived-Digests for Privatizations: `ProtectionBasedTIDPriv`
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/basePriv.mli
  src/analyses/commonPriv.ml
  src/analyses/threadEscape.ml
  src/analyses/useAfterFree.ml
  src/cdomain/value/cdomains/threadIdDomain.ml
  src/config/options.schema.json
  tests/regression/02-base/01-thread_creation.c
  tests/regression/13-privatized/75-protection-tid.c
  tests/regression/13-privatized/76-protection-tid2.c
Labels: feature, precision

#1393 Automatically add newline to trace output
  docs/developer-guide/debugging.md
  src/analyses/accessAnalysis.ml
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/apron/relationPriv.apron.ml
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/analyses/basePriv.ml
  src/analyses/condVars.ml
  src/analyses/loopTermination.ml
  src/analyses/mCP.ml
  src/analyses/memLeak.ml
  src/analyses/symbLocks.ml
  src/analyses/taintPartialContexts.ml
  src/analyses/threadEscape.ml
  src/analyses/tmpSpecial.ml
  src/analyses/varEq.ml
  src/cdomain/value/cdomains/addressDomain.ml
  src/cdomain/value/cdomains/arrayDomain.ml
  src/cdomain/value/cdomains/floatDomain.ml
  src/cdomain/value/cdomains/intDomain.ml
  src/cdomain/value/cdomains/offset.ml
  src/cdomain/value/cdomains/structDomain.ml
  src/cdomain/value/cdomains/valueDomain.ml
  src/cdomains/apron/affineEqualityDomain.apron.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/apron/linearTwoVarEqualityDomain.apron.ml
  src/cdomains/apron/sharedFunctions.apron.ml
  src/cdomains/symbLocksDomain.ml
  src/common/framework/cfgTools.ml
  src/config/gobConfig.ml
  src/domains/access.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/incremental/compareAST.ml
  src/maingoblint.ml
  src/solver/generic.ml
  src/solver/postSolver.ml
  src/solver/sLR.ml
  src/solver/sLRphased.ml
  src/solver/sLRterm.ml
  src/solver/td3.ml
  src/solver/topDown.ml
  src/solver/topDown_deprecated.ml
  src/solver/topDown_space_cache_term.ml
  src/solver/topDown_term.ml
  src/util/tracing/goblint_tracing.ml
  src/witness/argTools.ml
  src/witness/witness.ml
  src/witness/witnessConstraints.ml
Labels: cleanup
