Repository goblint/analyzer, pull requests merged in 2024-07, with the labels that each got.

#1493 make cil_exp_of_linexpr1 work with fractional expressions
  src/cdomains/apron/sharedFunctions.apron.ml
Labels: bug, relational

#1506 Fix Apron `compare` function usage
  dune-project
  goblint.opam
  goblint.opam.locked
  src/cdomains/apron/affineEqualityDomain.apron.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/apron/gobApron.apron.ml
  src/cdomains/apron/linearTwoVarEqualityDomain.apron.ml
Labels: type-safety, setup, dependencies, relational

#1543 Propagate bottom through narrowing operators of lattice lifters
  src/domain/lattice.ml
Labels: bug, precision

#1546 Check overflows when generating witnesses
  src/cdomains/apron/sharedFunctions.apron.ml
Labels: bug, unsound, sv-comp

#1527 Refactor Apron `Printable`s
  src/analyses/apron/relationAnalysis.apron.ml
  src/cdomains/apron/affineEqualityDomain.apron.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/apron/gobApron.apron.ml
  src/cdomains/apron/linearTwoVarEqualityDomain.apron.ml
  src/cdomains/apron/sharedFunctions.apron.ml
  src/common/domains/printable.ml
  src/common/util/gobFormat.ml
Labels: cleanup, usability

#1503 Continue refactoring of must-locksets to use definite mvals instead of addresses
  src/analyses/apron/relationPriv.apron.ml
  src/analyses/basePriv.ml
  src/analyses/basePriv.mli
  src/analyses/commonPriv.ml
  src/analyses/mutexAnalysis.ml
  src/cdomains/lockDomain.ml
  src/domains/queries.ml
Labels: cleanup, type-safety

#1492 Fix `mutex-meet` for malloc after thread creation
  src/analyses/apron/relationPriv.apron.ml
  tests/regression/46-apron2/90-malloc.c
  tests/regression/46-apron2/91-malloc-tid.c
  tests/regression/46-apron2/92-malloc-atomic.c
Labels: bug, unsound, relational
