Repository goblint/analyzer, pull requests merged in 2024-08, with the labels that each got.

#1555 `Relational MM`: Cluster `LMust`
  src/analyses/apron/relationPriv.apron.ml
  src/analyses/basePriv.ml
  src/analyses/commonPriv.ml
  tests/regression/46-apron2/98-issue-1511b.c
  tests/regression/46-apron2/98-issue-1511b.t
Labels: bug, precision, relational

#1095 Add PPX derivers for lattices of tuple and record types
  dune-project
  goblint.opam
  scripts/goblint-lib-modules.py
  src/cdomain/value/cdomains/floatDomain.ml
  src/cdomain/value/cdomains/intDomain.ml
  src/cdomains/apron/relationDomain.apron.ml
  src/cdomains/baseDomain.ml
  src/cdomains/mHP.ml
  src/cdomains/pthreadDomain.ml
  src/common/domains/printable.ml
  src/common/dune
  src/domain/dune
  src/domain/lattice.ml
  src/dune
  src/framework/analyses.ml
  src/ppx/dune
  src/ppx/lattice/dune
  src/ppx/lattice/ppx_deriving_lattice.ml
  src/ppx/printable/dune
  src/ppx/printable/ppx_deriving_printable.ml
  src/vendor/ppx_easy_deriving/LICENSE.md
  src/vendor/ppx_easy_deriving/README.md
  src/vendor/ppx_easy_deriving/deriver.ml
  src/vendor/ppx_easy_deriving/deriver.mli
  src/vendor/ppx_easy_deriving/deriver_intf.ml
  src/vendor/ppx_easy_deriving/dune
  src/vendor/ppx_easy_deriving/intf.ml
  src/vendor/ppx_easy_deriving/pat_exp.ml
  src/vendor/ppx_easy_deriving/pat_exp.mli
  src/vendor/ppx_easy_deriving/ppx_easy_deriving.ml
  src/vendor/ppx_easy_deriving/product.ml
  src/vendor/ppx_easy_deriving/product.mli
  src/vendor/ppx_easy_deriving/product_intf.ml
  src/vendor/ppx_easy_deriving/util.ml
  src/vendor/ppx_easy_deriving/util.mli
Labels: cleanup, type-safety

#1517 Simplify `IntDomTuple` witness invariants
  src/cdomain/value/cdomains/intDomain.ml
  src/config/options.schema.json
  tests/regression/56-witness/46-top-bool-invariant.t
  tests/regression/cfg/foo.t/run.t
  tests/regression/witness/int.t/int.c
  tests/regression/witness/int.t/run.t
Labels: feature, usability, sv-comp

#1559 Make `update_offset` idempotent for blobs
  src/cdomain/value/cdomains/valueDomain.ml
  tests/regression/13-privatized/95-mm-calloc.c
Labels: bug, unsound, precision

#1563 Default the value of `CilType.Location.Byte` to -1 if missing in JSON
  src/common/util/cilType.ml
Labels: bug, usability
