Repository goblint/analyzer, pull requests merged in 2024-06, with the labels that each got.

#1434 Clean up `destabilize_vs`
  src/solver/td3.ml
Labels: cleanup, student-job

#1500 Fix privatization unsoundness due to non-definite and unknown mutexes
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/base.ml
  src/analyses/commonPriv.ml
  tests/regression/13-privatized/93-unlock-idx-ambiguous.c
  tests/regression/13-privatized/93-unlock-idx-ambiguous.t
  tests/regression/13-privatized/94-unlock-unknown.c
  tests/regression/13-privatized/94-unlock-unknown.t
  tests/regression/13-privatized/dune
  tests/regression/46-apron2/87-unlock-idx-ambiguous.c
  tests/regression/46-apron2/87-unlock-idx-ambiguous.t
  tests/regression/46-apron2/88-unlock-unknown.c
  tests/regression/46-apron2/88-unlock-unknown.t
  tests/regression/46-apron2/dune
Labels: bug, unsound, relational

#1495 Simplify `SetDomain.FiniteSet` for first analysis tutorial
  docs/developer-guide/firstanalysis.md
  src/domain/setDomain.ml
  tests/unit/maindomaintest.ml
Labels: cleanup, documentation

#1497 Improve output for component of blob indicating whether it was created with `malloc` or `calloc`
  src/analyses/base.ml
  src/cdomain/value/cdomains/valueDomain.ml
Labels: cleanup, usability

#1504 Remove some `Option.is_some` usages
  src/analyses/condVars.ml
  src/cdomain/value/cdomains/addressDomain.ml
  src/cdomain/value/cdomains/valueDomain.ml
  src/solver/generic.ml
Labels: cleanup

#1502 Narrowing from widening thresholds
  src/cdomain/value/cdomains/intDomain.ml
  tests/regression/03-practical/33-threshold-narrowing-intervals.c
  tests/regression/03-practical/34-threshold-narrowing-interval-sets.c
  tests/unit/cdomains/intDomainTest.ml
Labels: feature, student-job, precision

#1466 Extending Linear Two-Variable Equalities with Coefficients
  src/analyses/apron/relationAnalysis.apron.ml
  src/cdomains/apron/gobApron.apron.ml
  src/cdomains/apron/linearTwoVarEqualityDomain.apron.ml
  src/cdomains/apron/sharedFunctions.apron.ml
  tests/regression/77-lin2vareq/34-coefficient-features.c
Labels: precision, relational

#1505 Simplify some `Option.get` usages
  src/cdomain/value/cdomains/floatDomain.ml
  src/cdomain/value/cdomains/intDomain.ml
  src/common/cdomains/floatOps/floatOps.ml
  src/common/cdomains/floatOps/floatOps.mli
  tests/unit/cdomains/floatDomainTest.ml
Labels: cleanup

#1508 Introduce sync reason `JoinCall` & Limit `sync` at function start nodes
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/apron/relationPriv.apron.ml
  src/analyses/base.ml
  src/analyses/basePriv.ml
  src/analyses/basePriv.mli
  src/analyses/commonPriv.ml
  src/analyses/mCP.ml
  src/config/options.schema.json
  src/domains/queries.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  tests/regression/46-apron2/89-flag-ctx-sens.c
  tests/regression/80-context_gas/21-sync.c
  tests/regression/80-context_gas/22-sync-precision.c
Labels: bug, precision, relational

#1515 Fix `ctx.split` and `ctx.spawn` in non-call transfer functions
  src/framework/constraints.ml
Labels: bug, unsound

#1510 Enable `pthreadMutexType` analysis by default
  conf/examples/medium-program.json
  conf/examples/very-precise.json
  src/analyses/mutexTypeAnalysis.ml
  src/autoTune.ml
  src/config/options.schema.json
Labels: usability, precision

#1511 Binary operations on pointers should not generate overflow warnings in SV-COMP
  docs/user-guide/assumptions.md
  src/analyses/base.ml
  src/cdomain/value/cdomains/offset.ml
  tests/regression/55-loop-unrolling/12-loop-no-overflows.c
  tests/regression/55-loop-unrolling/13-unrolled-loop-no-overflows.c
Labels: sv-comp, precision, documentation

#1521 Nicer SV-COMP result for validator when witness is missing
  src/analyses/unassumeAnalysis.ml
  src/framework/control.ml
  src/goblint.ml
  src/witness/svcomp.ml
  src/witness/witness.ml
  src/witness/yamlWitness.ml
Labels: cleanup, usability, sv-comp

#1529 Add opam package description and tags
  dune-project
  goblint.opam
  goblint.opam.locked
Labels: documentation, setup

#1530 Update results table in `relationalAnalysis` only if `exp.relation.prec-dump` is set
  src/analyses/apron/relationAnalysis.apron.ml
Labels: performance
