Repository goblint/analyzer, pull requests merged in 2024-05, with the labels that each got.

#1435 Fix catch-all exception handlers
  src/analyses/base.ml
  src/cdomain/value/cdomains/addressDomain.ml
  src/common/util/cilfacade.ml
  src/config/gobConfig.ml
  src/config/jsonSchema.ml
  src/goblint_lib.ml
  src/transform/expressionEvaluation.ml
  src/util/backtrace/goblint_backtrace.ml
  src/util/gobExn.ml
  src/util/loopUnrolling.ml
  src/util/server.ml
  src/util/timeout.ml
Labels: cleanup, bug

#1444 Fix relation analysis ignoring extern inits
  src/analyses/apron/relationAnalysis.apron.ml
  tests/regression/46-apron2/84-relation-extern.c
Labels: bug, unsound, sv-comp, relational

#1441 Fix unsoundness from relation analysis reading special mutexes as integer variables
  src/analyses/apron/relationPriv.apron.ml
  src/util/library/libraryFunctions.ml
  tests/regression/46-apron2/69-atomic-live.c
Labels: bug, unsound, sv-comp, relational

#1407 Avoid emitting reflexive pointer refines for locking
  src/analyses/mutexEventsAnalysis.ml
Labels: performance

#1445 Make all usages of `Obj` explicit
  .semgrep/obj.yml
  src/analyses/mCP.ml
  src/analyses/mCPAccess.ml
  src/analyses/mCPRegistry.ml
Labels: cleanup, type-safety

#1452 Make server `files` request include names of analyzed files when `pre.enabled = false`
  src/maingoblint.ml
Labels: bug, usability

#1439 Fix context gas in g2html
  src/framework/constraints.ml
Labels: feature, student-job

#1463 Fix `BaseDomain` top `priv` typo
  src/cdomains/baseDomain.ml
Labels: bug

#1412 Lin2var relations fine-tuning - switching from array to map
  src/cdomains/apron/linearTwoVarEqualityDomain.apron.ml
  src/cdomains/apron/sharedFunctions.apron.ml
  tests/regression/77-lin2vareq/33-dimarray.c
Labels: performance, relational

#1458 `BaseAnalysis`: For non-definite AD, join over **all** components not just `cpa` in `set`
  src/analyses/base.ml
  tests/regression/13-privatized/80-nondet-struct-ptr.c
  tests/regression/13-privatized/81-nondet-local-pointer.c
  tests/regression/13-privatized/82-nondet-global-pointer.c
  tests/regression/13-privatized/83-nondet-struct-ptr-write.c
  tests/regression/13-privatized/84-nondet-local-pointer-write.c
  tests/regression/13-privatized/85-nondet-global-pointer-write.c
  tests/regression/13-privatized/86-nondet-struct-ptr-lock.c
  tests/regression/13-privatized/87-nondet-local-pointer-lock.c
  tests/regression/13-privatized/88-nondet-global-pointer-lock.c
Labels: bug, unsound

#1427 Pass `ctx` to context & Simplify callstring-based approaches
  src/analyses/abortUnless.ml
  src/analyses/accessAnalysis.ml
  src/analyses/activeSetjmp.ml
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/base.ml
  src/analyses/callstring.ml
  src/analyses/condVars.ml
  src/analyses/expsplit.ml
  src/analyses/extractPthread.ml
  src/analyses/locksetAnalysis.ml
  src/analyses/loopTermination.ml
  src/analyses/loopfreeCallstring.ml
  src/analyses/mCP.ml
  src/analyses/mallocFresh.ml
  src/analyses/malloc_null.ml
  src/analyses/memLeak.ml
  src/analyses/memOutOfBounds.ml
  src/analyses/pthreadSignals.ml
  src/analyses/region.ml
  src/analyses/stackTrace.ml
  src/analyses/symbLocks.ml
  src/analyses/threadAnalysis.ml
  src/analyses/threadEscape.ml
  src/analyses/threadFlag.ml
  src/analyses/threadId.ml
  src/analyses/threadJoins.ml
  src/analyses/threadReturn.ml
  src/analyses/tutorials/signs.ml
  src/analyses/tutorials/taint.ml
  src/analyses/tutorials/unitAnalysis.ml
  src/analyses/uninit.ml
  src/analyses/varEq.ml
  src/analyses/wrapperFunctionAnalysis.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/util/wideningTokens.ml
  src/witness/observerAnalysis.ml
  src/witness/witnessConstraints.ml
Labels: cleanup, performance

#1471 Union: `meet` in `Field`: Do not raise `Uncomparable` when one arg is `Top`
  src/cdomain/value/cdomains/unionDomain.ml
  tests/regression/13-privatized/90-union.c
  tests/regression/13-privatized/91-union-direct.c
Labels: bug, precision

#1476 Fix unsoundness bug in interval sets and refactor interval widen thresholds
  src/cdomain/value/cdomains/intDomain.ml
  tests/unit/cdomains/intDomainTest.ml
Labels: cleanup, bug, unsound, sv-comp

#1475 Make privatization `sync Join` more precise when threadflag is path-sensitive
  src/analyses/apron/relationPriv.apron.ml
  src/analyses/basePriv.ml
  src/analyses/commonPriv.ml
  tests/regression/62-abortUnless/05-apron-mutex-meet-abortUnless.c
  tests/regression/62-abortUnless/dune
Labels: sv-comp, precision, performance

#1469 Separate soundness settings from precision improvements in the autotuner
  src/autoTune.ml
  src/goblint.ml
  src/goblint_lib.ml
  src/maingoblint.ml
  src/util/autoSoundConfig.ml
  tests/regression/29-svcomp/32-no-ov.t
  tests/regression/78-termination/51-modulo.c
Labels: cleanup, unsound, usability, sv-comp, unsound-usability

#1450 Improve autotune for octagon
  src/analyses/apron/relationAnalysis.apron.ml
  src/autoTune.ml
  tests/regression/29-svcomp/35-nla-sqrt.c
  tests/regression/29-svcomp/dune
Labels: sv-comp, precision, relational

#1447 Port all remaining library functions
  src/config/options.schema.json
  src/util/library/libraryDsl.ml
  src/util/library/libraryDsl.mli
  src/util/library/libraryFunctions.ml
Labels: cleanup

#1430 Refactor must-locksets to use definite mvals instead of addresses
  src/analyses/commonPriv.ml
  src/analyses/deadlock.ml
  src/analyses/locksetAnalysis.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/mutexEventsAnalysis.ml
  src/analyses/symbLocks.ml
  src/cdomain/value/cdomains/mval.ml
  src/cdomain/value/cdomains/mval_intf.ml
  src/cdomain/value/cdomains/offset.ml
  src/cdomain/value/cdomains/offset_intf.ml
  src/cdomains/lockDomain.ml
  src/cdomains/symbLocksDomain.ml
  src/common/domains/printable.ml
  src/domains/events.ml
  src/domains/queries.ml
  tests/regression/05-lval_ls/24-idxunknown_recursive.c
  tests/regression/05-lval_ls/25-idxunknown_recursive_2.c
  tests/regression/06-symbeq/21-mult_accs_rc.t
Labels: cleanup, bug, unsound, type-safety

#1487 Remove library functions old specification mechanisms
  src/util/library/libraryDesc.ml
  src/util/library/libraryFunctions.ml
Labels: cleanup

#1462 Fix witness `enter` sync map when caller state changes
  src/witness/witnessConstraints.ml
  tests/regression/56-witness/54-witness-lifter-abortUnless.c
  tests/regression/56-witness/54-witness-lifter-abortUnless.t
  tests/regression/56-witness/dune
Labels: bug, sv-comp

#1464 Activate abortUnless in svcomp conf
  conf/svcomp.json
Labels: feature, sv-comp, precision
