Repository goblint/analyzer, pull requests merged in 2024-12, with the labels that each got.

#1638 Add VMCAI '25 artifact description to docs
  docs/artifact-descriptions/vmcai25.md
  mkdocs.yml
Labels: documentation

#1606 Split `IntDomain`s into separate files
  scripts/goblint-lib-modules.py
  src/cdomain/value/cdomains/int/congruenceDomain.ml
  src/cdomain/value/cdomains/int/defExcDomain.ml
  src/cdomain/value/cdomains/int/enumsDomain.ml
  src/cdomain/value/cdomains/int/intDomTuple.ml
  src/cdomain/value/cdomains/int/intervalDomain.ml
  src/cdomain/value/cdomains/int/intervalSetDomain.ml
  src/cdomain/value/cdomains/intDomain.ml
  src/cdomain/value/cdomains/intDomain0.ml
Labels: cleanup

#1619 Print innermost backtrace mark for uncaught exception even with backtrace printing off
  src/util/backtrace/goblint_backtrace.ml
  src/util/backtrace/goblint_backtrace.mli
Labels: usability

#1573 Improve use of `Lattice.BotValue` and `Lattice.TopValue`
  src/cdomain/value/cdomains/stringDomain.ml
  src/cdomains/stackDomain.ml
  src/domain/lattice.ml
  src/domain/mapDomain.ml
  src/domains/domainProperties.ml
  tests/unit/domains/mapDomainTest.ml
Labels: cleanup

#1640 Fix `mine-W-noinit` not resetting W in `threadenter`
  src/analyses/basePriv.ml
  tests/regression/13-privatized/96-mine-W-threadenter.c
Labels: bug, precision

#1649 wrap speculative mode around bounds computation
  src/cdomains/apron/sharedFunctions.apron.ml
  tests/regression/77-lin2vareq/36-relations-overflow.c
Labels: bug, sv-comp, precision, relational

#1580 Add termination analysis success messages for loop bounds
  src/analyses/loopTermination.ml
  src/config/options.schema.json
Labels: cleanup, feature, usability, sv-comp, explainability

#1552 Optimize `none` base privatization, add eager Vojdani privatization
  src/analyses/basePriv.ml
  src/analyses/commonPriv.ml
  src/config/options.schema.json
  src/framework/constraints.ml
  tests/regression/13-privatized/01-priv_nr.t
Labels: performance, benchmarking
