Repository goblint/analyzer, pull requests merged in 2024-01, with the labels that each got.

#688 Klever concurrency safety support
  conf/ldv-races.json
  src/analyses/base.ml
  src/config/options.schema.json
  src/util/library/libraryDesc.ml
  src/util/library/libraryFunctions.ml
  tests/regression/51-threadjoins/08-klever-multiple.c
  unittest/analyses/libraryDslTest.ml
Labels: benchmarking

#1316 Add Karoliine as a maintainer to relevant files
  dune-project
  goblint.opam
  goblint.opam.locked
Labels: setup

#1278 Generalize mutex-meet-tid privatization to arbitrary digest
  src/analyses/apron/relationPriv.apron.ml
  src/analyses/basePriv.ml
  src/analyses/commonPriv.ml
Labels: cleanup, feature

#1323 Implement `combine_assign` in `threadEscape`
  src/analyses/base.ml
  src/analyses/region.ml
  src/analyses/threadEscape.ml
  src/util/returnUtil.ml
  tests/regression/45-escape/09-id-local-in-global.c
Labels: bug, unsound

#1310 Unbox some types
  src/cdomain/value/cdomains/floatDomain.ml
  src/cdomain/value/cdomains/intDomain.ml
  src/domains/queries.ml
  src/framework/analyses.ml
Labels: performance

#1327 `affeq`: Fix array OOB in `invariant`
  src/cdomains/apron/affineEqualityDomain.apron.ml
  tests/regression/63-affeq/19-witness.c
Labels: bug

#1063 Add CIL's ptranal for `EvalFunvar` queries
  src/analyses/ptranalAnalysis.ml
  src/goblint_lib.ml
  tests/regression/33-constants/05-fun_ptranal.c
Labels: feature, performance

#1233 Fix both branches dead from bot address in array
  src/cdomain/value/cdomains/valueDomain.ml
  tests/regression/00-sanity/41-both_branches-2.c
  tests/regression/03-practical/31-zstd-cctxpool-blobs.c
Labels: bug, unsound, benchmarking

#1332 Add VMCAI '24 artifact description to docs
  docs/artifact-descriptions/vmcai24.md
  mkdocs.yml
Labels: documentation

#1308 Remove duplicate ctx-derived arguments in base analysis
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
Labels: cleanup

#1335 Fix `NullPtr` assignment crash in relation analysis
  src/analyses/apron/relationAnalysis.apron.ml
  tests/regression/46-apron2/58-issue-1249.c
Labels: bug, sv-comp

#1342 Apron: Only replace deref expression with pointed to variable if types coincide
  src/analyses/apron/relationAnalysis.apron.ml
  tests/regression/46-apron2/59-issue-1319.c
Labels: bug, relational

#1324 Consider `Alloca` everywhere where `Malloc`, `Calloc` and `Realloc` are handled
  src/analyses/mallocFresh.ml
  src/analyses/region.ml
  src/util/loopUnrolling.ml
  tests/regression/45-escape/49-fresh-alloca.c
Labels: precision

#1329 Use Z module directly
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/cdomain/value/cdomains/arrayDomain.ml
  src/cdomain/value/cdomains/intDomain.ml
  src/cdomain/value/cdomains/intDomain.mli
  src/cdomain/value/cdomains/nullByteSet.ml
  src/cdomain/value/cdomains/offset.ml
  src/cdomain/value/cdomains/valueDomain.ml
  src/cdomains/apron/affineEqualityDomain.apron.ml
  src/cdomains/apron/apronDomain.apron.ml
  src/cdomains/apron/sharedFunctions.apron.ml
  src/cdomains/baseDomain.ml
  src/cdomains/vectorMatrix.ml
  src/common/util/cilfacade.ml
  src/common/util/intOps.ml
  src/domains/intDomainProperties.ml
  src/transform/expressionEvaluation.ml
  src/transform/transform.ml
  src/util/std/gobZ.ml
  unittest/cdomains/intDomainTest.ml
Labels: cleanup

#1347 Fix no function to call warnings on dead code
  src/framework/constraints.ml
  tests/regression/00-sanity/38-evalfunvar-dead.c
Labels: bug, usability

#1345 `eval_rv_base`: cast without `torg` when `typeOf` fails
  src/analyses/base.ml
  tests/regression/46-apron2/60-issue-1338.c
Labels: bug, relational

#1343 Refine Points-To set on locking a mutex
  src/analyses/mutexEventsAnalysis.ml
  tests/regression/04-mutex/96-split.c
  tests/regression/04-mutex/97-split-mt.c
Labels: feature, precision
