Repository goblint/analyzer, pull requests merged in 2025-07, with the labels that each got.

#1772 Add assumption about array index reads
  docs/user-guide/assumptions.md
Labels: unsound, documentation

#1775 Relational & VarEq: Invalidate LHS on `Longjmpd` event
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/varEq.ml
  tests/regression/24-octagon/19-sjlj.c
  tests/regression/68-longjmp/57-vareq.c
Labels: bug, unsound, relational

#1773 affeq: optimize sparse affeq join
  src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
  src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
  src/cdomains/apron/affineEqualityDomain.apron.ml
Labels: performance, relational

#1777 Consider option that `malloc(0)` may return `NULL`
  src/analyses/base.ml
  src/analyses/mallocFresh.ml
  src/analyses/memLeak.ml
  src/analyses/useAfterFree.ml
  src/analyses/wrapperFunctionAnalysis.ml
  src/config/options.schema.json
  src/domains/queries.ml
  tests/regression/11-heap/19-malloc-zero.c
Labels: cleanup, feature, unsound

#1780 Bump goblint-cil (c.f. https://github.com/goblint/cil/pull/184)
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
Labels: dependencies, c11

#1778 Adjust `test_FI_div_zero_result_top` QCheck test property to account for the 0/0 case
  src/cdomain/value/cdomains/floatDomain.ml
  tests/unit/cdomains/floatDomainTest.ml
Labels: testing

#1646 Relational: Use same invalidation strategy as base
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/base.ml
  tests/regression/46-apron2/93-invalidate-more.c
  tests/regression/46-apron2/94-weird.c
  tests/regression/46-apron2/94-weird.t
  tests/regression/46-apron2/94-weird.yml
Labels: bug, precision, relational

#1785 Turn `malloc_null` into an analysis serving as path-sens hint only & Fix enter
  src/analyses/malloc_null.ml
  tests/regression/08-malloc_null/01-simple-malloc.c
  tests/regression/08-malloc_null/02-paths-malloc.c
  tests/regression/08-malloc_null/03-interproc.c
Labels: cleanup, bug, unsound

#1784 Add semgrep rule for `BatEnum`
  .semgrep/batenum.yml
  src/analyses/apron/relationPriv.apron.ml
  src/analyses/assert.ml
  src/analyses/extractPthread.ml
  src/cdomains/apron/linearTwoVarEqualityDomain.apron.ml
  src/cdomains/congruenceClosure.ml
  src/cdomains/unionFind.ml
  src/common/util/messages.ml
  src/config/gobConfig.ml
  src/domain/hoareDomain.ml
  src/framework/analysisResult.ml
  src/framework/control.ml
  src/solver/td3.ml
  src/util/preprocessor.ml
  src/util/sarif.ml
  src/util/std/gobTuple.ml
Labels: cleanup, good first issue

#1787 Fix and update lower-bounds CI
  .github/workflows/unlocked.yml
Labels: cleanup, setup

#1788 Fix variables protected by mutex calculation
  src/analyses/basePriv.ml
  src/analyses/commonPriv.ml
  src/analyses/mutexAnalysis.ml
  src/domains/queries.ml
  tests/regression/13-privatized/19-publish-precision.t
  tests/regression/13-privatized/20-publish-regression.t
  tests/regression/46-apron2/98-issue-1511b.t
Labels: cleanup, bug

#1792 `BranchSet` analysis tracking set of taken branches
  src/analyses/branchSet.ml
  src/config/options.schema.json
  src/goblint_lib.ml
  tests/regression/88-branchset/01-set.c
Labels: feature, sv-comp, precision

#1790 Pin CIL with global state removed from `Pretty`
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
Labels: bug, sv-comp, pr-dependency, parallel

#1799 Fix copy-paste typo in interval set overflow handling
  src/cdomain/value/cdomains/int/intervalSetDomain.ml
  tests/regression/67-interval-sets-two/59-issue-1798.c
Labels: bug, unsound
