Repository goblint/analyzer, pull requests merged in 2025-04, with the labels that each got.

#1721 Fallback for malloc uniqueness for when threading analyses are disabled
  src/analyses/wrapperFunctionAnalysis.ml
  tests/regression/11-heap/18-unique-st.c
Labels: sv-comp, precision

#1483 Implement delayed widening
  src/config/options.schema.json
  src/framework/control.ml
  src/goblint_lib.ml
  src/lifters/wideningDelay.ml
  tests/regression/82-widen/01-side_parallel.c
  tests/regression/82-widen/02-loop_increment.c
  tests/regression/82-widen/03-loop_conditional_side.c
  tests/regression/82-widen/04-side_simple_update.c
  tests/regression/82-widen/05-side_and_no_side.c
  tests/regression/82-widen/06-post_loop1.c
  tests/regression/82-widen/07-post_loop2.c
  tests/regression/82-widen/08-semaphore.c
  tests/regression/82-widen/10-mine-tutorial-ex4.8-delay.c
  tests/regression/82-widen/11-mihaila-widen-fig7-delay.c
  tests/regression/82-widen/12-mihaila-widen-slide-delay.c
  tests/regression/82-widen/13-mine14-delay.c
Labels: feature, student-job, precision

#1726 Document def_exc and enums exclusion bit range assumption
  src/cdomain/value/cdomains/int/defExcDomain.ml
  src/cdomain/value/cdomains/int/enumsDomain.ml
  src/cdomain/value/cdomains/intDomain0.ml
Labels: documentation

#1727 Remove dummy `top` and `is_top` implementations from int domains
  src/cdomain/value/cdomains/int/defExcDomain.ml
  src/cdomain/value/cdomains/int/enumsDomain.ml
  src/cdomain/value/cdomains/int/intDomTuple.ml
  src/cdomain/value/cdomains/int/intervalDomain.ml
  src/cdomain/value/cdomains/int/intervalSetDomain.ml
  src/cdomain/value/cdomains/intDomain.mli
  src/cdomain/value/cdomains/intDomain0.ml
  src/domain/lattice.ml
  tests/regression/01-cpa/60-def_exc-int128.c
  tests/unit/cdomains/intDomainTest.ml
Labels: cleanup, bug, unsound, type-safety

#1636 Narrowing of globals in TD
  src/analyses/basePriv.ml
  src/config/options.schema.json
  src/constraint/constrSys.ml
  src/framework/constraints.ml
  src/maingoblint.ml
  src/solver/goblint_solver.ml
  src/solver/td3.ml
  src/solver/td3UpdateRule.ml
  tests/regression/85-narrow_globs/01-modulo-guard.c
  tests/regression/85-narrow_globs/02-state-machine.c
  tests/regression/85-narrow_globs/03-guarded_inc.c
  tests/regression/85-narrow_globs/04-semaphore.c
  tests/regression/85-narrow_globs/05-nested_loop.c
  tests/regression/85-narrow_globs/06-cyclic-dependency.c
  tests/regression/85-narrow_globs/07-ctxt-widen.c
  tests/regression/85-narrow_globs/08-ctxt-insensitive.c
  tests/regression/85-narrow_globs/09-longjmp-counting-local.c
  tests/regression/85-narrow_globs/10-longjmp-heap-counting-return.c
  tests/regression/85-narrow_globs/11-longjmp-counting-return.c
  tests/regression/85-narrow_globs/12-multiple-growing-updates.c
  tests/regression/85-narrow_globs/13-threaded-ctxt-widen.c
  tests/regression/85-narrow_globs/14-widening-thresholds.c
  tests/regression/85-narrow_globs/15-intertwined_increment.c
  tests/regression/85-narrow_globs/16-cyclic-dependency-guarded.c
  tests/regression/85-narrow_globs/17-dead-side-effect.c
  tests/regression/85-narrow_globs/18-dead-side-effect2.c
  tests/regression/85-narrow_globs/19-dead-side-effect3.c
  tests/regression/85-narrow_globs/20-dead-side-effect4.c
  tests/regression/85-narrow_globs/21-dead-escape.c
  tests/regression/85-narrow_globs/22-dead-escape-indirect.c
  tests/unit/solver/solverTest.ml
Labels: feature, student-job, precision

#1728 Weaken `Lattice.Lift{,2}Conf` arguments, remove `Lattice.LiftPO`
  src/analyses/mCPRegistry.ml
  src/cdomain/value/cdomains/intDomain0.ml
  src/domain/lattice.ml
Labels: cleanup, type-safety

#1731 Use generic `Spec` lifters for delayed widening
  src/lifters/specLifters.ml
  src/lifters/wideningDelay.ml
Labels: cleanup

#1733 Disable `graphml` witnesses in `svcomp.json`
  conf/svcomp-validate.json
  conf/svcomp.json
Labels: cleanup, sv-comp, performance

#1724 Explicitly specify no-argument function pointers in tests
  tests/incremental/11-restart/11-paper-example.c
  tests/regression/00-sanity/15-unused_arg.c
  tests/regression/00-sanity/38-evalfunvar-dead.c
  tests/regression/01-cpa/06-pointers.c
  tests/regression/01-cpa/09-arrays.c
  tests/regression/01-cpa/46-funptr_path.c
  tests/regression/02-base/46-spawn-global-funptrs.c
  tests/regression/03-practical/06-callback.c
  tests/regression/04-mutex/19-call_by_ptr_rc.c
  tests/regression/04-mutex/21-sound_base.c
  tests/regression/04-mutex/27-base_rc.c
  tests/regression/04-mutex/28-base_nr.c
  tests/regression/04-mutex/29-funstruct_rc.c
  tests/regression/04-mutex/30-funstruct_nr.c
  tests/regression/04-mutex/50-funptr_rc.c
  tests/regression/04-mutex/56-extern_call_by_ptr_rc.c
  tests/regression/13-privatized/95-mm-calloc.c
  tests/regression/22-partitioned_arrays/05-adapted_from_01_09_array.c
  tests/regression/23-partitioned_arrays_last/05-adapted_from_01_09_array.c
  tests/regression/28-race_reach/19-callback_racing.c
  tests/regression/28-race_reach/20-callback_racefree.c
  tests/regression/28-race_reach/27-funptr_racing.c
  tests/regression/28-race_reach/28-funptr_racefree.c
  tests/regression/28-race_reach/95-deref-fun.c
  tests/regression/67-interval-sets-two/18-adapted_from_01_09_array.c
  tests/sv-comp/cfg/free_spawn_ub_true-unreach-call.c
  tests/sv-comp/cfg/free_spawn_ub_true-unreach-call.expected
Labels: cleanup, testing, type-safety
