Repository goblint/analyzer, pull requests merged in 2025-05, with the labels that each got.

#1738 Remove GraphML witness export
  conf/ldv-races.json
  conf/svcomp-ghost.json
  conf/svcomp-yaml.json
  conf/svcomp21.json
  conf/svcomp22-intervals-novareq-affeq-apron.json
  conf/svcomp22-intervals-novareq-affeq-native.json
  conf/svcomp22-intervals-novareq-octagon-apron.json
  conf/svcomp22-intervals-novareq-polyhedra-apron.json
  conf/svcomp22.json
  conf/svcomp23.json
  conf/svcomp24-validate.json
  conf/svcomp24.json
  conf/svcomp25-validate.json
  conf/svcomp25.json
  conf/svcomp2var.json
  docs/user-guide/inspecting.md
  scripts/sv-comp/yed-sv-comp.cnfx
  src/arg/argConstraints.ml
  src/arg/argTools.ml
  src/arg/myARG.ml
  src/arg/observerAnalysis.ml
  src/arg/observerAutomaton.ml
  src/arg/violation.ml
  src/arg/z3/dune
  src/arg/z3/violationZ3.no-z3.ml
  src/arg/z3/violationZ3.z3.ml
  src/config/options.schema.json
  src/dune
  src/framework/control.ml
  src/goblint_lib.ml
  src/maingoblint.ml
  src/witness/graphml.ml
  src/witness/svcomp.ml
  src/witness/witness.ml
  tests/regression/00-sanity/19-if-0.t
  tests/regression/00-sanity/20-if-0-realnode.t
  tests/regression/00-sanity/21-empty-loops.t
  tests/regression/55-loop-unrolling/11-unrolled-loop-invariant.t
  tests/regression/56-witness/52-witness-lifter-ps2.c
  tests/regression/56-witness/53-witness-lifter-ps3.c
  tests/regression/cfg/foo.t/run.t
  tests/regression/cfg/issue-1356.t/run.t
  tests/regression/cfg/loops.t/run.t
  tests/regression/cfg/pr-758.t/run.t
  tests/regression/cfg/util/cfgDot.ml
  tests/sv-comp/basic/if_trier_exclude_multiple_false-unreach-call.expected
  tests/sv-comp/basic/if_trier_exclude_multiple_true-unreach-call.expected
  tests/sv-comp/cfg/multicall_join_true-unreach-call.expected
  tests/sv-comp/cfg/multicall_true-unreach-call.expected
  tests/sv-comp/dune.inc
  tests/sv-comp/gen/gen.ml
  tests/sv-comp/observer/path_nofun_true-unreach-call.c
Labels: cleanup, sv-comp

#1741 Deduplicate `IntDomain` module types
  src/cdomain/value/cdomains/intDomain.mli
  src/cdomain/value/cdomains/intDomain0.ml
  src/cdomain/value/cdomains/intDomain_intf.ml
Labels: cleanup

#1742 Remove `IntDomain.Size.top_typ`
  src/cdomain/value/cdomains/intDomain0.ml
  src/cdomain/value/cdomains/intDomain_intf.ml
  src/cdomain/value/cdomains/valueDomain.ml
Labels: cleanup

#1705 Add bash completion for array element addition and removal
  src/config/options.ml
Labels: feature, usability

#1744 Remove some usages of `MyCFG.current_node`
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/analyses/extractPthread.ml
  src/analyses/raceAnalysis.ml
  src/cdomain/value/util/precisionUtil.ml
  src/cdomains/pthreadDomain.ml
  src/config/options.schema.json
  src/framework/control.ml
  src/lifters/specLifters.ml
Labels: cleanup, parallel

#1746 Introduce demand in constraint system
  src/constraint/constrSys.ml
  src/constraint/solverTypes.ml
  src/constraint/translators.ml
  src/framework/analyses.ml
  src/framework/constraints.ml
  src/framework/control.ml
  src/solver/effectWConEq.ml
  src/solver/generic.ml
  src/solver/postSolver.ml
  src/solver/sLR.ml
  src/solver/sLRphased.ml
  src/solver/sLRterm.ml
  src/solver/selector.ml
  src/solver/td3.ml
  src/solver/td_simplified.ml
  src/solver/topDown.ml
  src/solver/topDown_deprecated.ml
  src/solver/topDown_space_cache_term.ml
  src/solver/topDown_term.ml
  src/solver/worklist.ml
  tests/unit/solver/solverTest.ml
Labels: feature, performance, parallel

#1748 Parallelism: Add data utils
  scripts/goblint-lib-modules.py
  src/index.mld
  src/util/parallel/data.ml
  src/util/parallel/data.mli
  src/util/parallel/dune
  src/util/parallel/goblint_parallel.ml
Labels: feature, parallel
