Repository goblint/analyzer, pull requests merged in 2025-01, with the labels that each got.

#1644 Make `update_offset` idempotent for blobs
  src/cdomain/value/cdomains/valueDomain.ml
  tests/regression/13-privatized/95-mm-calloc.c
Labels: bug, unsound

#1626 Introduce a simplified version of td3 with warrowing (see PR 1611)
  src/solver/goblint_solver.ml
  src/solver/td_simplified.ml
  tests/regression/00-sanity/01-assert.t
Labels: student-job

#1641 Fixes for Self-Validation Issues
  src/analyses/apron/relationAnalysis.apron.ml
  tests/regression/46-apron2/95-witness-mm-escape.c
  tests/regression/46-apron2/95-witness-mm-escape.t
  tests/regression/46-apron2/95-witness-mm-escape.yml
  tests/regression/46-apron2/96-witness-mm-escape2.c
  tests/regression/46-apron2/96-witness-mm-escape2.t
  tests/regression/46-apron2/dune
Labels: bug, unsound, relational

#1655 Update CIL pin to exclude dynlink and reduce executable size
  goblint.opam
  goblint.opam.locked
  goblint.opam.template
Labels: setup, dependencies

#1654 Use sets for widening thresholds instead of lists
  src/autoTune.ml
  src/cdomain/value/cdomains/intDomain0.ml
  src/cdomain/value/util/wideningThresholds.ml
  src/cdomain/value/util/wideningThresholds.mli
  src/cdomains/apron/apronDomain.apron.ml
  src/common/util/resettableLazy.ml
  src/common/util/resettableLazy.mli
Labels: cleanup, performance

#1656 Fix Vojdani privatization `invariant_global`
  src/analyses/basePriv.ml
  src/analyses/mutexAnalysis.ml
  src/domains/queries.ml
  tests/regression/13-privatized/74-mutex.t
  tests/regression/56-witness/64-ghost-multiple-protecting.t
  tests/regression/56-witness/69-ghost-ptr-protection.t
Labels: bug, unsound, sv-comp

#1468 Make meet in AddressDomain more precise
  src/analyses/base.ml
  src/domain/disjointDomain.ml
  tests/regression/13-privatized/89-write-lacking-precision.c
  tests/regression/27-inv_invariants/23-meet-ptrs.c
Labels: bug, precision
