Repository goblint/analyzer, pull requests merged in 2025-03, with the labels that each got.

#1701 Fix refinement in `baseInvariant` for more complicated lvals
  src/analyses/baseInvariant.ml
  tests/regression/03-practical/36-struct-ptr.c
Labels: bug, unsound

#1677 Add missing type unrollings
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/analyses/extractPthread.ml
  src/analyses/memOutOfBounds.ml
  src/analyses/mutexAnalysis.ml
  src/analyses/raceAnalysis.ml
  src/analyses/tutorials/constants.ml
  src/autoTune.ml
  src/autoTune0.ml
  src/cdomain/value/cdomains/int/bitfieldDomain.ml
  src/cdomain/value/cdomains/int/congruenceDomain.ml
  src/cdomain/value/cdomains/intDomain.ml
  src/cdomain/value/cdomains/structDomain.ml
  src/cdomain/value/cdomains/valueDomain.ml
  src/cdomain/value/domains/invariantCil.ml
  src/cdomain/value/util/wideningThresholds.ml
  src/cdomains/apron/sharedFunctions.apron.ml
  src/common/framework/cfgTools.ml
  src/common/util/cilfacade.ml
  src/domains/access.ml
  src/framework/constraints.ml
  src/util/loopUnrolling.ml
Labels: cleanup, precision

#1692 Extract generic `Spec` domain and context lifters
  src/domain/lattice.ml
  src/domain/mapDomain.ml
  src/lifters/specLifters.ml
Labels: cleanup

#1695 Unit tests: Remove usages of polymorphic equality
  tests/unit/cdomains/intDomainTest.ml
Labels: bug, testing

#1703 Fix flaky cram tests where `vid`s leak into witnesses
  tests/regression/56-witness/66-ghost-alloc-lock.t
  tests/regression/56-witness/dune
  tests/regression/56-witness/strip-ghost-alloc.sh
Labels: bug, testing

#1700 Closing the gaps in Texpr generation
  src/cdomains/apron/sharedFunctions.apron.ml
Labels: precision, relational

#1717 Use LazyEval instead of Lazy in C2PODomain.
  src/analyses/c2poAnalysis.ml
  src/cdomains/c2poDomain.ml
  src/cdomains/congruenceClosure.ml
  src/cdomains/duplicateVars.ml
  src/common/util/lazyEval.ml
Labels: testing, relational

#1709 Use naïve unassume for Apron analysis when strengthening disabled
  src/analyses/apron/relationAnalysis.apron.ml
  tests/regression/56-witness/48-apron-unassume-no-strengthening.c
  tests/regression/56-witness/48-apron-unassume-no-strengthening.yml
  tests/regression/56-witness/dune
Labels: bug, sv-comp, precision

#1707 Update 56-witness/*-tm-inv-tranfer* tests
  tests/regression/56-witness/60-tm-inv-transfer-protection.c
  tests/regression/56-witness/61-tm-inv-transfer-mine.c
  tests/regression/56-witness/62-tm-inv-transfer-protection-witness-manual.yml
  tests/regression/56-witness/62-tm-inv-transfer-protection-witness.c
  tests/regression/56-witness/62-tm-inv-transfer-protection-witness.t
  tests/regression/56-witness/62-tm-inv-transfer-protection-witness.yml
Labels: testing, sv-comp

#1720 `IsMultiple` in `MallocWrapper`: Check uniqueness of allocating(!) thread
  src/analyses/wrapperFunctionAnalysis.ml
  tests/regression/11-heap/17-unique-mt.c
Labels: bug, unsound, sv-comp, precision
