Repository goblint/analyzer, pull requests merged in 2025-02, with the labels that each got.

#1442 Widening gas
  src/config/options.schema.json
  src/solver/goblint_solver.ml
  src/solver/sideWPointSelect.ml
  src/solver/td3.ml
  tests/regression/56-witness/60-tm-inv-transfer-protection.c
  tests/regression/82-widening_gas/01-side_parallel.c
  tests/regression/82-widening_gas/02-loop_increment.c
  tests/regression/82-widening_gas/03-loop_conditional_side.c
  tests/regression/82-widening_gas/04-side_simple_update.c
  tests/regression/82-widening_gas/05-side_and_no_side.c
  tests/regression/82-widening_gas/06-post_loop1.c
  tests/regression/82-widening_gas/07-post_loop2.c
  tests/regression/82-widening_gas/08-semaphore.c
Labels: feature, student-job, precision

#1672 Fix `fixpoint` option `ana.int.refinement` - loop was never executed
  src/cdomain/value/cdomains/int/intDomTuple.ml
Labels: bug, precision

#1670 Update bash-completion for arg-complete 0.2.x, remove `Arg_complete.Rest_all_compat`
  dune-project
  goblint.opam
  goblint.opam.locked
  scripts/bash-completion.sh
  src/maingoblint.ml
Labels: cleanup, usability

#1676 Recognize pointers wrapped in `TNamed` in `memOutOfBounds` and fix bit-to-byte comparison bug
  src/analyses/memOutOfBounds.ml
  src/cdomain/value/cdomains/valueDomain.ml
  tests/regression/01-cpa/76-pointer-typedef.c
  tests/regression/74-invalid_deref/32-dll2c_append_equal-mini.c
Labels: bug, sv-comp, precision

#1623 Bitfield Domain
  scripts/goblint-lib-modules.py
  src/analyses/base.ml
  src/analyses/baseInvariant.ml
  src/cdomain/value/cdomains/int/bitfieldDomain.ml
  src/cdomain/value/cdomains/int/congruenceDomain.ml
  src/cdomain/value/cdomains/int/defExcDomain.ml
  src/cdomain/value/cdomains/int/enumsDomain.ml
  src/cdomain/value/cdomains/int/intDomTuple.ml
  src/cdomain/value/cdomains/int/intervalDomain.ml
  src/cdomain/value/cdomains/int/intervalSetDomain.ml
  src/cdomain/value/cdomains/intDomain.ml
  src/cdomain/value/cdomains/intDomain.mli
  src/cdomain/value/cdomains/intDomain0.ml
  src/cdomain/value/util/precisionUtil.ml
  src/config/options.schema.json
  src/util/std/gobTuple.ml
  src/util/std/goblint_std.ml
  tests/regression/83-bitfield/00-simple-demo.c
  tests/regression/83-bitfield/01-simple-arith.c
  tests/regression/83-bitfield/02-complex-arith.c
  tests/regression/83-bitfield/03-simple-bitwise.c
  tests/regression/83-bitfield/04-complex-bitwise.c
  tests/regression/83-bitfield/05-refine-with-congruence.c
  tests/regression/83-bitfield/06-refine-with-incl-set.c
  tests/regression/83-bitfield/07-refine-with-interval.c
  tests/regression/83-bitfield/08-refine-with-bitfield.c
  tests/regression/83-bitfield/09-refine-intervalA.c
  tests/regression/83-bitfield/10-refine-intervalB.c
  tests/regression/83-bitfield/11-refine-intervalC.c
  tests/regression/83-bitfield/12-precision.c
  tests/regression/83-bitfield/13-join.c
  tests/unit/cdomains/intDomainTest.ml
  tests/unit/maindomaintest.ml
Labels: feature, in progress, student-job, precision, practical-course

#1679 Change `Offset.MakeLattice.to_index` to return bytes, not bits
  src/analyses/base.ml
  src/analyses/memOutOfBounds.ml
  src/cdomain/value/cdomains/offset.ml
  src/cdomain/value/cdomains/valueDomain.ml
  src/cdomains/lockDomain.ml
  src/common/util/cilfacade.ml
Labels: cleanup, bug, unsound

#1682 Ensure that `__goblint_check` does not affect memLeak analysis
  src/analyses/memLeak.ml
  tests/regression/76-memleak/32-no-mem-leak-goblint-check.c
  tests/regression/76-memleak/32-no-mem-leak-goblint-check.t
  tests/regression/76-memleak/dune
Labels: bug, testing, sv-comp

#1667 Disable race analyses for other ConcurrencySafety properties
  conf/svcomp-ghost.json
  conf/svcomp-validate.json
  conf/svcomp.json
  conf/svcomp23.json
  conf/svcomp24-validate.json
  conf/svcomp24.json
  conf/svcomp25-validate.json
  conf/svcomp25.json
  conf/svcomp2var.json
  src/autoTune.ml
  src/config/options.schema.json
  src/util/autoSoundConfig.ml
Labels: sv-comp, performance

#1685 Correctly cast offsets to `Cilfacade.ptrdiff_ikind ()` in memOutOfBounds
  src/analyses/memOutOfBounds.ml
  tests/regression/74-invalid_deref/33-enum-in-index.c
Labels: bug, sv-comp

#1645 PrivPrecCompare: Add `bot_in_blob_leq_bot` so `bot` and `Blob(bot)` are considered equal
  src/cdomain/value/cdomains/valueDomain.ml
  src/common/framework/analysisState.ml
  src/privPrecCompare.ml
Labels: usability, benchmarking

#1690 HashCachedContextLifter: Introduce the lifter and the option
  src/common/domains/printable.ml
  src/config/options.schema.json
  src/framework/control.ml
  src/lifters/specLifters.ml
Labels: feature, performance

#1688 Audit usages of `fold_right`
  src/analyses/apron/relationAnalysis.apron.ml
  src/analyses/base.ml
  src/analyses/malloc_null.ml
  src/analyses/region.ml
  src/analyses/symbLocks.ml
  src/analyses/uninit.ml
  src/analyses/varEq.ml
  src/cdomain/value/cdomains/int/defExcDomain.ml
  src/util/library/libraryFunctions.ml
Labels: cleanup

#1587 Unsound congruence domain arithmetic
  scripts/creduce/branches.sh
  src/cdomain/value/cdomains/int/congruenceDomain.ml
  tests/regression/37-congruence/15-congruence-hardness-unsound-branches.c
  tests/regression/37-congruence/16-refinement-fixpoint.c
  tests/regression/37-congruence/17-sub-congruence.c
Labels: bug, unsound, sv-comp

#1659 Consider pointees separately for refinement
  src/analyses/baseInvariant.ml
  tests/regression/27-inv_invariants/24-ptr.c
  tests/regression/27-inv_invariants/25-deadcode.c
Labels: feature, precision
